### PR TITLE
update Amazon EKS name on aws docs

### PR DESCRIPTION
**Pull request by shanidchamal**
old name: Amazon Elastic Container Service for Kubernetes
new name: Amazon Elastic Kubernetes Service

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1294)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/ok-to-test
/assign @Jeffwan 

@Jeffwan please would you review this PR?

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/1290

**Comment by Jeffwan** [comment]
/lgtm

EKS recently changes the name. Thanks for the change!

**Pull request merged**
