### PR TITLE
Add GPU node pool to an existing kubeflow cluster

### PR DESCRIPTION
**Pull request by fai555**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1432)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
@fai555 Thanks for this update! Please would you sign the CLA and then add a comment to this PR, as requested by the **googlebot** above. The PR will not merge until the CLA is signed. When you add the requested comment to this PR, the googlebot will perform the CLA check again.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1432--competent-brattain-de2d6d.netlify.com/docs/gke/customizing-gke/#add-gpu-node-pool-to-an-existing-kubeflow-cluster

**Comment by sarahmaddox** [comment]
@richardsliu Please would you review the proposed new section on adding GPU nodes to an existing cluster?

/assign @richardsliu 

@fai555 This change LGTM, apart from one small fix: Change "kubeflow" to "Kubeflow" in line 181. Also, please sign the CLA as mentioned in a previous comment.

**Comment by fai555** [comment]
@googlebot I signed it!

**Comment by fai555** [comment]
@sarahmaddox sorry for the delayed response. I have signed the CLA.

**Pull request merged**
