### PR TITLE
Add 1.9 version dropdown and make it latest version

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Review by tarilabs — COMMENTED** [review]
Assuming `v1.9-branch` branch will be "cut" from main at the date of release,
/lgtm
thank you!

**Review by andreyvelich — COMMENTED** [review]
Thank you @rimolive!
/lgtm
/approve

**Comment by thesuperzapper** [comment]
@james-jwu Someone needs to make the CNAME DNS record from:

`v1-9-branch.kubeflow.org` to `v1-8-branch--competent-brattain-de2d6d.netlify.app`

Because right now trying to go to https://v1-9-branch.kubeflow.org/ will fail.

**Pull request merged**
