### PR TITLE
Changed AWS kubeflow installation to be more in line with current documentation

### PR DESCRIPTION
**Pull request by MaanavD**
Apologies for all the messy open and closed pull requests. Once this gets pulled, my team and I have some working Azure docs that are ready to be committed as well.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/768)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @Jeffwan 

@Jeffwan Please would you take a look at these updates to the Kubeflow AWS docs. The PR changes the use of `kfctl.sh` script to the `kfctl` binary.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-768--competent-brattain-de2d6d.netlify.com/docs/aws/deploy/install-kubeflow/

**Comment by Jeffwan** [comment]
Thanks for the contribution. Kfctl is working well on AWS only with platform `none`. 
platform `aws` in golang kfctl has not been added yet. 

kfctl.sh provides several aws integrations and customizations. I am still in progress of kfctl golang. Once change is merged into upstream, then we should come back to this doc. 

I would suggest to hold this PR at this moment.

**Comment by sarahmaddox** [comment]
Thanks @Jeffwan!

Thanks again for your input @MaanavD! Let's close this PR for now, and re-open it when the AWS team are ready to support the kfctl binary.

/close

**Pull request closed without merging**
