### PR TITLE
Move `AWS` platform under /distributions

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Following the latest discussions on platforms and distributions starting a PR to move Kubeflow on AWS.

cc @joeliedtke @Bobgy @animeshsingh @8bitmp3

### CODE REVIEW

**Comment by 8bitmp3** [comment]
cc @Jeffwan @PatrickXYS

**Review by PatrickXYS — APPROVED** [review]
/lgtm
/approve

**Comment by RFMVasconcelos** [comment]
@PatrickXYS thank you for approving! Because this changes redirects file, it needs root OWNER approval

**Comment by 8bitmp3** [comment]
📣 Root owners please `/approve` @animeshsingh @Bobgy @joeliedtke 🙏 😃

**Comment by RFMVasconcelos** [comment]
Given that @PatrickXYS approves, I will go ahead and merge this one.
/approve

**Pull request merged**
