### PR TITLE
Adding 1.8 version to the dropdown menu list

### PR DESCRIPTION
**Pull request by Davidnet**
Adding 1.8 to the dropdown menu support.

This also requires that the branch v1.8-branch exist in the repo

### CODE REVIEW

**Comment by Davidnet** [comment]
@DnPlas So this will allow to have 1.8 on the website, but the repo needs to have a branch called v1.8-branch 

PTAL merci!

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@DnPlas @Davidnet this PR has created a dead link, as the https://v1-8-branch.kubeflow.org/ domain does NOT currently exist.

**Pull request merged**
