### PR TITLE
Removed content from NVIDIA server page and linked to NVIDIA docs

### PR DESCRIPTION
**Pull request by sarahmaddox**
Removed the content from the NVIDIA server page and pointed users at the v0.6 docs.

This fix unblocks Kubeflow v1.0 in terms of issue https://github.com/kubeflow/website/issues/959. With this change, we can reduce the priority of the issue (currently P0). We've been trying to find someone to fix this doc since July 2019, so I think it's fine to point to v0.6 as the last version that the instructions work for.

Preview: https://deploy-preview-1608--competent-brattain-de2d6d.netlify.com/docs/components/serving/trtinferenceserver/

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1608)

### CODE REVIEW

**Comment by jlewi** [comment]
Should we just refer to the NVIDIA inference server docs for info on deploying on K8s
https://github.com/NVIDIA/tensorrt-inference-server/tree/master/deploy/single_server?

**Comment by sarahmaddox** [comment]
> NVIDIA inference server docs for info on deploying on K8s
> https://github.com/NVIDIA/tensorrt-inference-server/tree/master/deploy/single_server

Thanks @jlewi Done.

**Comment by jlewi** [comment]
@sarahmaddox The statement NVIDIA inference server isn't supported on KF isn't quite accurate. Since the server works on K8s it will just work on Kubeflow. What we no longer have is any special documentation. 

So could we just say something like

"If you want to run NVIDIA inference server; please refer to the docs for running NVIDIA inference server on Kubernetes"

**Comment by sarahmaddox** [comment]
I see, thanks @jlewi I've modified the wording. PTAL.
https://deploy-preview-1608--competent-brattain-de2d6d.netlify.com/docs/components/serving/trtinferenceserver/

**Pull request merged**
