### PR TITLE
Corrected broken link to pytorch documentation

### PR DESCRIPTION
**Pull request by Rubiel1**
I suspect the correct link is https://github.com/kubeflow/kfserving/tree/master/python/pytorchserver

### CODE REVIEW

**Comment by 8bitmp3** [comment]
thank you

/lgtm

**Comment by 8bitmp3** [comment]
/assign  @adrian555 @animeshsingh @cliveseldon @ellistarn @ryandawsonuk @Tomcli @yuzisun

PTAL, small change (link fix). Thanks

**Comment by joeliedtke** [comment]
/ok-to-test

Preview: https://deploy-preview-2447--competent-brattain-de2d6d.netlify.app/docs/components/serving/overview/

**Comment by joeliedtke** [comment]
Looks like the [examples section was reorged](https://github.com/kubeflow/kfserving/commit/2f4f28a2c94086229d9d1e436c04d6f14d0b21c0#diff-5d3bd4fc0f3a73e4f7f82c661b0682b41c0c17f01d96c5a9410a8f44ecb3f38c) by @yuzisun in November. So, the current version of that link would be:

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/pytorch

@yuzisun, should that link be updated to use one of the v1beta1 samples?

**Pull request closed without merging**
