### PR TITLE
fixed typo in contributing.md

### PR DESCRIPTION
**Pull request by BrainLogic**

### CODE REVIEW

**Comment by BrainLogic** [comment]
@googlebot I signed it!

**Comment by BrainLogic** [comment]
@Jeffwan @pdmack could you please approve this tiny fix? this is just 1min review. Thanks.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you @BrainLogic !

/lgtm
/approve

**Pull request merged**
