### PR TITLE
Remove outdated banners, move GCP instructions to GKE folder

### PR DESCRIPTION
**Pull request by DavidSpek**
Closes: https://github.com/kubeflow/website/issues/2514

I went through the Notebook Server docs and removed the outdated banner. Everything seems up to date at the moment. Depending on what gets implemented for 1.3 the docs will need to get updated with the new functionality.
The instructions to build images on GCP were moved to the `Kubeflow on GCP` section, after confirming this with @Bobgy. 

@kubeflow/wg-notebooks-leads Is there anything missing in the docs that needs to be added?

/cc @RFMVasconcelos

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
@DavidSpek thank you for this PR! 

I've added a redirect to cover any outside links going to the old position of that page.

**Comment by DavidSpek** [comment]
@RFMVasconcelos Thanks, hadn't thought of that.

**Comment by RFMVasconcelos** [comment]
@animeshsingh could you please approve this PR?

**Comment by Bobgy** [comment]
/approve

Thank you!

**Pull request merged**
