### PR TITLE
Update component-development.md to showcase v2 compatible data passing.

### PR DESCRIPTION
**Pull request by chensun**
The current tutorial contains legacy data passing -- specifically passing a constant value to an input expect `inputPath`. This is not compatible with KFP v2 and Vertex Pipelines.
Update the sample to use compatible data passing that works on both KFP v1 and Vertex Pipelines.

Fixes: https://github.com/kubeflow/pipelines/issues/6112

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@kubeflow/wg-pipeline-leads could you PTAL?

**Comment by neuromage** [comment]
Thanks @RFMVasconcelos 
/approve

/cc @joeliedtke you may need to check/approve this

**Pull request merged**
