### PR TITLE
Add OWNERs file to > started section

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
As discussed in #2127, I'm adding myself as an approver for Getting-started docs. 

Happy to add others to the list.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@andreyvelich @8bitmp3 @jlewi

**Review by andreyvelich — APPROVED** [review]
Thank you for your help @RFMVasconcelos.
/lgtm

**Comment by RFMVasconcelos** [comment]
@Bobgy @joeliedtke @rmgogogo, can I please ask you to accelerate this PR, so I can start reviewing docs?  🚀

Many thanks!

**Comment by rmgogogo** [comment]
Would leave this to Joe. My personal preference is that better we let Joe centrally approve docs, especially the common part. 

Which doc changes you plan to make? I may missed few PRs.

**Comment by Bobgy** [comment]
/approve

Thank you for offering help!

**Pull request merged**
