### PR TITLE
[Katib] Update documentation for suggestion algorithms

### PR DESCRIPTION
**Pull request by tenzen-y**
I updated documentation for suggestion algorithms.

1. Add Optuna to the documentation for the grid search algorithm
2. Remove Chocolate from all documentation

Part-of: https://github.com/kubeflow/katib/issues/2058

/hold for https://github.com/kubeflow/katib/pull/2071

/assign @kubeflow/wg-automl-leads

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thanks for the update @tenzen-y !
/lgtm
/assign @johnugeorge

**Comment by johnugeorge** [comment]
@tenzen-y Can you rebase?

**Comment by tenzen-y** [comment]
@andreyvelich @johnugeorge Thanks for the review!
I have rebased it.

**Pull request merged**
