### PR TITLE
update hugo version

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/kubeflow/website/issues/3055

### CODE REVIEW

**Comment by Arhell** [comment]
/asssign @Bobgy 
Checked locally & https://deploy-preview-3058--competent-brattain-de2d6d.netlify.app/

**Comment by Arhell** [comment]
/assign @Bobgy 
Checked locally & https://deploy-preview-3058--competent-brattain-de2d6d.netlify.app/

**Comment by Bobgy** [comment]
Thank you!
/lgtm
/approve

**Pull request merged**
