### PR TITLE
MR: update getting started

### PR DESCRIPTION
**Pull request by isinyaaa**

### CODE REVIEW

**Comment by isinyaaa** [comment]
cc: @tarilabs

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by tarilabs — COMMENTED** [review]
This changes looks good to me, thank you @isinyaaa but I need to wait for 0.2.3

**Comment by tarilabs** [comment]
With the additional changes of: https://github.com/isinyaaa/kubeflow-website/pull/2

Tested all tutorial:
- 
Screenshot from 2024-07-15 08-37-56
- 
Screenshot from 2024-07-15 08-38-22
- 
Screenshot from 2024-07-15 08-45-39
- 
[getting-started.ipynb.zip](https://github.com/user-attachments/files/16230909/getting-started.ipynb.zip)


Will wait for https://github.com/isinyaaa/kubeflow-website/pull/2 to be merged, then we can proceed on this one I think, thanks @isinyaaa

**Review by tarilabs — COMMENTED** [review]
https://github.com/kubeflow/website/pull/3801#issuecomment-2227812630

/lgtm

**Comment by rareddy** [comment]
"get_model_version" This method does not sound right to me, IMO this should have been "get_versioned_model"  or "get_model_by_versison", this can be another PR but wanted to mention.

Are snake "_" style APIs typical in Python APIs? TBH I do not like them :) This is time to fix any APIs before we officially do a release.

**Comment by tarilabs** [comment]
This definitely the right case (Python is snake case) and is the right naming, since the logical model entity name is "ModelVersion", but thank you for noticing!

**Comment by rareddy** [comment]
ok, with snake style (but do not like it).  IMO high-level APIs need to be descriptive not necessarily expose as is the data model in the background. Name closer to user actions.

**Comment by tarilabs** [comment]
👍 

It is the correct action, as that is the Logic Model entity: https://github.com/kubeflow/model-registry/blob/main/docs/logical_model.md#model-version
which is the same concepts for UI mocks.

We are not leaking in this API the fact the actual data behind the scenes is a MLMD context.

**Pull request merged**
