### PR TITLE
#1754 - Only smooth scroll on home page

### PR DESCRIPTION
**Pull request by simmscg**
Added a `smooth-scroll` class to the `html` tag on the home page. All other pages should jump immediately to the anchor.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1755)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview:
https://deploy-preview-1755--competent-brattain-de2d6d.netlify.com/

**Comment by sarahmaddox** [comment]
Hmm, the content-rich scrolling still happens e.g. here: https://deploy-preview-1755--competent-brattain-de2d6d.netlify.com/docs/started/k8s/kfctl-k8s-istio/#access-the-kubeflow-user-interface-ui

Maybe you need to force-commit some more generated CSS files?

**Comment by simmscg** [comment]
Looks like just running a `hugo` from the command line with no extra parameters generated some extra files. This might get us across the line.

**Comment by sarahmaddox** [comment]
Thanks so much for the quick fix!
/lgtm
/approve

**Pull request merged**
