### PR TITLE
Move `IBM` platform under /distributions

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Following the latest discussions on `platforms` and `distributions` starting a PR to move `Kubeflow on IBM`.

cc @joeliedtke @Bobgy @animeshsingh @8bitmp3

### CODE REVIEW

**Comment by 8bitmp3** [comment]
cc @Tomcli

**Comment by Tomcli** [comment]
thanks @8bitmp3 
/lgtm

**Comment by 8bitmp3** [comment]
Thanks @Tomcli 🙏 

📣 Root owners please `/approve` @animeshsingh @Bobgy @joeliedtke 🙏

**Comment by RFMVasconcelos** [comment]
@animeshsingh  could you please review this? I have made a similar request to all the platforms so we get them moved to distributions.

This is merging to master and we can make sure we only point the main website to master once all the platforms have moved, so there is no weird scenario where one of the clouds would be outside and others inside the distributions folder.

/assign @animeshsingh 

cc @Bobgy @joeliedtke

**Comment by Bobgy** [comment]
Note that @RFMVasconcelos is now a new root owner too : )

@Tomcli is your LGTM enough? Shall we wait for @animeshsingh 's confirmation on this PR?

**Comment by Tomcli** [comment]
thanks @RFMVasconcelos 
I talked to @animeshsingh today and it's okay to move here
/lgtm.

**Comment by RFMVasconcelos** [comment]
@Tomcli great news! :tada: 

I think your LGTM did not work with the "."  :)

**Comment by 8bitmp3** [comment]
> Note that @RFMVasconcelos is now a new root owner too : )

@RFMVasconcelos @Bobgy @Tomcli 😃 

image

**Pull request merged**
