### PR TITLE
Fix code snippets for python-based-visualizations docs

### PR DESCRIPTION
**Pull request by ajchili**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1509)

### CODE REVIEW

**Comment by joeliedtke** [comment]
This change is staged at:

https://deploy-preview-1509--competent-brattain-de2d6d.netlify.com/docs/pipelines/sdk/python-based-visualizations/

**Comment by ajchili** [comment]
Currently, the code snippets within the **Known Limitations** section looks like 
image

The code snippets are not properly rendered and should instead be 
image.

**Comment by joeliedtke** [comment]
Thanks for fixing the code sample formatting, @ajchili! 

/lgtm
/approve

**Pull request merged**
