### PR TITLE
<HOLD> Initial commit for Developer Workstation Setup

### PR DESCRIPTION
**Pull request by carmine**
This is in reference to issue #878.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1006)

### CODE REVIEW

**Comment by carmine** [comment]
There are a few steps remaining to fill in, but it is about 85% complete. I wanted to share as a mechanism for initial feedback.

**Comment by carmine** [comment]
@sarahmaddox Please review.

**Comment by sarahmaddox** [comment]
Preview: 
* https://deploy-preview-1006--competent-brattain-de2d6d.netlify.com/docs/developer/
* https://deploy-preview-1006--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-developer/

**Comment by sarahmaddox** [comment]
@carmine @jlewi @abhi-g @pdmack and anyone else interested :)

I'd like to discuss the location of this new guide (" how to set up a dev environment"). The target audience of this doc is developers of and contributors to Kubeflow rather than users of Kubeflow. I'm thinking the developer-focused docs belong in the `kubeflow/kubeflow` repo on GitHub rather than on the website.

Reasons behind my thinking:

* **Audience:** It can be confusing to users of Kubeflow when they land on a developer-focused doc. They may arrive on that doc via an Internet search, and not realise that the information is directed at developers/contributors rather than users. Particularly with a product like Kubeflow, the line can be quite narrow. People may think they need to build Kf from source in order to use it.

* **Scattering of information:** We already have a host of dev-focused guides on GitHub. Developers will need to hop around to find the info they need. Examples:

  * [Repository setup](https://github.com/kubeflow/community/blob/master/repository-setup.md)
  * [Testing](https://github.com/kubeflow/kubeflow/blob/master/testing/README.md)
  * [Releasing](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md)
  * [tf-operator developer guide](https://github.com/kubeflow/tf-operator/blob/master/developer_guide.md)
  * [README with links to various dashboards](https://github.com/kubeflow/kubeflow/blob/master/README.md) (Could do with merging into a broader-scope guide)
  * [Code review info](https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md) (Could do with merging into a broader-scope guide)
  * And so on.

* **Maintenance:** Developers are more likely to update the docs on GitHub than on the website.

* **Tech writing standards:** Arguably, the bar is lower for GitHub-based guides than the official Kubeflow website, particularly as we move towards v1.0.

My recommendation is to move this guide to GitHub. What do folks think?

**Comment by abhi-g** [comment]
I agree that this belongs with other developer support documentation on
GitHub.

**Comment by carmine** [comment]
I'll close this pull request and propose it under kubeflow/kubeflow. I do think it'll be helpful to promote it on the website though - maybe under the reference section?

**Comment by sarahmaddox** [comment]
Hallo @carmine 

Answering this question:

> I do think it'll be helpful to promote it on the website though - maybe under the reference section?

It'd be great to add a link on the following page:

https://www.kubeflow.org/docs/about/contributing/

to your new guide when it's ready.

**Pull request closed without merging**
