### PR TITLE
Fix working directory path for make commands

### PR DESCRIPTION
**Pull request by plang85**
The makefile is in `${MGMT_DIR}/management`

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
/assign @joeliedtke

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you again @plang85 ! 

@Bobgy @zijianjoy same here

**Comment by zijianjoy** [comment]
/approve

Thank you @plang85 for the fix! You might want to resolve the conflict before merging.

And thanks @RFMVasconcelos for directing the PR to us.

**Comment by Bobgy** [comment]
/hold
I think there are some complexities here, behavior is different between MGMT_DIR ends with management or not.

If MGMT_DIR=management, the folder itself will be used, if MGMT_DIR=mgmt, then mgmt/management folder will be created.

That's what I recall, I think we need to verify that

**Comment by zijianjoy** [comment]
@Bobgy That is a good catch! I misread the PR change and the latest document here, the latest `MGMT_DIR` definition is documented in https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/#configure-environment-variables, so it ends with `management`. Moreover, we use the actual value instead of variable name for directory navigation in the latest instruction https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/#fetch-kubeflowgcp-blueprints-package.

@plang85 Would you like to confirm if the latest document is accurate? If so, please close this PR. Thanks again for creating PR!

**Review by Arhell — COMMENTED** [review]
There are conflicts

**Pull request closed without merging**
