### PR TITLE
Apply Docs Restructure to `v1.2-branch` = update `v1.2-branch` to current `master`

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
This acts on #2606.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@RFMVasconcelos why why hold? Looks good!
/lgtm

**Comment by thesuperzapper** [comment]
@joeliedtke or @Bobgy we need you to /approve

**Comment by thesuperzapper** [comment]
@RFMVasconcelos can you fix the merge conflict?

**Comment by RFMVasconcelos** [comment]
@thesuperzapper hold simply as I was testing ways to solve that conflict, maybe not the best process. Had to jump on something else, but now back on this

**Comment by RFMVasconcelos** [comment]
I can't figure out this conflict here, I have made an alternative PR here >> #2612

Let's please use that one. 

/close

**Pull request closed without merging**
