### PR TITLE
Add 1.5 to version dropdown.

### LINKED ISSUE #3133: Add an entry for the 1.5 release to the docs version dropdown
See this PR for an example of what needs to happen:
https://github.com/kubeflow/website/pull/3027

### PR DESCRIPTION
**Pull request by shannonbradshaw**
Fixes #3133

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
@annajung @kimwnasptd @jbottum

**Review by annajung — APPROVED** [review]
/lgtm

As a side note, I think it would be helpful to think about removing past versions every time there is a new version added. Maybe keep the previous 5 or 6 versions (from v1.0 - v1.5) and remove the rest. Are there users who actually access v0.2 docs? We can discuss this in the retro as well.

**Comment by jbottum** [comment]
@shannonbradshaw FYI, I just tried this and got this error, 

This site can’t be reachedCheck if there is a typo in v1-5-branch.kubeflow.org.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by shannonbradshaw** [comment]
Still need to cut the branch. Waiting on one more PR.

**Pull request merged**
