### PR TITLE
Kubeflow multinode cluster installation

### PR DESCRIPTION
**Pull request by mastrogiovanni**
I described in this use case how to setup in on-prem multi-node Kubernetes cluster Dynamic Provisioning using NFS volumes in order to allow KubeFlow installation and bind existing Persistent Volume Claims without pain.

I added also a *Limitations* section for this solution and a *Resources* section to get information about Kubernetes resources used.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/896)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Thanks @mastrogiovanni ! 

Please would you add a link to the issue that this PR is addressing. (Also, is it related to issue https://github.com/kubeflow/website/issues/230 ?) If there isn't a fitting issue yet, please create one and I'll add it to the doc sprint Kanban board.

/ok-to-test
/assign @alecglassford

**Comment by alecglassford** [comment]
I believe this should be closed and I'll review #897 instead.

**Comment by sarahmaddox** [comment]
Thanks @mastrogiovanni and @alecglassford I'll close this one, as it's replaced by PR https://github.com/kubeflow/website/pull/897

/close

**Pull request closed without merging**
