### PR TITLE
Updated K3ai version and re-freshed docs

### PR DESCRIPTION
**Pull request by alefesta**
K3ai is now v1 and has been migrated to the k3ai-project ..So I've updated the docs accordingly.
Also, K3ai does support the full components of Kubeflow so I think I'll open up another PR to add other capabilities of K3ai to the docs.

### CODE REVIEW

**Comment by alefesta** [comment]
also please notice that I'm the middle of migrating my old account @alfsuse  to this one @alefesta  so I'm the original author of this doc.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by alfsuse — APPROVED** [review]

**Pull request closed without merging**
