### PR TITLE
 Frontpage overhaul. Follow up from PR #924.

### PR DESCRIPTION
**Pull request by MaanavD**
Apologies for recreating the PR. Issues have been fixed and page has been reviewed. Continuation of #924 .

Co-authored-by: Mohona Ahmed <t-moahme@microsoft.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/951)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-951--competent-brattain-de2d6d.netlify.com/

(In future PRs, it's useful if you can link to the preview of your page(s) to save the PR reviewers some time.)

**Comment by sarahmaddox** [comment]
The TF training card is still linking to TF serving.

**Comment by sarahmaddox** [comment]
This looks great - just the one thing to fix then it's LGTM.

**Comment by MaanavD** [comment]
https://deploy-preview-951--competent-brattain-de2d6d.netlify.com/

We should be ready for the roll out!

**Comment by mohona17** [comment]
I consent.

**Comment by sarahmaddox** [comment]
Thanks @mohona17 for verifying your CLA consent. I'm happy to merge this PR, as we do have a CLA for both committers on file and I've verified their contributions by chatting to @mohona17 and @MaanavD in person at the Kubeflow Doc Sprint.

**Pull request merged**
