### PR TITLE
Create a Fairing section for the documentation

### LINKED ISSUE #590: Create a Kubeflow Fairing section
Create a section for Kubeflow Fairing parallel to Pipelines and Kubeflow on GCP

### PR DESCRIPTION
**Pull request by abhi-g**
fixes #590

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/599)

### CODE REVIEW

**Comment by abhi-g** [comment]
Preview https://deploy-preview-599--competent-brattain-de2d6d.netlify.com/docs/fairing/

**Comment by sarahmaddox** [comment]
Thanks @abhi-g! I think we should hold off on adding the section until we have some content to include. Readers may be surprised and even frustrated to find no content, especially as there's no indication of what Fairing is.

FYI I have a meeting later today with @joeliedtke to discuss the Fairing docs. He's the tech writer working with the Fairing team.

I'll apply a hold, to stop this PR from being merged without direct intention. Please do cancel the hold if you disagree. :)

/hold

**Comment by abhi-g** [comment]
Sounds reasonable. I created a bunch of issues in the website repo to add
various documentation for Fairing.

**Comment by sarahmaddox** [comment]
We now have a candidate page that will appear in this section. See PR https://github.com/kubeflow/website/pull/603

I'll LGTM this PR and remove the hold, so that you can approve and merge as soon as the above PR is approved. :)

**Comment by abhi-g** [comment]
Thanks.

**Pull request merged**
