### PR TITLE
Simplification of installation instructions

### PR DESCRIPTION
**Pull request by edu-ap**
Clarification of message.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1579)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/ok-to-test
/lgtm
/approve

Simplification is good - thanks!

**Comment by edu-ap** [comment]
Thank you @sarahmaddox 
Do you know how long this will take to appear on the live page?
Many thanks!
Eduardo

**Comment by sarahmaddox** [comment]
Hallo @edu-ap :) the updates should be visible on https://master.kubeflow.org

Explanation:
www.kubeflow.org is currently pointing to the archived v0.7 docs. Updates after PR merge will appear on master.kubeflow.org. Close to launch of v1.0, www.kubeflow.org will again be pointed to master.

**Pull request merged**
