### PR TITLE
KUBEFLOW-3267 Link from the getting-started guide to the IBM Cloud Pr…

### PR DESCRIPTION
**Pull request by rawkintrevo**
Hey there, this is my first PR on this repo so please be kind.

I'm working on this issue[1] 

Some one else took it- but it was literally like a 42 second fix and they were assigned 10 days ago... so not trying to be rude, but just want to go through any ICLA and other paper work to get the swing of this (and don't be afraid to sharp shoot me on etiquette, I've done some rounds in Apache but I get communities are different and I'm trying to learn. )

Thanks in advance!

[1] https://github.com/kubeflow/kubeflow/issues/3267

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/748)

### CODE REVIEW

**Comment by rawkintrevo** [comment]
ICLA signed

**Comment by sarahmaddox** [comment]
/unassign @hongye-sun 
/assign
/ok-to-test
/lgtm
/approve

Thanks!

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/kubeflow/issues/3267

**Pull request merged**
