### PR TITLE
Fixed broken links in Notebooks

### LINKED ISSUE #3810: Fix broken links in Notebooks
[Now that we have Checklinks enabled in Netlify](https://github.com/kubeflow/website/pull/3763), we can fix the existing broken links we have on our TODO list.

1. Remove Notebooks links from [Checklinks TODO list](https://github.com/kubeflow/website/blob/e1eb76b4facca9562445a63c14bbe30b7003b5c3/netlify.toml#L12).
2. Fix links [reported in Netlify deployment log](https://github.com/kubeflow/website/assets/11776454/01cf5cf0-3d8a-49dd-b32e-89506c4a71d9).

https://github.com/kubeflow/website/pull/3807 can be used as a reference.

cc @StefanoFioravanzo @elikatsis @kimwnasptd @thesuperzapper

### PR DESCRIPTION
**Pull request by varodrig**
fixes #3810

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

@varodrig can you please just do the following?

- Update the title of the PR to reflect the actual changes. Something like "Fixed broken links in Notebooks".
- Edit the [description](https://github.com/kubeflow/website/pull/3878#issue-2544124050) to [automatically link your PR to the issue it resolves](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by varodrig** [comment]
> /lgtm
> 
> @varodrig can you please just do the following?
> 
> * Update the title of the PR to reflect the actual changes. Something like "Fixed broken links in Notebooks".
> * Edit the [description](https://github.com/kubeflow/website/pull/3878#issue-2544124050) to [automatically link your PR to the issue it resolves](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Done. thank you for reviewing.

**Comment by hbelmiro** [comment]
@thesuperzapper can you please take a look?

**Comment by thesuperzapper** [comment]
@hbelmiro @varodrig looks fine to me, but I can't approve it because we need a root approver to be able to edit the Netlify configs.

/lgtm

**Comment by thesuperzapper** [comment]
@andreyvelich can you please approve this fix on the website, we need a root approver.

**Pull request merged**
