### PR TITLE
Updated Azure docs for kfctl v0.7

### PR DESCRIPTION
**Pull request by sarahmaddox**
This PR updates the Azure docs to use the new kfctl semantics in v0.7. Only the installation doc needs updating.

The PR addresses some of the updates for https://github.com/kubeflow/website/issues/1226. Further PRs will update other docs.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1245)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @gopitk 
@gopitk Please would you review these updates to the Kubeflow Azure deployment guide?

I'll merge the update when we brand the website to Kubeflow v0.7.
/hold

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1245--competent-brattain-de2d6d.netlify.com/docs/azure/deploy/install-kubeflow/

**Comment by sarahmaddox** [comment]
/assign @gopitk 

@gopitk Please would you take a look at this PR, and LGTM it if you're happy with the updates. When we're ready, I'd like to rebrand the docs to Kubeflow v0.7 and merge this PR as well as my related PRs for the other deployment/setup guides.

**Comment by sarahmaddox** [comment]
Thanks @gopitk! I'll find someone else to do the LGTM based on your approval.
/unassign

**Comment by sarahmaddox** [comment]
@jlewi This PR is ready to go, but I'll hold it until the on-prem PR is merged, to avoid problems with the shared `kfctl_k8s_istio.0.7.0.yaml` config. If you're happy to LGTM based on previous approval from @gopitk then I'll remove the hold when applicable.

**Comment by jlewi** [comment]
Previous LGTM satisfies me
/lgtm
/approve

Feel free to submit when you're ready. If you need me to re-LGTM just ping me and I'll take care of it immediately

**Comment by sarahmaddox** [comment]
The PR that updates the config file is now merged, so we can merge this PR too.

/hold cancel

**Pull request merged**
