### PR TITLE
Update authentication.md

### PR DESCRIPTION
**Pull request by vabshere**
add missing conjunction

### CODE REVIEW

**Comment by vabshere** [comment]
@googlebot I signed it!

**Review by Arhell — COMMENTED** [review]
/assign @RFMVasconcelos
@kubeflow/aws

**Review by AlexandreBrown — APPROVED** [review]

**Review by surajkota — APPROVED** [review]
/approve
/lgtm

**Comment by vabshere** [comment]
Hi @RFMVasconcelos
Can you please give this PR a review

**Comment by surajkota** [comment]
Thank you for the contribution. Closing this in favour of new docs at https://github.com/awslabs/kubeflow-manifests/tree/v1.3-branch/distributions/aws/examples/cognito

/close

**Pull request closed without merging**
