### PR TITLE
update mxjob docs

### PR DESCRIPTION
**Pull request by EDGsheryl**
Add a useful way to install MXNet-Operator.
The documentation is from https://github.com/kubeflow/mxnet-operator/blob/master/README.md

Besides, I add code below to distinguish repos for users.
```
# git clone https://github.com/kubeflow/mxnet-operator.git
# cd mxnet-operator
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1529)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Thanks for this update @EDGsheryl. We're looking to remove the ksonnet instructions from the MXNet doc entirely. See issue https://github.com/kubeflow/website/issues/1504, which mentions a specific YAML file. Is this update something you can incorporate into your PR?

/cc @jlewi

**Comment by EDGsheryl** [comment]
@sarahmaddox Thank you for advice. 

I noticed that https://www.kubeflow.org/docs/components/training/mpi/ have used kustomize. So I supposed that I should keep same to MPI's.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1529--competent-brattain-de2d6d.netlify.com/docs/components/training/mxnet/

**Comment by sarahmaddox** [comment]
/assign @jlewi 

@jlewi Do you have a suggestion for someone who can review this doc for technical correctness and completeness?

/cc @suleisl2000

**Comment by jlewi** [comment]
/assign @suleisl2000 
/assign @wackxu 

@suleisl2000 and @wackxu are listed in the OWNERs file for mxnet so it would be good to get one of them to review this.

**Comment by sarahmaddox** [comment]
Thanks @suleisl2000 and @EDGsheryl 

/lgtm
/approve

**Pull request merged**
