### PR TITLE
WtD fixit: Readability improvements for Install Kubeflow

### PR DESCRIPTION
**Pull request by shimdude**
Fix https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1392)

### CODE REVIEW

**Comment by shimdude** [comment]
Fixes issue https://github.com/kubeflow/website/pull/1392

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/1360

**Pull request merged**
