### PR TITLE
Added a GSoC page

### PR DESCRIPTION
**Pull request by sarahmaddox**
Added a page with info for GSoC students and mentors. Linked to the page from the Community page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1806)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview:
* https://deploy-preview-1806--competent-brattain-de2d6d.netlify.com/docs/about/gsoc/
* https://deploy-preview-1806--competent-brattain-de2d6d.netlify.com/docs/about/community/

**Comment by sarahmaddox** [comment]
/assign @jlewi 
/cc @theadactyl 

**Note:** This PR is ready for discussion. Is there anything I should add, and does the content fit with your thinking of our GSoC plans? ( I'm currently investigating the mailing lists/groups that we're going to use. This PR is not ready for merging until those are finalized.)

**Comment by sarahmaddox** [comment]
@jlewi This PR is now ready for review. 

(I plan to pretty it up a little by adding the GSoC logo, but I'm running out of time this morning and I want to get this info out there ASAP.)

**Comment by jlewi** [comment]
Thanks @sarahmaddox

**Pull request merged**
