### PR TITLE
Refactor getting started

### LINKED ISSUE #2590: Refactor the "Getting Started" "Installing Kubeflow" page
As we have been moving all distribution-specific docs out of "Getting Started" with PRs like #2576, #2577, #2569, #2492, we should now clean up the first place people look when trying to install Kubeflow.

As proposed by @cvenets [here](https://github.com/kubeflow/website/issues/2565#issuecomment-816296338) we should clearly indicate the two "paths" for installing Kubeflow:
1. __Roll your own__ -- using the `kubeflow/manifests` yourself, with no support
2. __Supported Distribution__ -- using a vendor or community supported install process

I think this leaves us with the following sections in "Getting Started" / "Installing Kubeflow":

```md
## Overview
* discussion about Kubeflow being a "Kubernetes" app, with multiple components which can be mix-and-matched
* discussion about the two "paths" as described above, "Roll your own" and "Distribution"
* discussion about how Kubeflow is versioned, e.g. what 1.3, 1.4, even mean.

## Path 1: Roll Your Own
* Either take the content in the README of `kubeflow/manifests`, or just link to it
* https://github.com/kubeflow/manifests#kubeflow-manifests

## Path 2: Supported Distribution 

### Vendor Supported
a TABLE which lists the currently maintained VENDOR-SUPPORTED distributions, and links to their docs

CONTENT (Alphabetical):
* `Kubeflow on AWS`
* `Kubeflow on Azure`
* `Kubeflow on GCP`
* `Kubeflow on IBM Cloud`
* `Kubeflow on Openshift` (Combine: "Kubeflow Operator" and "Kubeflow on Openshift" page)
* `Kubeflow on MicroK8s` (Rename from "MicroK8s Kubeflow add-on" page)
* `Kubeflow with Charmed Operators` (Rename from "Kubeflow Charmed Operators" page)
* `Kubeflow with MiniKF`

### Community Supported
a TABLE which lists the currently maintained COMMUNITY-SUPPORTED distributions, and links to their docs

CONTENT (Alphabetical):
* `Kubeflow with ArgoCD` (New page)
* `Kubeflow with kfctl` (Rename from "kfctl" page)

## Next Steps
* links to important component docs "Pipelines", "Notebooks", etc.
```

### PR DESCRIPTION
**Pull request by shannonbradshaw**
This fixes #2590 I'm expecting to make small fixes depending on reviews.

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
cc: @RFMVasconcelos @cvenets

**Comment by shannonbradshaw** [comment]
I believe we're done making updates to this PR. It's ready for review.

**Comment by shannonbradshaw** [comment]
@joeliedtke @RFMVasconcelos I believe this PR fully addresses #2590. We have finished make changes and it is ready for review.

**Comment by Bobgy** [comment]
@thesuperzapper Can I confirm, is this PR competing with https://github.com/kubeflow/website/pull/2611?
What are the differences?

**Comment by thesuperzapper** [comment]
I am not sure what this pr was for..

Given the contentious nature of such a visible page, we are sowly working though the change on PR #2611

**Comment by shannonbradshaw** [comment]
@thesuperzapper I'm not trying to compete here. I'm just trying to get #2590 closed. #2611 wasn't moving so I pushed a PR that as best I could tell included only elements of the discussion around #2590 around which there appeared to be agreement:

**Comment by RFMVasconcelos** [comment]
@shannonbradshaw thank you for starting this. Since there is ongoing work on #2611 with the same scope, I have ported some of your changes to there to accelerate the merge. 

I propose we wrap it up in #2611

**Comment by thesuperzapper** [comment]
closing in preference of https://github.com/kubeflow/website/pull/2611

/close

**Pull request closed without merging**
