### PR TITLE
Add 1.6.1 info

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

- Add 1.6.1 release info

cc @kubeflow/release-team

### CODE REVIEW

**Comment by annajung** [comment]
deploy preview: https://deploy-preview-3373--competent-brattain-de2d6d.netlify.app/docs/releases/kubeflow-1.6/#161

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by annajung** [comment]
Hi @zijianjoy, could you take a look?

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you for the 1.6.1 update!

**Pull request merged**
