### PR TITLE
Cherrypick of "Adding docs for Azure MySQL (#2304)"

### PR DESCRIPTION
**Pull request by berndverst**
Cherrypick of "Adding docs for Azure MySQL (#2304)"

* Adding docs for Azure MySQL

* Edit kustomization.yaml to use relative path in the example

* Linting the code

### CODE REVIEW

**Comment by berndverst** [comment]
@yilun-msft can you approve as the original author?

**Comment by yilun-msft** [comment]
@googlebot I consent.

**Pull request merged**
