### PR TITLE
Updated AWS Troubleshooting guide to add tag for public subnets

### PR DESCRIPTION
**Pull request by mattmcclean**
Added details on troubleshooting steps when there are issues with the ALB ingress controller. The public subnets should have the correct tag **Name:** ```kubernetes.io/role/elb``` and **Value:** ```1```.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1470)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @Jeffwan 

@Jeffwan FYI :)

**Comment by sarahmaddox** [comment]
@mattcallanan Please would you sign the CLA then add a comment to this PR as prompted by the googlebot in a previous comment. When you add the comment with the suggested wording, the bot will verify the CLA again and reset the validation check on the PR.

**Comment by Jeffwan** [comment]
Just come back from vacation. 
/lgtm

**Comment by abhi-g** [comment]
@mattmcclean please sign the CLA for the PR to be merged.

**Comment by mattmcclean** [comment]
@googlebot I signed it!

**Pull request merged**
