### PR TITLE
Accessibility add link name

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubeflow/website/issues/3142

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
@Arhell for the record, can you provide a bit more detail about the motivation for this PR?

**Comment by Arhell** [comment]
> @Arhell for the record, can you provide a bit more detail about the motivation for this PR?

@shannonbradshaw
As noted here https://github.com/kubeflow/website/issues/3142 This edit adds more responsiveness for site users

**Pull request closed without merging**
