### PR TITLE
docs(gcp): unify terminology for CNRM as Config Connector

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/kubeflow/gcp-blueprints/issues/175

/assign @joeliedtke

### CODE REVIEW

**Comment by joeliedtke** [comment]
Preview:
https://deploy-preview-2396--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/delete-cli/
https://deploy-preview-2396--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/deploy-cli/
https://deploy-preview-2396--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/reasons/
https://deploy-preview-2396--competent-brattain-de2d6d.netlify.app/docs/gke/private-clusters/

**Comment by joeliedtke** [comment]
Are the resources for Config Connector, or are these resources that are managed by Config Connector?

**Comment by Bobgy** [comment]
@joeliedtke they are managed by config connector, also the resource spec are defined by config connector

**Pull request merged**
