### PR TITLE
Move Kubeflow on OpenShift installation docs to legacy distribution

### PR DESCRIPTION
**Pull request by LaVLaS**
The PR removes the documentation for the Kubeflow on OpenShift as distribution that will be tested for compatibility prior to each KF release.  The Red Hat maintainers for Kubeflow on OpenShift are re-prioritizing KF support to focus on providing OpenShift compatibility for specific KF components running on OpenShift.

Addresses  #3074

### CODE REVIEW

**Comment by LaVLaS** [comment]
@VaishnaviHire PTAL
/cc @nakfour @crobby

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by VaishnaviHire** [comment]
LGTM

**Review by nakfour — APPROVED** [review]

**Review by crobby — APPROVED** [review]

**Comment by thesuperzapper** [comment]
@zijianjoy can you please approve this, so we don't confuse users by having this deprecated distribution on the "installing kubeflow" page?

**Pull request merged**
