### PR TITLE
update hugo version

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubeflow/website/issues/2797
/assign @Bobgy

### CODE REVIEW

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Bobgy** [comment]
Thank you for the update!
Is this ready for review? (It is in draft)

**Comment by Arhell** [comment]
/unhold
cc @Bobgy update hugo to last version

**Pull request merged**
