### PR TITLE
add QBO and "raw manifests" guides table

### PR DESCRIPTION
**Pull request by thesuperzapper**
Based on my comments in https://github.com/kubeflow/website/pull/3672#issuecomment-2008558070, I think there is a need to distinguish "guides" from distributions. 

To help @alexeadem get a presence on the website, I think QBO can be the first such guide.

All other existing distributions have forked the `kubeflow/manifests` repo, and made at least some platform-specific changes. We can discuss if any of the existing "packaged distributions" should be moved to the "guides for specific platforms" table in future PRs.

## Changes

- Adds a "guides for specific platforms" section under "raw kubeflow manifests"
- Adds QBO to the "guides for specific platforms" table
- Moves the "packaged distributions note" to the bottom of the "packaged distributions" section:
    - _this is an unrelated change, but I think it makes the page more readable, as it currently interrupts the reader a lot_

## Screenshot 

Installing-Kubeflow-Kubeflow

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@andreyvelich @james-jwu @jbottum based on my comments in https://github.com/kubeflow/website/pull/3672#issuecomment-2008558070, I think it makes more sense to introduce a "platform-specific guides" section under "raw kubeflow manifests" so we can include things which really aren't "packaged distributions" on the website.

The first one can be the QBO guide.

See the screenshot above.

**Review by hbelmiro — COMMENTED** [review]
/lgtm
/hold for review

@andreyvelich @james-jwu @jbottum can you PTAL?

**Comment by rimolive** [comment]
There are merge conflicts. @thesuperzapper would you mind fix these conflicts?

**Comment by thesuperzapper** [comment]
@rimolive @hbelmiro this PR is stale, we ended up just adding QBO to the distributions list in https://github.com/kubeflow/website/pull/3672.

**Pull request closed without merging**
