### PR TITLE
Cards on front page fail WCAG AA, Open Sans not loading all weights (#1675)

### PR DESCRIPTION
**Pull request by simmscg**
- Fixed Open Sans not loading its weights correctly (also added 600 weight, but left out 800).
- Lightened the card font color.
- Darkened the card background color.
- Moved the css added in between style tags in `_index.html` into `_variables_project.sass`.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1676)

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @simmscg , I don't see any text on the cards:
https://deploy-preview-1676--competent-brattain-de2d6d.netlify.com/

**Comment by sarahmaddox** [comment]
Thanks @simmscg! I think the CSS hasn't all come across properly. The images in the cards are a little squidged, and the text in the bottom of each card is invisible.

Preview: https://deploy-preview-1676--competent-brattain-de2d6d.netlify.com/

**Comment by simmscg** [comment]
Oh how odd. I'll see if I can figure out what's going on.

**Comment by simmscg** [comment]
Looks like those Hugo-generated assets are important after all @sarahmaddox, things should look good now.

**Comment by simmscg** [comment]
A few more card tweaks:

- Removed unneeded class from links inside cards.
- Fixed one broken, and one incorrect link.
- Added `rel="noopener"` to links inside cards that have target set to `_blank` (questionable if target should be set to that.

**Comment by kbhawkey** [comment]
@simmscg Did you intend for the card background to match the dark blue color?

**Comment by simmscg** [comment]
> @simmscg Did you intend for the card background to match the dark blue color?

Yep! Selected $dark for improved readability, with the intention of passing WCAG AA. The original $primary background color made things hard to read.

Can always revert the color if desired.

**Comment by sarahmaddox** [comment]
Very nice. We've run it past a couple of people here in the doc sprint room too.
/lgtm
/approve

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/1675

**Pull request merged**
