### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by bdoohan-goog**
current link is dead. I Propose adding this link for getting Feast installed on Kubernetes: https://docs.feast.dev/v/v0.6-branch/getting-started/deploying-feast/kubernetes

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
@bdoohan-goog thank you for this PR! Can you please sign the CLA?

**Comment by bdoohan-goog** [comment]
> @bdoohan-goog thank you for this PR! Can you please sign the CLA?

Hi Rui - I am a Google employee and am unable to sign a CLA unfortunately. Not sure what to do in this instance.

Brendan

**Comment by RFMVasconcelos** [comment]
That's odd. cc @Bobgy :)

**Comment by bdoohan-goog** [comment]
> That's odd. cc @Bobgy :)

Let me close and retry. Brendan

**Pull request closed without merging**
