### PR TITLE
Change "What is Kubeflow" in v0.2 branch from master branch

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/website/issues/268.
Copy "What is Kubeflow" information from master to v0.2-branch.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/288)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
I've seen the comments in [PR 285](https://github.com/kubeflow/website/pull/285), but I think we need more than the high-level description that is currently in the master branch. I added the words that are currently in the v0.2 branch to answer the question, "What is Kubeflow". The high-level description (quoted below) is a statement of vision and goals, but does not give any technical information. I've heard many people ask "what is Kubeflow exactly", and some have said the docs don't make it clear what it actually is.

Here's the text we currently give in master, and which this PR is putting into v0.2 as well:

>>> Originating at Google, Kubeflow is an open source project dedicated to making deployments of machine learning (ML) workflows on Kubernetes simple, portable and scalable. Our goal is not to recreate other services, but to provide a straightforward way to deploy best-of-breed open-source systems for ML to diverse infrastructures. Anywhere you are running Kubernetes, you should be able to run Kubeflow.

As a reader, I'm left wondering: "Yes, but what **is** it?"

**Comment by andreyvelich** [comment]
@sarahmaddox @richardsliu I change it in v0.2-branch, like you said.

**Comment by andreyvelich** [comment]
@sarahmaddox Yes, I will make PR for master on Monday.

**Comment by sarahmaddox** [comment]
Thanks!

/approve

**Pull request merged**
