### PR TITLE
Add missing import to containerized pipelines example

### PR DESCRIPTION
**Pull request by tom1299**
The import for `compiler` was missing.

### CODE REVIEW

**Review by hbelmiro — CHANGES_REQUESTED** [review]
Thank you for this contribution @tom1299.
Can you please [sign off your commit](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)?

**Comment by varodrig** [comment]
@hbelmiro  can you approve?

**Comment by hbelmiro** [comment]
@tom1299 can you please rebase?

**Comment by tom1299** [comment]
@hbelmiro Looking at the merge conflicts it seems that the changes from my PR are already part of https://github.com/kubeflow/website/commit/d9ae92b1c43be3dbb332bc106617a4e231011273 So it doesn't really make any sense to merge this PR. Closing it.

**Pull request closed without merging**
