### PR TITLE
Updating kubeflow kustomize requirements

### PR DESCRIPTION
**Pull request by richardsliu**
Fixes https://github.com/kubeflow/website/issues/870

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/882)

### CODE REVIEW

**Comment by richardsliu** [comment]
@sarahmaddox Looks like this PR is merging into the wrong branch, please ignore.

**Comment by sarahmaddox** [comment]
@richardsliu For some reason the presubmit is skipped on the PR, and the Netlify preview isn't built. Do you have any idea why?

**Comment by sarahmaddox** [comment]
Ah I see :)

**Pull request closed without merging**
