### PR TITLE
Add demo of using custom visualization with taxi pipeline

### PR DESCRIPTION
**Pull request by jingzhang36**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1533)

### CODE REVIEW

**Comment by jingzhang36** [comment]
Preview is at https://deploy-preview-1533--competent-brattain-de2d6d.netlify.com/docs/pipelines/sdk/python-based-visualizations/. Look for "a demo".

**Comment by hongye-sun** [comment]
/lgtm
/approve

Sorry for the delay. I missed the notification somehow.

**Pull request merged**
