### PR TITLE
Add 1.5.1 release info

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

Add 1.5.1 release info

cc @kubeflow/release-team @jbottum

### CODE REVIEW

**Comment by annajung** [comment]
page preview: https://deploy-preview-3298--competent-brattain-de2d6d.netlify.app/docs/releases/kubeflow-1.5/

**Comment by jbottum** [comment]
@annajung thanks for this PR, Question 1 - Does this replace 1.5.0 ?   Question 2 - Are there two training operators (I thought every framework used the Universal training operator.

**Comment by annajung** [comment]
Hi @jbottum, it does not replace 1.5.0. they're both just on the same page
- 1.5.0: https://deploy-preview-3298--competent-brattain-de2d6d.netlify.app/docs/releases/kubeflow-1.5/#150
- 1.5.1: https://deploy-preview-3298--competent-brattain-de2d6d.netlify.app/docs/releases/kubeflow-1.5/#151

> Question 2 - Are there two training operators (I thought every framework used the Universal training operator.

Are you asking why the release table under training working group lists both MPI Operator and Training Operator? If so, this was just a copy and paste from the 1.5.0 table (the only change was the pipeline version). We can combine the two operators  if needed

**Comment by jbottum** [comment]
@johnugeorge hey Johnu - Should we be listing the MPI and Training operator separately ?   I thought they were both in the Universal Training Operator.   Josh

**Comment by johnugeorge** [comment]
Sorry for late reply. MPI operator v1 is part of Training operator itself.  https://github.com/kubeflow/mpi-operator contains v2 version which needs to be separately installed by the user if he wants to.

**Comment by jbottum** [comment]
@thesuperzapper did you fix the issue, are we good to post

**Comment by thesuperzapper** [comment]
@jbottum because I can not write to @annajung 's fork, I have made PR https://github.com/kubeflow/website/pull/3311 to include the correct info about 1.5.1. 

It also makes some nice additions to previous releases by collecting "media" into its own section of the table, and fixing broken ROADMAP links.

---

I am going to close this PR in preference of https://github.com/kubeflow/website/pull/3311

/close

**Pull request closed without merging**
