### PR TITLE
Added a downloads page for kfctl

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/598

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/607)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-607--competent-brattain-de2d6d.netlify.com/docs/reference/downloads/

**Comment by abhi-g** [comment]
@gabrielwen Is this correct, that kfctl binary only works for GCP. I have seen some commands documenting that it can be used to deploy to minikube or an existing K8s cluster.

**Comment by gabrielwen** [comment]
IIUC minikube/k8s support is not finished.  @kkasravi is this correct?

**Comment by sarahmaddox** [comment]
See also @Jeffwan 's comment on this issue: https://github.com/kubeflow/kubeflow/issues/2954#issuecomment-481490880

@abhi-g Should we merge this PR and update it when support for other platforms is available?

**Comment by abhi-g** [comment]
Sounds good.
/lgtm
/approve

**Pull request merged**
