### PR TITLE
Update install-kubeflow.md

### PR DESCRIPTION
**Pull request by ricoms**
rerally small fix, the solution on #2039 (issue #2039) worked so I'm just updating the other URL for a nice presentation.

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/lgtm

Thanks for contributions @ricoms

**Comment by joeliedtke** [comment]
Preview: https://deploy-preview-2051--competent-brattain-de2d6d.netlify.app/docs/aws/deploy/install-kubeflow/

**Pull request merged**
