### PR TITLE
Make component development doc more language agnostic

### PR DESCRIPTION
**Pull request by lqdev**
Updated some phrases in *component-development.md* document to make it more clear pipeline components are language agnostic. 

Based on kubeflow/pipelines#4599 discussion

[Preview Link](https://deploy-preview-2294--competent-brattain-de2d6d.netlify.app/docs/pipelines/sdk/component-development/)

### CODE REVIEW

**Comment by lqdev** [comment]
Ready for review when you get a chance. Thanks!

/assign @Ark-kun

**Comment by alfsuse** [comment]
Hi @lqdev thanks for the submission! Would you mind to sign the cla/google in the meantime? Seems like is not right now. :)

**Comment by lqdev** [comment]
Hi @alfsuse,

I did that. Though after submitting the PR. Not sure if PRs retroactively pick up that information. Is there something I should to retrigger that check?

image

**Comment by 8bitmp3** [comment]
@lqdev thank you for this. You should follow the instructions from the `google-cla` bot - https://github.com/kubeflow/website/pull/2294#issuecomment-712563187 - to sign the Google-specific CLA. Make sure you use the same 📧 address.

---

/assign @Bobgy @IronPan @neuromage @Ark-kun @numerology

(assigned the Pipelines approvers)

**Comment by lqdev** [comment]
@googlebot I signed it!

**Comment by lqdev** [comment]
Thanks @8bitmp3 . My mistake. I had signed the LFAI, not the Google CLA.

**Review by alfsuse — APPROVED** [review]

**Comment by numerology** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
