### PR TITLE
Clean up "Frameworks for training" + rename to "Training Operators"

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Following the last community meeting discussion, I removed "Outdated banners" from Tensorflow and Pytorch docs, removed Chainer, and sorted by importance (IMO). 

@andreyvelich @kimwnasptd WDYT? 

cc @Bobgy @thesuperzapper

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
This tackles issue #2516

**Comment by kimwnasptd** [comment]
LGTM, but @andreyvelich will be the one to make the call here.

Thanks for the PR @RFMVasconcelos!

**Review by andreyvelich — COMMENTED** [review]
Thanks a lot for this update @RFMVasconcelos!
Should we also remove Out of Date from: 
MPI Operator: https://deploy-preview-2584--competent-brattain-de2d6d.netlify.app/docs/components/training/mpi/
MXnet Operator: https://deploy-preview-2584--competent-brattain-de2d6d.netlify.app/docs/components/training/mxnet/

**Review by terrytangyuan — APPROVED** [review]
LGTM. I can help update some of the pages for operators this week too if needed.

**Comment by thesuperzapper** [comment]
Seems like consensus has been reached!
/lgtm

**Pull request merged**
