### PR TITLE
Upgrade Azure section to release 1.7.0

### PR DESCRIPTION
**Pull request by mosabami**

### CODE REVIEW

**Comment by jbottum** [comment]
the Azure portion looks good but the AWS and IBM sections are potentially messed up

**Comment by thesuperzapper** [comment]
@jbottum it's just because this PR is based on an old fork, once it's merged, it only changes the Azure row, so looks fine to me.

/lgtm

**Comment by thesuperzapper** [comment]
@james-jwu @zijianjoy one of you will need to approve, because there are no active owners in the "getting started" section.

**Pull request merged**
