### PR TITLE
Fixing command to retrieve the existing Dex configmap

### PR DESCRIPTION
**Pull request by yuval-yaari**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1086)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/ok-to-test
/assign @yanniszark 

@yanniszark Please would you verify the change to the command to fetch dex?

**Comment by sarahmaddox** [comment]
@yuval-yaari Thanks for this update! Please would you sign the CLA as requested by the googlebot in a previous comment, and then come back to this PR and add a comment? Your comment will prompt the googlebot to run the CLA check again.

**Comment by yuval-yaari** [comment]
Thanks @sarahmaddox , I signed the CLA

**Comment by sarahmaddox** [comment]
Thanks @yuval-yaari!

**Comment by yanniszark** [comment]
@yuval-yaari great to see you! :D
Thanks for the fix!

/lgtm
/approve

**Comment by sarahmaddox** [comment]
Thanks!
/approve

**Pull request merged**
