### PR TITLE
fix markdown code blocks broken after substituted text tokens

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2770

### CODE REVIEW

**Comment by Arhell** [comment]
before
https://www.kubeflow.org/docs/distributions/azure/authentication-oidc/#kubeflow-configuration

Review page
https://deploy-preview-2809--competent-brattain-de2d6d.netlify.app/docs/distributions/azure/authentication-oidc/#kubeflow-configuration

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Bobgy** [comment]
Can you add owners file for Azure folder? So that you won't need root owner to approve your changes

**Comment by Arhell** [comment]
@kubeflow/azure

**Comment by Arhell** [comment]
cc @Bobgy
I update PR fix only tag

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you for the fix!

**Pull request merged**
