### PR TITLE
Add MLRun Serving: Index + External Add-Ons

### PR DESCRIPTION
**Pull request by alexiguazio**
-Add MLRun serving description under Homepage's Serving (_index) 
- Add KF site under External Add-Ons, Serving

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @RFMVasconcelos

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you for this addition @alexiguazio! 

It looks like MLRun can add value to Kubeflow users. However, it is a bit unclear from this documentation how these would be used together. Would there be a way to add information about this?

**Comment by alexiguazio** [comment]
@RFMVasconcelos Thank you for your review. I have made some changes to the content in mlrun.md that should reflect your recommendations. Please let me know if there is anything else I should amend.

**Comment by RFMVasconcelos** [comment]
@alexiguazio Thank you for the work on this PR.

/lgtm
/approve

**Comment by alexiguazio** [comment]
Thank you :))

**Pull request merged**
