### PR TITLE
Update TFJob docs and document how to upgrade Kubeflow

### LINKED ISSUE #57: Document how you upgrade Kubeflow e.g. from 0.1. to 0.2
We should add some docs on how to upgrade between different versions; even if that means telling people to delete everything and recreate it from scratch since we don't have an upgrade path right now.

### LINKED ISSUE #62: Broken link to user guide
Link to user guide at the end of the getting started guide to troubleshooting section is broken
https://www.kubeflow.org/docs/started/getting-started/

### PR DESCRIPTION
**Pull request by jlewi**
* Explain how to use the new simple example prototype to generate a job.
* Fix some broken links
* Fix #62 - broken links to user guide
* Add instructions for doing upgrades; Fix #57

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @ankushagarwal All broken links are fixed with the exception of http://localhost:8000. Not sure how to configure the link checker to ignore those.

```
docker run --rm ktbartholomew/link-checker https://deploy-preview-71--competent-brattain-de2d6d.netlify.com/
[ BROKEN ] URL:      http://127.0.0.1:8000/
           Error:    Error: connect ECONNREFUSED 127.0.0.1:8000
           Referrer: https://deploy-preview-71--competent-brattain-de2d6d.netlify.com/docs/about/user_guide/
           Element:  <a href="http://127.0.0.1:8000">http://127.0.0.1:8000</a>
[ BROKEN ] URL:      http://localhost:8080/
           Error:    Error: connect ECONNREFUSED 127.0.0.1:8080
           Referrer: https://deploy-preview-71--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-minikube/
           Element:  <a href="http://localhost:8080/">http://localhost:8080/</a>
[ BROKEN ] URL:      http://localhost:8000/
           Error:    Error: connect ECONNREFUSED 127.0.0.1:8000
           Referrer: https://deploy-preview-71--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-minikube/
           Element:  <a href="http://localhost:8000/">http://localhost:8000/</a>
Crawl complete! Broken: 3 Broken/Total: 0.00525

```

**Comment by ankushagarwal** [comment]
I used the checker from here : https://www.npmjs.com/package/recursive-link-checker

It doesn't have an option to ignore certain links

**Pull request merged**
