### PR TITLE
update hugo

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/kubeflow/website/issues/2838

### CODE REVIEW

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Arhell** [comment]
/assign @RFMVasconcelos
last upd https://github.com/kubeflow/website/pull/2808

**Comment by RFMVasconcelos** [comment]
Thank you for this @Arhell ! 

Would you say this is ready to be merged? Have you been able to test that it does not break the website? :)

**Comment by Arhell** [comment]
@RFMVasconcelos 
Of course, both locally and here https://deploy-preview-2840--competent-brattain-de2d6d.netlify.app/

**Comment by RFMVasconcelos** [comment]
Awesome! :tada: 

/lgtm
/approve

**Pull request merged**
