### PR TITLE
Update layouts folder OWNERS file

### PR DESCRIPTION
**Pull request by PatrickXYS**
A follow up PR to add `/aws` folder for shortcode

https://github.com/kubeflow/website/pull/2391

/cc @Bobgy

### CODE REVIEW

**Comment by Bobgy** [comment]
@PatrickXYS you can create a sub folder, there are many examples now

**Comment by PatrickXYS** [comment]
@Bobgy  Thanks, I added `aws` subfolder as suggested

**Comment by Bobgy** [comment]
@PatrickXYS when you add a sub folder, you also need to change the shortcode to aws/...

**Comment by PatrickXYS** [comment]
@Bobgy  Thanks for reminding, addressing your comment and waiting to see test succeed

**Pull request merged**
