### PR TITLE
remove legacy kubeflow operator docs

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR removes the "kubeflow operator" docs from the website as part of https://github.com/kubeflow/website/issues/3074

However, even separate from https://github.com/kubeflow/website/issues/3074, it also reflects the reality that this is no longer a supported method of installing Kubeflow (the latest supported version [is Kubeflow 1.2](https://operatorhub.io/operator/kubeflow), from all the way back in November 2020.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@jbottum @zijianjoy @james-jwu I think this is important to remove from the website.

I am trying to close out https://github.com/kubeflow/website/issues/3074 to make the website actually clear about how to get Kubeflow installed (especially with all the new eyes about to look after the CNCF adoption).

**Comment by thesuperzapper** [comment]
@zijianjoy can you also approve this one, because having these old docs for an unsupported distribution really sends a bad message.

**Comment by thesuperzapper** [comment]
@zijianjoy also, can we please archive the [`kubeflow/kfctl` repo](https://github.com/kubeflow/kfctl), see https://github.com/kubeflow/kfctl/issues/501#issuecomment-1644871752 for more information.

**Comment by Talador12** [comment]
LGTM

**Comment by thesuperzapper** [comment]
@zijianjoy this is now the last remaining section of distribution docs on the website.

As the "kubeflow operator" is no longer maintained, and is incredibly out of date (it has not been updated since Kubeflow 1.2), I think we can safely merge this PR!

PS: once we merge this, I will raise a final PR to remove and redirect the old `/distribution/` docs to the `"installing kubeflow"` page, so we can close https://github.com/kubeflow/website/issues/3074.

**Comment by zijianjoy** [comment]
@animeshsingh @Tomcli Please comment on this PR to remove the legacy kubeflow operator docs. Since we have stopped development/maintenance to this project, can we remove the documentation?

**Comment by Tomcli** [comment]
Yes this document is safe to remove. 

/lgtm

**Pull request merged**
