### PR TITLE
Revert "Added a support page for Kubeflow v1.0.0"

### PR DESCRIPTION
**Pull request by sarahmaddox**
Reverts kubeflow/website#1520

The *hold* on PR # 1520 was removed prematurely. The PR has dependencies on PR https://github.com/kubeflow/website/pull/1308, in terms of content and a link. We should submit the two PRs at the same time.

In addition, the website versioning is currently broken - the support page doesn't show up on the following site as predicted in a comment on the merged PR:
https://competent-brattain-de2d6d.netlify.com/docs/other-guides/
I can't open the page on either v1-0.kubeflow.org/ or master.kubeflow.org.
I'm concerned that if we revert to publishing master on www.kubeflow.org (as I think we should - see issue https://github.com/kubeflow/website/issues/1581) then this page will show up but without the versioning-policy page to back it up.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1584)

### CODE REVIEW

**Comment by jlewi** [comment]
@sarahmaddox Apologies for the churn it took me a while to get netlify working.

The naming schema in Netlify is

https://${BRANCH}--competent-brattain-de2d6d.netlify.com/docs/other-guides/

So the support guide is available at
https://master--competent-brattain-de2d6d.netlify.com/docs/other-guides/support/

We also have a vanity URL
https://master.kubeflow.org/docs/other-guides/support/

As noted in #1586 there is an ugly SSL cert warning but you can work around it.

https://www.kubeflow.org  points to the stable version of the v0.7 docs on the v0.7 branch

I sent you #1585 to remove the **archived version banner**

So with #1586

* Users should see the stable version of the v0.7 docs until we are ready to flip to the v1 docs
* PRs can be merged on master without them being directly shown to users
* master can be viewed by developers and provides a preview

So I think at this point PRs for 1.0 can be unblocked and merged into master. I think this is preferable to putting holds on 1.0 PRs and then trying to get them all merged at once. 

Since users are redirected to the v0.7 branch of the docs, I think its ok if there is some inconsistencies in the master version of the docs while we work on getting them ready for 1.0.

Do we still need to revert this PR?

**Comment by sarahmaddox** [comment]
Yes, we should still revert this PR. The docs on the website should retain their integrity as much as possible, even when on master.kubeflow.org. That is, if we know two PRs belong together, we should attempt to merge them as close to the same time as possible. The support page has a broken link and its content (app status as stable/alpha/beta) depends heavily on a page which does not yet exist.

**Comment by sarahmaddox** [comment]
Thanks. I'll recreate the original PR tomorrow.

**Pull request merged**
