### PR TITLE
Remove chainer docs

### PR DESCRIPTION
**Pull request by jspenc72**
- Removed Chainer Documentation Page
- Added link to Chainer Project
- Added note that Chainer is not supported in Kubeflow >0.6

Closes https://github.com/kubeflow/website/issues/1503

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1516)

### CODE REVIEW

**Comment by jspenc72** [comment]
Hi @sarahmaddox, As I am not a member of the Kubeflow organization I don't have read access to the repo so I could not incorporate the changes after your request. I do plan on making regular contributions to kubeflow so. I will ask to please let me know if you see anything else.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1516--competent-brattain-de2d6d.netlify.com/docs/components/training/chainer/

**Comment by sarahmaddox** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
