### PR TITLE
Create a list of approvers and reviewers for Upgrading Kubeflow docs

### PR DESCRIPTION
**Pull request by 8bitmp3**
Create a list of approvers and reviewers for Upgrading Kubeflow (deployment) docs - currently, there are none

@Bobgy Can you think of anyone else who works directly on the project and can approve the doc additions/changes here? Thank you!!

cc @RFMVasconcelos

### CODE REVIEW

**Comment by 8bitmp3** [comment]
cc @jlewi fyi

**Comment by 8bitmp3** [comment]
We have a PR that may need an OK from an approver:

image

**Comment by RFMVasconcelos** [comment]
Hi @8bitmp3, 

Thank you for bringing this up! 🚀 

This is the same as #2219, but more advanced. I'll close #2219.

**Comment by 8bitmp3** [comment]
@RFMVasconcelos Thanks for checking. As per PR 2219, I'll add @alfsuse 

@Bobgy LMKWYT

**Comment by jlewi** [comment]
@8bitmp3 should we just delete these pages?
https://www.kubeflow.org/docs/upgrading/upgrade/

These docs no longer looks relevant.
 Going forward it probably makes sense to make the upgrade instructions specific to each deployment; e.g. the sections
Kubeflow on GCP
Kubeflow AWS
etc...
Can each have instructions specific to the deployment.

KFUpgrade is no longer used.

For GCP we are using kubeflow/gcp-blueprints#103 to track upgrade instructions.

**Comment by 8bitmp3** [comment]
> @8bitmp3 should we just delete these pages?
> https://www.kubeflow.org/docs/upgrading/upgrade/
> 
> These docs no longer looks relevant.
> 

@jlewi If you're OK with removing the whole section, we can do that (cc @RFMVasconcelos ). Then we together with OWNERS of each of the "subprojects" (AWS, IBM Cloud, Azure, Pipelines, etc) can start adding an `upgrading-kubeflow.md` to their directories.  WDYT?

cc @Bobgy @joeliedtke 

From OWNERS files:

- Google Cloud `docs/gke`:
  @Bobgy
  @joeliedtke
  @rmgogogo

- IBM Cloud `docs/ibm`:
  @adrian555
  @animeshsingh
  @shawnzhu
  @Tomcli

- Azure `docs/azure`:
  @aronchick (we need to get that PR OKed - OWNERS for `azure` https://github.com/kubeflow/website/pull/2199) :)

- AWS `/docs/aws`:
  @Jeffwan
  @PatrickXYS

- Kubeflow Pipelines `/docs/pipelines`: should we have a separate upgrading KF section here?
  @Bobgy
  @IronPan
  @neuromage
  @Ark-kun
  @numerology
  @joeliedtke
  @alfsuse

- Getting started `docs/started` - add a paragraph or two with links?
  @Bobgy
  @knkski

- Components - how do we proceed here?
`components/feature-store`
   @woop
`components/serving`
   @adrian555
   @animeshsingh
   @cliveseldon
   @ellistarn
   @ryandawsonuk   
   @Tomcli
   @yuzisun

Other components...

**Comment by jlewi** [comment]
@8bitmp3 I think its sufficient for now to delete upgrading.md. We can leave it to the respective distribution owners to create their own upgrade documentation if and when they desire to.

**Comment by Bobgy** [comment]
Agree to deleting upgrade.md doc, because the feature is no longer maintained.

**Comment by RFMVasconcelos** [comment]
Given the deletion of the docs, I'll close this PR. 

/close

**Pull request closed without merging**
