### PR TITLE
feat: Add Francisco as OWNER for Feature Store documentation

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
I am one of the [maintainers of Feast](https://github.com/feast-dev/feast/blob/311efc5005b24d1fc9bc389ee7579e102e2cd4ea/community/maintainers.md) and I'd like to update the documentation here. 

So I have proposed to add myself as an OWNER for the Feature Store documentation.

### CODE REVIEW

**Comment by franciscojavierarceo** [comment]
@andreyvelich @woop

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by franciscojavierarceo** [comment]
@Arhell any update here?

**Comment by Arhell** [comment]
Sorry, I don't have approval rights

**Comment by franciscojavierarceo** [comment]
Np I also added a separate PR to add me to the org here: https://github.com/kubeflow/internal-acls/pull/679#issuecomment-2099248303

**Pull request merged**
