### PR TITLE
Update install-kubeflow.md  for latest  Charmed Kubeflow

### PR DESCRIPTION
**Pull request by evilnick**

### CODE REVIEW

**Review by DomFleischmann — COMMENTED** [review]
This looks good but can we also update `Kubeflow Charmed Operators` to version 1.4 in the [Installing Kubeflow section](https://github.com/kubeflow/website/blob/master/content/en/docs/started/installing-kubeflow.md)?

**Comment by evilnick** [comment]
@DomFleischmann done

**Review by DomFleischmann — APPROVED** [review]
LGTM

**Review by knkski — APPROVED** [review]
/lgtm

**Pull request merged**
