### PR TITLE
Add an ML-orchestration blog reference

### PR DESCRIPTION
**Pull request by Sharon-iguazio**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1597)

### CODE REVIEW

**Comment by Sharon-iguazio** [comment]
I'm in the process of checking whether my company already has a Google contributor license agreement / a related Google group, as I see that this is a requirement for submitting PRs.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1597--competent-brattain-de2d6d.netlify.com/docs/examples/blog-posts/

Thanks @Sharon-iguazio this LGTM, pending the CLA.

/lgtm
/ok-to-test

**Comment by Sharon-iguazio** [comment]
@googlebot I signed it!

**Comment by sarahmaddox** [comment]
@Sharon-iguazio the CLA register doesn't contain a CLA for your username or for the email address that you used in this commit. Please would you check that you signed the CLA with the same email address?

**Comment by Sharon-iguazio** [comment]
> @Sharon-iguazio the CLA register doesn't contain a CLA for your username or for the email address that you used in this commit. Please would you check that you signed the CLA with the same email address?

@sarahmaddox I initially wanted our CTO to sign the CLA (although I should also have relevant permissions), but he's currently unavailable. I tried to submit a new CLA with me as the authorized signer, but the system doesn't let me submit a new CLA because it identifies that one has already been submitted. => Is there any way we can change the CLA so that I can sign it?

**Comment by sarahmaddox** [comment]
@googlebot recheck

**Comment by sarahmaddox** [comment]
@abhi-g Do you have any ideas here? The CLA tool is still saying "need_author_cla".

**Comment by kunmingg** [comment]
The PR author need to sign with their own account.

**Comment by abhi-g** [comment]
@sarahmaddox can you please verify that we can find the CLA for the author. It needs to match the GitHub user ID/email for the commits. Once you have verified, I can try override.

**Comment by sarahmaddox** [comment]
@abhi-g There isn't a CLA that matches the author's GitHub ID or email address. The CTO of the author's company has signed the CLA. 

@Sharon-iguazio according to the googlebot's [comment above](https://github.com/kubeflow/website/pull/1597#issuecomment-581621214):
> The email used to register you as an authorized contributor must be the email used for the Git commit. Check your existing CLA data and verify that your email is set on your git commits.
The email used to register you as an authorized contributor must also be attached to your GitHub account.

Do you know whether the CTO used the correct email address for you?

**Comment by Sharon-iguazio** [comment]
I just signed a personal CLA as well. Retrying:
/retest

**Comment by Sharon-iguazio** [comment]
@sarahmaddox / @abhi-g I've now signed a personal CLA for the same Google account that's associated with this PR (Sharon-iguazio GH user uses email sharonl@iguazio.com / sharonl@iguaz.io). I don't know what else I can do ... .

**Comment by sarahmaddox** [comment]
@googlebot recheck please

**Comment by sarahmaddox** [comment]
Thanks for persevering @Sharon-iguazio! Now that there's a CLA registered, your next PR will go through smoothly. :)

/approve

**Comment by Sharon-iguazio** [comment]
Thanks @sarahmaddox! When can we expect to see our changes online?

**Comment by sarahmaddox** [comment]
@Sharon-iguazio the change is visible at https://master.kubeflow.org/docs/examples/blog-posts/

A bit of explanation :)

www.kubeflow.org is currently pointing to the archived v0.7 docs. Currently, new docs after PR merge will appear on master.kubeflow.org. This is to give us the opportunity to publish the v1.0 docs without disturbing Kubeflow users on www.kubeflow.org. 

Close to the launch of v1.0, we'll point www.kubeflow.org back to master.

**Comment by Sharon-iguazio** [comment]
Thanks @sarahmaddox. 
1. What's the current estimated release date for v1.0?
2. I wanted to start watching the repo's [releases](https://github.com/kubeflow/website/releases), but I see that there's no release information there (including in the tags). => How can I get notifications of new Kubeflow releases?

**Comment by sarahmaddox** [comment]
@Sharon-iguazio We're busy cutting the next RC (release candidate) for v1.0. We're hoping to finalize the release by end this week. For up-to-date commentary, you can join the #release channel on Kubeflow Slack. For notification of release features, watch the blog. There's more info about the community here: https://master.kubeflow.org/docs/about/community/

**Comment by sarahmaddox** [comment]
Oh, and we also have this new page which may be interesting: https://master.kubeflow.org/docs/other-guides/support/ (currently showing up on master only).

**Comment by Sharon-iguazio** [comment]
Thanks @sarahmaddox! Good luck with the release.

**Pull request merged**
