### PR TITLE
Fix links to machine types and kustomize configuration

### PR DESCRIPTION
**Pull request by tom1299**
Update of two links to machines types and kustomize.

### CODE REVIEW

**Comment by hbelmiro** [comment]
/ok-to-test
/lgtm

@chensun can you PTAL?

**Comment by hbelmiro** [comment]
@tom1299 can you please rebase?

**Comment by varodrig** [comment]
content is still valid, but needs to be moved to https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/standalone-deployment/
@tom1299  can you please make this update? thank you
cc @hbelmiro

**Comment by tom1299** [comment]
I'm sorry but I accidentally closed the PR while doing the changes. I moved the changes to the legacy documentation.

**Pull request merged**
