### PR TITLE
Fix typo on kubeflow notebook quickstart guide

### PR DESCRIPTION
**Pull request by k-jeon**
* "exit" -> "exist" in configurations step

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by abinthomasonline** [comment]
this must be a record, 400 days for a minor documentation fix.

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads Can we please approve and merge this ?

**Pull request merged**
