### PR TITLE
Fix management project variable name

### PR DESCRIPTION
**Pull request by plang85**

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
/assign @joeliedtke

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you @plang85 for this fix.

/lgtm

@zijianjoy @Bobgy could you please confirm that this is an issue (GKE distro)

**Comment by zijianjoy** [comment]
This issue has caused many confusions in the past. We have updated the documentation in the right page using the right naming approach: https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#authorize-cloud-config-connector-for-each-kubeflow-project. 

Therefore this PR is not necessary to be merged, but thank you so much for improving the doc! Appreciate it a lot! @plang85

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
