### PR TITLE
Adding update to KF 1.0 installation instructions on OCP

### PR DESCRIPTION
**Pull request by nakfour**
This PR is to add an OWNERS file to Openshift installation pages and to update instructions to KF 1.0.

### CODE REVIEW

**Comment by jlewi** [comment]
@nakfour The problem with the PR is explained in the error message
https://github.com/kubeflow/website/pull/2107#issuecomment-671593299

Everyone listed in an OWNERs file must already be a member of the Kubeflow GitHub org. 

My suggestion would be to add as approvers existing folks working on openshift e.g. @animeshsingh @vpavlin etc... who are already as approvers. That way they can approve this and other PRs.

Separately you can look into becoming a member of the org and once that happens open up a PR to add yourself to the OWNERs file.

**Comment by crobby** [comment]
The content of this lgtm.

**Comment by animeshsingh** [comment]
Thanks @nakfour 

We are also working on getting the Kubeflow Operator exposed in OCP catalog, and will append the instructions once its made available there.

/lgtm
/approve

**Comment by nakfour** [comment]
@jlewi would the "out of date" banner still stay even though we updated the docs? What is the process to get the banner deleted?

**Comment by Bobgy** [comment]
@nakfour the banner is in `*.md` files, when you finish updating a file, you can remove that banner in the same PR

**Comment by nakfour** [comment]
@Bobgy this PR has merged, I will open a new one thanks

**Pull request merged**
