### PR TITLE
Update quickstart-guide.md

### PR DESCRIPTION
**Pull request by Souheil-Yazji**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by hbelmiro** [comment]
@thesuperzapper would you like to merge this PR?
Otherwise, we can close it.

**Comment by thesuperzapper** [comment]
@hbelmiro as its not got a DCO sign-off, we cant merge it anyway.

**Comment by hbelmiro** [comment]
/close
Due to inactivity.

**Pull request closed without merging**
