### PR TITLE
Kfserving update

### PR DESCRIPTION
**Pull request by animeshsingh**
Rearranged KFServing writeup

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1320)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1320--competent-brattain-de2d6d.netlify.com/docs/components/serving/kfserving/

**Comment by sarahmaddox** [comment]
@animeshsingh Please would you fix the rendering problems and comment when the PR is ready for final review.

See preview: https://deploy-preview-1320--competent-brattain-de2d6d.netlify.com/docs/components/serving/kfserving/

**Comment by animeshsingh** [comment]
thanks @sarahmaddox - ready for review

**Comment by sarahmaddox** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
