### PR TITLE
s/AWS/Azure/

### PR DESCRIPTION
**Pull request by jameswnl**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/792)

### CODE REVIEW

**Comment by jameswnl** [comment]
I signed it!

**Comment by sarahmaddox** [comment]
Thank you for this contribution. A couple of people noticed this problem, and jumped in to fix it. The change is in the prior PR https://github.com/kubeflow/website/pull/787, currently under review, so I'll put a hold on this PR.

/hold

**Comment by sarahmaddox** [comment]
PR https://github.com/kubeflow/website/pull/787 has fixed the problem.

/close

**Pull request closed without merging**
