### PR TITLE
Remove the outdated banner for cloud storage

### PR DESCRIPTION
**Pull request by yilun-msft**
Remove the banner indicating outdated and directly land user to the installation page. This will align with pages for GKE and IBM.

### CODE REVIEW

**Comment by yilun-msft** [comment]
@shbijlan jFYI

**Comment by 8bitmp3** [comment]
/assign @aronchick @jbottum @PatrickXYS 
(OWNERS)

cc @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
This document no longer exists after #2498. 

We can close this PR. 

/close

**Pull request closed without merging**
