### PR TITLE
update blog link

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2810

### CODE REVIEW

**Comment by Arhell** [comment]
cc @thesuperzapper

**Comment by Arhell** [comment]
cc @thesuperzapper

**Comment by Arhell** [comment]
page
https://deploy-preview-2815--competent-brattain-de2d6d.netlify.app/docs/started/

**Comment by Arhell** [comment]
сс @Bobgy review please

**Review by RFMVasconcelos — COMMENTED** [review]
The blog appears to be is the most up-to-date. 

/lgtm

**Comment by RFMVasconcelos** [comment]
Thank you for tackling this @Arhell !

**Comment by Arhell** [comment]
сс @Bobgy

**Comment by Arhell** [comment]
сс @Bobgy

**Comment by terrytangyuan** [comment]
I don't have permission to approve in this repo so you probably want to tag someone else.

**Pull request merged**
