### PR TITLE
added enable Cloud Build API

### LINKED ISSUE #1814: Set up a GCP Project
I think in https://www.kubeflow.org/docs/gke/deploy/project-setup/, step 4 should mention to enable 
Cloud Build API.

### PR DESCRIPTION
**Pull request by imskr**
Closes #1814 

Added enable cloud build API in step 4 [here](https://www.kubeflow.org/docs/gke/deploy/project-setup/)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1817)

### CODE REVIEW

**Comment by imskr** [comment]
@sarahmaddox Done.

**Comment by sarahmaddox** [comment]
/assign
/ok-to-test
/unassign @neuromage 

Preview: https://deploy-preview-1817--competent-brattain-de2d6d.netlify.com/docs/gke/deploy/project-setup/

**Comment by sarahmaddox** [comment]
Thanks @imskr!
/lgtm
/approve

**Pull request merged**
