### PR TITLE
Fixed broken AWS Pipelines link for 1.3 docs branch

### PR DESCRIPTION
**Pull request by judyheflin**
Fixed relative link to new AWS Pipelines page

### CODE REVIEW

**Comment by surajkota** [comment]
@judyheflin can we point to the relevant section as well?

**Comment by judyheflin** [comment]
> 

Added

**Comment by judyheflin** [comment]
> @judyheflin can we point to the relevant section as well?

Added

**Comment by surajkota** [comment]
@Arhell can you take a look, same as #3176

**Comment by surajkota** [comment]
@Arhell can you take a look, same as #3176

**Comment by surajkota** [comment]
@Arhell @Ark-kun review please, thanks

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by surajkota** [comment]
@Arhell please merge this PR

**Comment by Arhell** [comment]
> @Arhell PR is ready to merge

https://github.com/kubeflow/website/pull/3188#issuecomment-1064502539

**Comment by surajkota** [comment]
@Bobgy, @IronPan, @neuromage, @chensun can one of you approve this tiny PR?

**Comment by surajkota** [comment]
@Bobgy, @IronPan, @neuromage, @Ark-kun, @numerology can one of you approve this tiny PR?

**Comment by surajkota** [comment]
@Bobgy, @IronPan, @neuromage, @Ark-kun, @numerology can one of you approve this tiny PR?

**Review by chensun — APPROVED** [review]

**Pull request merged**
