### PR TITLE
update hugo to last version

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/kubeflow/website/issues/2959

### CODE REVIEW

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Arhell** [comment]
/assign @RFMVasconcelos
local check

**Comment by Bobgy** [comment]
/assign @zijianjoy
Can you help @Arhell review?
This is a usual dependency upgrade

**Comment by Arhell** [comment]
> /assign @zijianjoy
> Can you help @Arhell review?
> This is a usual dependency upgrade

I've already checked everything, both locally and here https://deploy-preview-2973--competent-brattain-de2d6d.netlify.app/

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you for the hugo upgrade!

**Pull request merged**
