### PR TITLE
Updated the Pipelines Quickstart screenshots and related text for Kubeflow 0.5

### PR DESCRIPTION
**Pull request by sarahmaddox**
Part of issue https://github.com/kubeflow/website/issues/505

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/585)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/587

**Comment by sarahmaddox** [comment]
Preview:

* https://deploy-preview-585--competent-brattain-de2d6d.netlify.com/docs/pipelines/pipelines-quickstart/
* https://deploy-preview-585--competent-brattain-de2d6d.netlify.com/docs/pipelines/pipelines-overview/
* https://deploy-preview-585--competent-brattain-de2d6d.netlify.com/docs/pipelines/pipelines-concepts/

**Comment by abhi-g** [comment]
/lgtm
/approve

Thanks Sarah

**Pull request merged**
