### PR TITLE
Adding docs for Azure MySQL

### PR DESCRIPTION
**Pull request by yilun-msft**
Adding documents for Azure Database for MySQL. The content is coming from [this PR](https://github.com/kubeflow/manifests/pull/1587/files)

### CODE REVIEW

**Comment by 8bitmp3** [comment]
Thank you @yilun-msft !

To make a few things easier during the review, I'll send you a PR with code and text linting changes and other proposals, then explain them here, if you don't mind.

cc @sudivate @eedorenko

**Comment by yilun-msft** [comment]
Thanks @8bitmp3. Any update on this?

**Comment by 8bitmp3** [comment]
@yilun-msft Send you PR https://github.com/yilun-msft/website/pull/1

I have a few small questions.

Thank you!

**Comment by 8bitmp3** [comment]
@yilun-msft What do you think of those proposed changes? https://github.com/yilun-msft/website/pull/1 Feel free to copy-paste them and amend them in your PR branch and I can close mine.

**Comment by yilun-msft** [comment]
> @yilun-msft What do you think of those proposed changes? [yilun-msft#1](https://github.com/yilun-msft/website/pull/1) Feel free to copy-paste them and amend them in your PR branch and I can close mine.

Thanks for the changes. They look great to me. I will copy them to this PR and wait for my team to review. Thanks!

**Comment by 8bitmp3** [comment]
Thank you @yilun-msft 

/ok-to-test

**Comment by yilun-msft** [comment]
@eedorenko @sudivate, see if it documents all the necessary information and is well-understandable for Azure users? 
FYI @shbijlan: see if there are anything needed to be added/changed?

**Comment by shbijlan** [comment]
@yilun-msft looks good. Can you confirm if alert/warning heading appears properly in markdown? Not sure if I am seeing it formatted correctly.

**Comment by 8bitmp3** [comment]
@shbijlan Thank you 👍 

https://deploy-preview-2304--competent-brattain-de2d6d.netlify.app/docs/azure/azuremysql/

Great job @yilun-msft! 

In case you're not aware, to check the website preview, click on "Details" next to "deploy/netlify" in the window at the bottom of this PR where it shows which tests are being/have been done.

@eedorenko @shbijlan @sudivate I think we also need this to be `/approve`d if you're happy.

/lgtm

**Comment by yilun-msft** [comment]
Hi @8bitmp3, sorry for a qq. Why isn't this doc being updated to v1.1 branch, which is the one used for www.kubeflow.org. Do I need to create a PR for that branch separately?

**Comment by berndverst** [comment]
@yilun-msft will need to cherry pick this into the v1.1 branch. Once the branch is created it isn't synced with master but needs cherry picks. I'll make the PR and you'll have to approve.

**Comment by 8bitmp3** [comment]
Thanks @berndverst! @yilun-msft - I hope this has helped with your question. cc'ing @RFMVasconcelos (getting ready for KF v1.2 👑 😃)

**Comment by yilun-msft** [comment]
> Thanks @berndverst! @yilun-msft - I hope this has helped with your question. cc'ing @RFMVasconcelos (getting ready for KF v1.2 👑 😃)

Awesome! Thanks!

**Pull request merged**
