### PR TITLE
Generate social embed images for all pages

### PR DESCRIPTION
**Pull request by thesuperzapper**
On social media like Slack, LinkedIn, Facebook, etc. the Kubeflow website does not display an embedded image.

For example:

Screenshot 2024-07-21 at 19 11 24

This PR makes it so that each page has a unique image (with the title of the page) to show on social media sites.
This is really important for people wanting to share about Kubeflow publicly.

For example, here are some of the generated images:

social 62fafe114d1c92485c6088c3efd27ce2

social 8fc3e9355cc74412ab45fdd6a3332bad

As new pages are added, this system will automatically generate new social images.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I have tested with the preview, and they work properly on Slack and Discord:

Screenshot 2024-07-21 at 19 45 18

Screenshot 2024-07-21 at 19 46 29

**Comment by thesuperzapper** [comment]
@james-jwu @jbottum @andreyvelich @terrytangyuan can one of you please review or approve this website PR?

It adds automatic social media image embeds for each page (the images that come up when you post a link on Slack or LinkedIn).

I think adding these images will make people much more likely to share Kubeflow!

**Review by terrytangyuan — COMMENTED** [review]
Can you share previews for LI and X?

**Comment by thesuperzapper** [comment]
@terrytangyuan here is the LinkedIn example:

Screenshot 2024-07-21 at 20 40 08

I can get X to work with the test site, I think they block embeds strange domains like `deploy-preview-3818--competent-brattain-de2d6d.netlify.app`, however all the testers I see online say it should be working.

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
