### PR TITLE
chore: bump model registry python client version

### PR DESCRIPTION
**Pull request by Al-Pragliola**
This PR bumps the model registry python client version to the latest one, in the Model Registry "Getting Started" page.

1.  changed from "0.2.3a1" to "0.2.5a1"

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by tarilabs** [comment]
@Al-Pragliola I think we should close this one as it was superseeded with https://github.com/kubeflow/website/pull/3922

cc/ @varodrig @rimolive docs fyi

**Comment by Al-Pragliola** [comment]
> @Al-Pragliola I think we should close this one as it was superseeded with #3922
> 
> cc/ @varodrig @rimolive docs fyi

yes thank you for pointing it out @tarilabs

**Comment by Al-Pragliola** [comment]
superseeded by https://github.com/kubeflow/website/pull/3922

**Pull request closed without merging**
