### PR TITLE
WtD fixit: Readability improvements for Overview of Kubeflow Fairing

### PR DESCRIPTION
**Pull request by nkrish1983**
Fixes https://www.kubeflow.org/docs/fairing/fairing-overview/

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1369)

### CODE REVIEW

**Comment by alecglassford** [comment]
Fixes https://github.com/kubeflow/website/issues/1353

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1369--competent-brattain-de2d6d.netlify.com/docs/fairing/fairing-overview/

**Comment by sarahmaddox** [comment]
Thanks @nkrish1983 these changes look great! Please would you sign the CLA and then add a comment to this PR, as prompted by the googleblot in a previous comment.

/lgtm
/approve

**Comment by sarahmaddox** [comment]
I've checked the CLA - it looks good.

@googlebot re-check CLA.

**Pull request merged**
