### PR TITLE
update tfjob, pytorchjob ref scripts, style tables

### PR DESCRIPTION
**Pull request by kbhawkey**
- simple update of table styling in api gen scripts: tf job, pytorch job.
- h3->code could use a better color for highlighting.
- See #680.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/805)

### CODE REVIEW

**Comment by kbhawkey** [comment]
@sarahmaddox

**Comment by sarahmaddox** [comment]
/ok-to-test
/assign @richardsliu 

Thanks @kbhawkey! I've assigned @richardsliu to take a look, because he wrote the original scripts for ref doc generation.

**Comment by richardsliu** [comment]
@kbhawkey Thanks for doing this. Can you also make similar changes for the pytorch script?

**Comment by sarahmaddox** [comment]
This is soooo much better. Thank you @kbhawkey!

**Comment by kbhawkey** [comment]
👍 😃

**Pull request merged**
