### PR TITLE
remove `Reference` section

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR resolves: https://github.com/kubeflow/website/issues/2970

__Here's what has been done to each page under `Reference`:__
- `Reference Overview`
   - __REMOVE__
   - this page is redundant without the `Reference` section
- `Kubeflow Versioning Policies`
   - __REMOVE__
   - the "Kubeflow application matrix" is no longer needed after the [`Releases` section PR](https://github.com/kubeflow/website/pull/3015))
- `Dockerfile Locations`
   - __REMOVE__
   - the cost of keeping this page up-to-date in future is not worth it
- `Katib Reference`
   - __MOVE__ to `Components / Katib / API Reference`
- `Notebook CRD Reference`
   - __MOVE__ to `Components / Notebook Servers / API Reference`
- `MPIJob Reference`
   - __REMOVE__
   - @kubeflow/wg-training-leads [no longer want CRD reference](https://github.com/kubeflow/website/pull/3002#issuecomment-938612528)
- `PyTorchJob Reference`
   - __REMOVE__
   - @kubeflow/wg-training-leads [no longer want CRD reference](https://github.com/kubeflow/website/pull/3002#issuecomment-938612528)
- `TFJob Reference`
   - __REMOVE__
   - @kubeflow/wg-training-leads [no longer want CRD reference](https://github.com/kubeflow/website/pull/3002#issuecomment-938612528)

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@kubeflow/wg-training-leads to be able to move the `Training Operator` related references, I had to restructure the `Components / References`  section, so you might want to take a look at this PR!

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by thesuperzapper** [comment]
@james-jwu this should be a pretty easy merge now, can you review when you get time?

The full list of changes can be seen in the [PR description](https://github.com/kubeflow/website/pull/3014#issue-752741476).

---

_(NOTE: the @kubeflow/wg-training-leads said they are happy to just remove their CRD reference: https://github.com/kubeflow/website/pull/3002#issuecomment-938612528)_

**Comment by kramachandran** [comment]
@thesuperzapper  -- There was some text in version-policy.md which described the versioning scheme, and the meanings of the terms Stable, Beta and Alpha.  Did that content get moved somewhere? I think we want to perserve it.  

I do like what you did in moving the "Kubeflow application matrix" to a seperate release section. That greatly clarifies that content. 

My suggestion would be to keep the version-policy page, but remove the application matrix.

**Comment by kramachandran** [comment]
I see -- I was actually hoping that we could preserve the sections labeled "Kubeflow Versioning" and "Application versioning and stable status". I don't think that text is present on support page. 

Perhaps this content can be migrated over there?

**Comment by thesuperzapper** [comment]
@kramachandran actually that "Kubeflow Versioning" text is incorrect so needs to be removed:
1. We no longer use `kfctl` 
2. We now "version" kubeflow based on the [kubeflow/manifests](https://github.com/kubeflow/manifests) repo, not releases of `kfctl`
3. We don't actually follow semantic versioning (and its dangerous to imply that we do)
    - NOTE: I am talking about the whole project here, specific sub-projects (like pipelines) might follow symantic versioning

**Pull request merged**
