### PR TITLE
added get-credentials command to configures kubectl on Azure

### PR DESCRIPTION
**Pull request by adipola**
To configure kubectl to connect to Kubernetes cluster, az aks get-credentials command is used. This command downloads credentials and configures the Kubernetes CLI to use them.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1785)

### CODE REVIEW

**Comment by adipola** [comment]
@googlebot I signed it!

**Comment by sarahmaddox** [comment]
/assign @vjrantal 

@vjrantal please would you take a look at this PR?

**Comment by vjrantal** [comment]
@adipola It looks like `az aks get-credentials` is the first documented command to run under this section https://github.com/kubeflow/website/blob/1cd1f97077698e77f4aec7b5358b3f843ca133af/content/docs/azure/deploy/install-kubeflow.md#kubeflow-installation.

**Comment by adipola** [comment]
@vjrantal you are right! thanks! closing the PR.

**Comment by sarahmaddox** [comment]
> @vjrantal you are right! thanks! can you please close the PR?

Thanks @adipola!
/close

**Pull request closed without merging**
