### PR TITLE
update navbar on tablet & mobile

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2568

### CODE REVIEW

**Comment by Arhell** [comment]
on the PC remained as it is at the moment (may be small changes)
**On a tablet**

**On mobile**

**Comment by thesuperzapper** [comment]
@Arhell this is great!

/lgtm

@RFMVasconcelos can you review/approve this?

**Review by RFMVasconcelos — COMMENTED** [review]
Looks good to me. Thank you @Arhell for your contribution! 

/lgtm
/approve

**Pull request merged**
