### PR TITLE
Update redirects to include job scheduling change

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
See issue #2520

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@Bobgy could I ask you to quickly review and merge this, please?

**Comment by Bobgy** [comment]
/lgtm
/approve

Sorry, missed the notification

**Comment by RFMVasconcelos** [comment]
@Bobgy Thank you for taking a look at this PR and approving it! 

There were some conflicts that I had to fix, so we need another /lgtm 🙏

**Pull request merged**
