### PR TITLE
Fixing kfctl_aws hyperlink in IAM-SA doc

### PR DESCRIPTION
**Pull request by gautamkmr**

### CODE REVIEW

**Comment by gautamkmr** [comment]
@Jeffwan

**Comment by Jeffwan** [comment]
Thanks for the contribution. @gautamkmr 

You can use this `{{% config-uri-aws-standard %}}` and `{{% config-uri-aws-cognito %}}`

Check details and usage in `install-kubeflow.md`. We don't need to update it in the future.

**Comment by Jeffwan** [comment]
/lgtm

Thanks for the help.

**Pull request merged**
