### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by GraphtyLove**

### CODE REVIEW

**Comment by joeliedtke** [comment]
Preview: https://deploy-preview-2013--competent-brattain-de2d6d.netlify.app/docs/pipelines/sdk/parameters/

**Comment by joeliedtke** [comment]
Thanks for fixing this, @GraphtyLove! Looks like we need you to complete the CLA and then I can move forward with the PR review.

**Comment by GraphtyLove** [comment]
@googlebot I signed it!

Best regards,
Maxim Berge


Le mar. 23 juin 2020 à 18:37, Joe Liedtke <notifications@github.com> a
écrit :

**Comment by joeliedtke** [comment]
/lgtm
/approve

Thanks for fixing this, @GraphtyLove!

**Pull request merged**
