### PR TITLE
AWS distribution version and links update

### PR DESCRIPTION
**Pull request by surajkota**
https://github.com/kubeflow/blog/pull/119

Updated generalized Kubeflow on AWS links for 1.5.1 release

@PatrickXYS is no longer owning AWS docs

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by surajkota** [comment]
@Arhell can you please add approve label as well?

**Comment by Arhell** [comment]
> @Arhell can you please add approve label as well?

https://github.com/kubeflow/website/blob/master/OWNERS#L1

**Comment by surajkota** [comment]
@chensun can you please add approve label as well?

**Pull request merged**
