### PR TITLE
Add more instructions and screenshots to setup authentication in AWS

### PR DESCRIPTION
**Pull request by Jeffwan**

### CODE REVIEW

**Comment by Jeffwan** [comment]
@theofpa  Please have a check.

**Comment by theofpa** [comment]
> @theofpa Please have a check.

/lgtm

**Comment by sarahmaddox** [comment]
Thanks @Jeffwan and @theofpa 
/lgtm
/approve

**Comment by sarahmaddox** [comment]
@Jeffwan Please would you resolve the merge conflicts?

**Comment by Jeffwan** [comment]
@sarahmaddox just rebase the upstream changes.

**Comment by cloudbow** [comment]
+100 for this as it was self explanatory now

**Pull request merged**
