### PR TITLE
Adding to Kubeflow support providers

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
As Canonical is committed to supporting Kubeflow users, we're enthusiastic about adding our name here to help remove frictions from Kubeflow adoption.

Switched order to be alphabetical, as would be confusing otherwise.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@joeliedtke @rmgogogo sorry to bother you with this! Adding Canonical to support organizations, as we are now able to provide enterprise support to our K8s customers on Kubeflow. 

Would you please review this PR?

/assign @joeliedtke 
/assign @rmgogogo

**Comment by Bobgy** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
