### PR TITLE
Improve update instruction steps

### PR DESCRIPTION
**Pull request by jonasdebeukelaer**
* Two additional env variables are required for kf cluster setup
* clearer env var reference for management cluster update

Side note: is there a way to test the update was successful? aside from no errors in console?

### CODE REVIEW

**Comment by jonasdebeukelaer** [comment]
Also it would be safer to require the user to specify the managed cluster's namespace name in the management cluster.
 
I have two clusters managed, and the default context in the management cluster points to one of the two kf clusters. When trying to update the second kf cluster, they were clashing. Hopefully it's not broken anything, i need to investigate.

**Review by 8bitmp3 — COMMENTED** [review]
/assign @Bobgy

And HNY to y'all! 🥂

**Comment by Bobgy** [comment]
/lgtm
/approve
thanks for the fix!

**Comment by Bobgy** [comment]
> Also it would be safer to require the user to specify the managed cluster's namespace name in the management cluster.
> 
> I have two clusters managed, and the default context in the management cluster points to one of the two kf clusters. When trying to update the second kf cluster, they were clashing. Hopefully it's not broken anything, i need to investigate.

good point, mind opening a separate issue?

**Comment by jonasdebeukelaer** [comment]
@Bobgy sure np

**Pull request merged**
