### PR TITLE
 Updated the docs guide with info about using the Docsy theme.

### PR DESCRIPTION
**Pull request by sarahmaddox**
Updated the README with info about styling, menu structure, and other usage tips for the new theme. (See issue [291](https://github.com/kubeflow/website/issues/291).)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/397)

### CODE REVIEW

**Comment by abhi-g** [comment]
Thanks for the cleanup and updates Sarah. Do we need to add any example command line for installing hugo 0.45 extended version? The link from docsy guide is also very thin on hugo installation.

Otherwise looks great.

**Comment by sarahmaddox** [comment]
The merge caused a weird CLA error on automated testing of this PR, so I'm going to close this PR. See the replacement PR [#401](https://github.com/kubeflow/website/pull/401).

/close

**Pull request closed without merging**
