### PR TITLE
Redirects blog to medium.com and removes obsolete blog entries.

### PR DESCRIPTION
**Pull request by sarahmaddox**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/338)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Try it:
https://deploy-preview-338--competent-brattain-de2d6d.netlify.com/blog/
https://deploy-preview-338--competent-brattain-de2d6d.netlify.com/blog/why_kubeflow/

**Comment by abhi-g** [comment]
Thanks Sarah. This looks great.

/lgtm
/approve

**Pull request merged**
