### PR TITLE
Add Katib config PV reclaim policy

### PR DESCRIPTION
**Pull request by andreyvelich**
Related to: https://github.com/kubeflow/katib/blob/master/pkg/util/v1beta1/katibconfig/config.go#L130.
I added info about `persistentVolumeReclaimPolicy` for the Suggestion's PV.

/cc @gaocegege @johnugeorge @RFMVasconcelos

### CODE REVIEW

**Comment by andreyvelich** [comment]
cc @8bitmp3 It would be great if you can help with the review on this PR!

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you for this @andreyvelich! 
This looks good to me! Letting some time for @8bitmp3 to review as well, if he's busy I can LGTM.

**Review by gaocegege — APPROVED** [review]
LGTM

**Comment by andreyvelich** [comment]
@RFMVasconcelos @gaocegege Can you add `/lgtm` on this pr, please ?

**Pull request merged**
