### PR TITLE
Update website for TFJob/PyTorchJob v1 docs

### PR DESCRIPTION
**Pull request by richardsliu**
Removed v1beta1 documentation, added v1.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/732)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: 

* https://deploy-preview-732--competent-brattain-de2d6d.netlify.com/docs/reference/pytorchjob/
* https://deploy-preview-732--competent-brattain-de2d6d.netlify.com/docs/reference/tfjob/

**Comment by sarahmaddox** [comment]
LGTM with just one question: I see we've removed the v1beta1 API reference, replacing it with v1. Is that because v1beta1 is no longer supported?

/lgtm

**Comment by richardsliu** [comment]
@sarahmaddox Yes, we have stopped supporting v1beta1. V1 is the stable release now, and v1beta2 is for backward compatibility.

**Pull request merged**
