### PR TITLE
Updates metrics screenshot to Kubeflow v0.5

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/588

I also improved the text of the page while I was there.

Note: I could not find the code that creates the metrics for the XGBoost sample:
https://github.com/kubeflow/pipelines/tree/master/samples/xgboost-spark

The metrics page currently points to the code for a different Python sample, which only has one metric.

It'd be nice to point to the code that specifies the metrics for the XGBoost sample, if anyone knows where it is.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/608)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-608--competent-brattain-de2d6d.netlify.com/docs/pipelines/metrics/pipelines-metrics/

**Comment by abhi-g** [comment]
looks good to me. /cc @IronPan, please ensure correctness or add someone who can review.

**Pull request merged**
