### PR TITLE
fix kfctl version

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2983

### CODE REVIEW

**Comment by Arhell** [comment]
@kimwnasptd  done

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by zijianjoy** [comment]
I will defer to @kubeflow/azure to approve this PR because it touches Azure distribution doc.

**Comment by Arhell** [comment]
cc @dtzar
cc @berndverst

**Comment by dtzar** [comment]
Ah - looks like I no longer have approval ability.  @eedorenko - this is just a doc fix to get the proper kubectl version in there.

**Comment by Arhell** [comment]
> Ah - looks like I no longer have approval ability. @eedorenko - this is just a doc fix to get the proper kubectl version in there.

try /approve

**Comment by Arhell** [comment]
@dtzar
https://github.com/kubeflow/website/pull/3046#issuecomment-957327670
try /approve

**Comment by dtzar** [comment]
Nope - I'm not in the owners list anymore

**Pull request merged**
