### PR TITLE
Add RFMVasconcelos to reviewers - see #2104

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Creating this PR as a follow-up on #2104.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
Thank you @8bitmp3 !

**Comment by jlewi** [comment]
@RFMVasconcelos You will need to assign this to an approver per the K8s bot notice in order to get it approved. I can't approve it.

**Comment by 8bitmp3** [comment]
Hi @animeshsingh @Bobgy @rmgogogo Is this good to go? Thanks!!

**Comment by Bobgy** [comment]
Sure
/lgtm
/approve

**Pull request merged**
