### PR TITLE
Remove Fairing section

### PR DESCRIPTION
**Pull request by 80rian**
Resolves: #3721

Removing Fairing link as Fairing pages are removed from #3553.

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Comment by rimolive** [comment]
/cc @kubeflow/kubeflow-steering-committee 

How can we proceed with documentation PRs? We have lots of OWNERS files spread in the repo, and only KSC members as the root OWNERS. If we want to ensure the [Documentation phase](https://github.com/kubeflow/community/blob/master/releases/handbook.md#documentation-3-weeks-starts-the-same-time-as-feature-freeze) can move on smoothly the Release Team need some autonomy to merge PRs.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
