### PR TITLE
[wip] added kaptain (D2iQ's kubeflow distribution) to kubeflow docs

### PR DESCRIPTION
**Pull request by chessahoekstra**
- added a description in the docs/distributions
- added a table entry in Support
- added a table entry in Installing Kubeflow

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by thesuperzapper** [comment]
@chessahoekstra We won't be adding any more distribution-owned docs to the website, we are planning to remove the `distribution` section on __Feb 1, 2022__, see issue: https://github.com/kubeflow/website/issues/3074

This is NOT to say you can't be linked under "Installing Kubeflow" (if you are active contributors to Kubeflow), but be aware that in the near future you will have to be certified under the [Certified Kubeflow](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-conformance-program-proposal.md#certified-kubeflow-for-kubeflow-distribution) program to be listed.

/hold

**Comment by chessahoekstra** [comment]
@thesuperzapper it seems that the effort to remove distributions to the website hasn't made progress, and in fact, new distributions have been added since this PR was closed

**Comment by thesuperzapper** [comment]
@chessahoekstra a quick update is that we should be able to merge these changes (with a few tweaks) once https://github.com/kubeflow/website/pull/3381 is merged.

Once https://github.com/kubeflow/website/pull/3381 is merged, please update your PR to use the new formatting of the "installing kubeflow" table, and ping me (or someone else) for a review.

**Comment by jbottum** [comment]
@chessahoekstra Did this get resolved to your satisfaction ?

**Comment by thesuperzapper** [comment]
@chessahoekstra is this distribution continuing to exist? If so, let's get it added asap.

I am happy to merge a PR adding it to the list (assuming it's active), even if we end up doing it before the newer refactor PR https://github.com/kubeflow/website/pull/3440 gets merged.

**Pull request closed without merging**
