### PR TITLE
rename getting started to fix broken link

### LINKED ISSUE #2634: Key link broken!
Master branch getting started broken link:
https://master.kubeflow.org/docs/started/getting-started/ 

cc @thesuperzapper

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Fixes #2634

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
[URGENT] - @castrojo @thesuperzapper I need a LGTM here to merge this. The title change broke the master branch (glad we are not pointing to it yet!)

**Comment by RFMVasconcelos** [comment]
Thank you @DavidSpek ! With urgency we did not test the branch and it got broken. Hopefully this fixes it. Testing now

**Comment by Bobgy** [comment]
thanks, makes sense to me.

keep in mind that any proper file rename needs
* fixing existing links
* adding redirect rules

**Comment by thesuperzapper** [comment]
@RFMVasconcelos should we rename this to installing-kubeflow, and add a redirect?

**Pull request merged**
