### PR TITLE
Update AWS documentation to v1.2

### PR DESCRIPTION
**Pull request by PatrickXYS**
On behalf of AWS, update AWS documentation to v1.2 in general

Help https://github.com/kubeflow/website/issues/2322

/cc @8bitmp3 @RFMVasconcelos

### CODE REVIEW

**Review by 8bitmp3 — APPROVED** [review]
/lgtm

assuming changing kfctl AWS YAML files to v1.2 from v1.1 is the only change in this PR

Thanks @PatrickXYS

**Comment by PatrickXYS** [comment]
@8bitmp3 Right, that's minimal change I think

Seems like we need root owner to approve the PR

@Bobgy Can you help approve the PR?

Let me know if you think it's necessary to add OWNERS file in subfolder `layouts`, thus improve our bar of fine grained access.

**Comment by RFMVasconcelos** [comment]
Thank you for this update @PatrickXYS! 

/lgtm

**Comment by Bobgy** [comment]
Yes, please add OWNERS whenever you are updating anything aws specific

**Comment by Bobgy** [comment]
/lgtm
/approve
You can do that in a separate PR

**Pull request merged**
