### PR TITLE
add MiniKF slack channel to community page

### PR DESCRIPTION
**Pull request by shannonbradshaw**
@RFMVasconcelos adding the Slack channel for MiniKF to the community page to make it easier for Kubeflow users to find help on MiniKF when they need it.

Did not want to place this at the top of the list so I placed it in alphabetical order by "MiniKF." Happy to label this as "MiniKF (Arrikto)" instead of "Arrikto MiniKF"

### CODE REVIEW

**Comment by shannonbradshaw** [comment]
@berndverst @Jeffwan @RFMVasconcelos would you mind taking a look at this? I'd like to make sure community members can find there way to help with questions as they try out Kubeflow.

**Comment by RFMVasconcelos** [comment]
I believe this would make MiniKF the only distribution channel added to the list.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos @shannonbradshaw as proposed in https://github.com/kubeflow/website/issues/2807, we are planning to remove the `About / Community` page and replace it with new pages that are more specific:
 - `Kubeflow Slack`: a page which describes (and provides an invite to) the official Kubeflow Slack
 - `Kubeflow Mailing List`: a page which describes (and links to) the [kubeflow-dicsuss](https://groups.google.com/g/kubeflow-discuss) mailing list
 - `Kubeflow Blog`: a page which describes (and links to) the [offical Kubeflow blog](https://blog.kubeflow.org/)
 - `Kubeflow Working Groups`: a page which lists and describes the Kubeflow Working Groups
     - possibly links to the [kubeflow/community](https://github.com/kubeflow/community/tree/master/wg-automl) pages 
     - possibly include links to calendars for meetings

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@Arhell please stop drive-by `/lgtm`ing PRs.

**Comment by thesuperzapper** [comment]
After https://github.com/kubeflow/website/pull/3007 the community page has been rewritten.

Furthermore, as there are no other distributions in the "called out" slack channels, I am closing this issue.

/close

**Comment by shannonbradshaw** [comment]
@thesuperzapper please don't make unilateral choices such as closing a PR. A better approach, IMO, would be to ping signaling that you believe it would make sense to close and provide a last opportunity for some discussion.

**Pull request closed without merging**
