### PR TITLE
Display Kubeflow logo on mobile

### LINKED ISSUE #409: Kubeflow logo should appear on mobile too
The Kubeflow logo currently does not appear on mobile devices - we show just the name "Kubeflow". It'd be nice to get the logo working on mobile too.

See this file:
https://github.com/kubeflow/website/blob/master/assets/scss/_nav.scss#L45

### PR DESCRIPTION
**Pull request by mk-nickyang**
Fixes #409

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/417)

### CODE REVIEW

**Comment by mk-nickyang** [comment]
@sarahmaddox I just double checked and the logo does appear for me. Maybe inspect the`<span class="navbar-logo">` element and see if it still has the `display: none;` applied? If it does, it might mean the scss code not being updated for some reasons

[Screenshot from Gyazo](https://gyazo.com/cb30b64d9db5f602b5394b57e7b29329)

**Comment by sarahmaddox** [comment]
@mk-nickyang The element does have `display: none;` applied, and if I remove `display: none;` using dev tools, the logo appears in the middle of the display. So yes, for some reason the new CSS isn't being applied. Does it work for you from the Netlify preview of your PR? That is, from https://deploy-preview-417--competent-brattain-de2d6d.netlify.com/ ?

**Comment by mk-nickyang** [comment]
@sarahmaddox The Netlify preview doesn't work for me either.
When I looked at the `public/index.html`, the css path is `/scss/main.min.32ae9592885aeb29af4eac34d4189bb34fe1f0b034b56b4a12f2f8110436f894.css`. Then I went to this min css file, I couldn't find the updated css. But I can find the updated css in `public/scss/main.css`. So I guess the css compressing went wrong?

PS: I'm still figuring how do we update the min css file

**Comment by sarahmaddox** [comment]
When I originally started updating the CSS a few months ago, I had a similar problem. I found that I needed to install PostCSS (`npm install -D --save autoprefixer` and `npm install -D --save postcss-cli`) before building the site and checking in the resources folder. Could it be that you don't have those two libraries installed? I found that things built OK locally but not in the Netlify preview.

**Comment by mk-nickyang** [comment]
@sarahmaddox Yes, I just realised that too. Just pushed the fix, should be good now

**Comment by nikhil-koul** [comment]
Hi @mk-nickyang @sarahmaddox , Could you please guide me how to customize kubeflow logo in the UI?

**Comment by sarahmaddox** [comment]
Hallo @nikhil-koul I'm sorry, I can't help here. It's a long time since I've worked on Kubeflow. Good luck with making this change!

**Comment by nikhil-koul** [comment]
> Hallo @nikhil-koul I'm sorry, I can't help here. It's a long time since I've worked on Kubeflow. Good luck with making this change!

Sure @sarahmaddox

**Pull request merged**
