### PR TITLE
Resolved typos

### PR DESCRIPTION
**Pull request by rlenferink**
Resolved a set of typos.

/assign @abhi-g

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/665)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign
/ok-to-test
/lgtm
/approve

Thank you!

**Comment by sarahmaddox** [comment]
@rlenferink Thanks for this PR! It has some conflicts that need resolving before it will merge.

**Comment by rlenferink** [comment]
@sarahmaddox Thanks for having a look. Merge conflicts should be resolved now.

**Pull request merged**
