### PR TITLE
Resolves #3809

### LINKED ISSUE #3809: Fix broken links in Central Dashboard
[Now that we have Checklinks enabled in Netlify](https://github.com/kubeflow/website/pull/3763), we can fix the existing broken links we have on our TODO list.

1. Remove Central Dashboard links from [Checklinks TODO list](https://github.com/kubeflow/website/blob/e1eb76b4facca9562445a63c14bbe30b7003b5c3/netlify.toml#L12).
2. Fix links [reported in Netlify deployment log](https://github.com/kubeflow/website/assets/11776454/01cf5cf0-3d8a-49dd-b32e-89506c4a71d9).

https://github.com/kubeflow/website/pull/3807 can be used as a reference.

cc @kimwnasptd @thesuperzapper

### PR DESCRIPTION
**Pull request by varodrig**
Resolves #3809

### CODE REVIEW

**Comment by varodrig** [comment]
After creating this PR, I noticed that there's another one in progress #3830, but it seems it's missing the redirect file.  I tested this locally, let me know if you want me to run any other tests.

**Review by thesuperzapper — CHANGES_REQUESTED** [review]
Please never update any lines in the redirects file, otherwise you will create 404s.

If you move a page (not what you are doing in this PR) please ADD a line to the redirects file.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by thesuperzapper** [comment]
As the redirect file should not be updated, I am going to close this.

For reference, the purpose of the redirect file is to be a catalog of moved pages, so all old links to the website end up on the current page (even if the pages have been moved multiple times, so redirects point to other redirects).

/close

**Pull request closed without merging**
