### PR TITLE
Updated legal info due to migration from CLA to DCO

### PR DESCRIPTION
**Pull request by hbelmiro**
This PR depends on https://github.com/kubeflow/community/pull/703.

The Legal text is based on [Argo Project](https://github.com/argoproj/argoproj/blob/main/community/CONTRIBUTING.md#legal).

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
cc @kubeflow/kubeflow-steering-committee

**Comment by diegolovison** [comment]
It can be closed in favor of https://github.com/kubeflow/community/pull/703

**Comment by terrytangyuan** [comment]
Can you address the comments above?

**Comment by hbelmiro** [comment]
Duplicated info removed.
Can you please take a second look, @terrytangyuan and @diegolovison?

**Pull request merged**
