### PR TITLE
Add CNCF logo and trademark guidelines

### PR DESCRIPTION
**Pull request by annajung**
Part of https://github.com/cncf/toc/issues/1139

> Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).

- Add "We are a Cloud Native Computing Foundation incubation project" with CNCF logo
- Update footer to include CNCF trademark guidelines

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by annajung** [comment]
deploy preview: https://deploy-preview-3621--competent-brattain-de2d6d.netlify.app/ (scroll to the bottom of the main page)

**Comment by annajung** [comment]
cc @zijianjoy @thesuperzapper to review, let me know if any style/formatting needs to change. Thanks!

**Comment by thesuperzapper** [comment]
@annajung sorry to take your PR, but I started reviewing it, and it was just easier to make a separate PR with the style changes. 

Please review: https://github.com/kubeflow/website/pull/3622

I also updated the homepage cards, because they were very out of date.

Also, as the CNCF guidelines say “We are a Cloud Native Computing Foundation project.” not the "incubating" part.

**Review by Arhell — COMMENTED** [review]
Here I would suggest using a responsive image, that is, width 100% max-width 600px
\+ use svg
https://www.cncf.io/wp-content/uploads/2023/04/cncf-main-site-logo.svg

**Comment by annajung** [comment]
Closing this in favor of https://github.com/kubeflow/website/pull/3622

/close

**Pull request closed without merging**
