### PR TITLE
Remove outdated banner for Katib docs

### PR DESCRIPTION
**Pull request by andreyvelich**
All Katib docs should be up to date for 1.1 release from 11th of June, see this: https://github.com/kubeflow/katib/issues/1211.

/cc @gaocegege @johnugeorge @jlewi

### CODE REVIEW

**Comment by jlewi** [comment]
@andreyvelich @gaocegege Looks like you guys need an OWNERs file so you can approve your changes.

**Comment by andreyvelich** [comment]
@jlewi We have already created OWNERS file for `hyperparameter-tuning` section: https://github.com/kubeflow/website/blob/master/content/en/docs/components/hyperparameter-tuning/OWNERS.
This PR also makes changes for `reference`.
I created PR to add OWNERS file there:  https://github.com/kubeflow/website/pull/2092

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge We need to get lgtm on this PR again.

**Pull request merged**
