### PR TITLE
Added integrations section, including Rok for data management

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/1659

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @jbottum 

@jbottum Please would you review this PR or assign another person for review. I've included the words from the above-linked doc, and I've also added an image showing the **Snapshot Store** option in the UI. Let me know if you'd prefer no image, or a different image.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1855--competent-brattain-de2d6d.netlify.com/docs/other-guides/integrations/data-management/

**Comment by jbottum** [comment]
@cspavlou Hi Chris, Can you please help on this PR review?  Thanks!

**Comment by jbottum** [comment]
@sarahmaddox @cspavlou  I spoke to Constantinos, LGTM

**Comment by sarahmaddox** [comment]
Thanks @jbottum @cspavlou @cvenets can one of you mark the PR as LGTM (type `/lgtm` on a line all by itself)? I can't LGTM my own PR, though I can approve it once someone has added the LGTM.

**Comment by cvenets** [comment]
Hello @sarahmaddox, unfortunately I'm not a collaborator, so I don't have the right privileges, and thus got the error:

`changing LGTM is restricted to collaborators`

**Comment by sarahmaddox** [comment]
Oh dear, thanks @cvenets. It's possible that you're now a collaborator, after adding a comment, but I'm not sure about the definition of collaborator in this context.

/assign @janeman98 

@janeman98 Would you be able to add an LGTM, based on the above approval from the Arrikto team?

**Comment by sarahmaddox** [comment]
Thanks @janeman98!
/approve

**Pull request merged**
