### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by jbottum**
Multi-user isolation has evolved in the last few releases.   These updates reflect the changes and updated related content.

### CODE REVIEW

**Comment by jbottum** [comment]
@cvenets @kimwnasptd I have proposed these changes to multi-user isolation and would appreciate your review and improvements.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you for this PR @jbottum ! 

/lgtm
/approve

**Comment by jbottum** [comment]
@RFMVasconcelos we need to review this before merging.   we should revert back to the prior doc

**Comment by RFMVasconcelos** [comment]
Oh, apologies @jbottum! 

I did a quick review, and since @terrytangyuan had also reviewed and LGTM - I thought we were ready to merge. 

Is there any quick change that we need to do? Can we make that change in a new PR?

**Comment by yhwang** [comment]
the doc looks good to me too! thanks for providing these information.

**Comment by jbottum** [comment]
@RFMVasconcelos @yhwang thanks for reviewing.   I guess we can leave it up based on the reviews.  If others find issues, we modify.

**Pull request merged**
