### PR TITLE
KFP Doc fix and add to owner

### PR DESCRIPTION
**Pull request by rmgogogo**
1. correct email address
2. add to owner
3. correct old version

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1628)

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm
@sarahmaddox for more review

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/1627

**Comment by sarahmaddox** [comment]
/assign @joeliedtke 

I've assigned this to @joeliedtke for review and approval, as he's the KFP tech writing lead.

**Comment by joeliedtke** [comment]
This change can be previewed at:
https://deploy-preview-1628--competent-brattain-de2d6d.netlify.com/docs/pipelines/installation/overview/
https://deploy-preview-1628--competent-brattain-de2d6d.netlify.com/docs/pipelines/installation/standalone-deployment/

**Pull request merged**
