### PR TITLE
Create an OWNERS file with approvers and reviewers for Kubeflow Azure docs

### PR DESCRIPTION
**Pull request by 8bitmp3**
This PR creates an OWNERS file with approvers and reviewers for Kubeflow Azure docs.

It should help with the Issue and PR review process.

cc @aronchick (approver), @sudivate (reviewer) - let me know what you think. Should we add anyone else?

/assign @aronchick

### CODE REVIEW

**Comment by sudivate** [comment]
@8bitmp3  please add @eedorenko to the list as well

**Comment by 8bitmp3** [comment]
Ok @sudivate! I've just added @eedorenko as a second approver (just in case). Let me know what else I can help with

**Comment by 8bitmp3** [comment]
@aronchick PTAL Thank you! We have an Azure doc PR that can benefit from this OWNERS file :)

**Comment by sudivate** [comment]
@8bitmp3  any update on this is  #2196  blocked due to this?

**Comment by 8bitmp3** [comment]
@aronchick @eedorenko Can you please take a look?

cc @Bobgy Do you know if you can assist here? If we get this done, we can help this Azure-related PR https://github.com/kubeflow/website/pull/2196 Thank you!

**Comment by eedorenko** [comment]
/lgtm
/approve

Let's get it merged!

**Comment by Bobgy** [comment]
Sorry, I'm just back from vacation.
/lgtm
/approve

**Pull request merged**
