### PR TITLE
Update output-artifact.md w/ Working Link

### PR DESCRIPTION
**Pull request by bobuel**
Link to "output viewers" is broken

### CODE REVIEW

**Comment by bobuel** [comment]
@googlebot I signed it!

**Review by Arhell — COMMENTED** [review]
/assign @RFMVasconcelos

**Comment by zijianjoy** [comment]
/approve

Thank you for the changes!

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos can you please approve this?

**Comment by zijianjoy** [comment]
Manually added approved label.

**Pull request merged**
