### PR TITLE
Update KFP latest version and stability level

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @8bitmp3 @rmgogogo @jlewi 
EDIT: preview: https://deploy-preview-2204--competent-brattain-de2d6d.netlify.app/docs/reference/version-policy/

### CODE REVIEW

**Comment by Bobgy** [comment]
How can I ask other app owners to update their status too?

**Comment by 8bitmp3** [comment]
@Bobgy I began looking at the OWNERS in reach of the repos that is not KFP. Here's a list of folks excluding @jlewi:

1. Chainer operator: https://github.com/kubeflow/chainer-operator - https://github.com/kubeflow/chainer-operator/blob/master/OWNERS

> approvers:
>   -  everpeace
>   - disktnk
>  
> reviewers:
>   - gaocegege

2. Feature store: Feast https://github.com/feast-dev/feast - https://github.com/feast-dev/feast/blob/master/OWNERS

> approvers:
>   - davidheryanto
>   - khorshuheng
>   - pyalex
>   - woop
>   - zhilingc
> reviewers:
>   - ches
>   - davidheryanto
>   - khorshuheng
>   - pyalex
>   - woop
>   - zhilingc

3. Hyperparameter tuning: Katib https://github.com/kubeflow/katib - https://github.com/kubeflow/katib/blob/master/OWNERS

> approvers:
>     - gaocegege
>     - hougangliu
>     - johnugeorge
>     - andreyvelich
> reviewers:
>     - sperlingxx
>     - c-bata

4. KFServing: https://github.com/kubeflow/kfserving/blob/master/OWNERS

> approvers:
>   - ellistarn
>   - yuzisun
>   - cliveseldon
>   - animeshsingh
>   - rakelkar
> reviewers:
>   - iamlovingit
>   - ifilonenko
>   - jinchihe
>   - salanki
>   - tomcli
>   - pugangxa
>   - yuzliu

5. https://github.com/kubeflow/metadata/blob/master/OWNERS
6. https://github.com/kubeflow/mpi-operator/blob/master/OWNERS
7. https://github.com/kubeflow/mxnet-operator/blob/master/OWNERS
8. https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/OWNERS
9. https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/OWNERS
10. https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/OWNERS
11. https://github.com/kubeflow/pytorch-operator/blob/master/OWNERS
12. https://github.com/SeldonIO/seldon-core/blob/master/OWNERS
13. https://github.com/kubeflow/tf-operator/blob/master/OWNERS

cc @RFMVasconcelos fyi

**Comment by Bobgy** [comment]
Thank you @8bitmp3!
Shall we merge this first?
Because I don't think we can gather everyone here quickly. I'll create a new issue for other components.

**Comment by 8bitmp3** [comment]
> Thank you @8bitmp3!
> Shall we merge this first?
> Because I don't think we can gather everyone here quickly. I'll create a new issue for other components.
 
@Bobgy Agree 💯 Thank you!

**Pull request merged**
