### PR TITLE
Renaming tf-hub to jupyterhub

### PR DESCRIPTION
**Pull request by pvsousalima**
Follow up updates in regards to https://github.com/kubeflow/kubeflow/pull/1410, changing tf-hub to jupyterhub and tf-hub-lb to jupyterhub-lb

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/243)

### CODE REVIEW

**Comment by jlewi** [comment]
/ok-to-test
Looks like this got a little out of date.
Would you bind rebasing?

**Comment by pvsousalima** [comment]
No problem @jlewi I will rebase! :)

**Comment by jlewi** [comment]
@pvsousalima Any chance you could take a look at this?

**Comment by pvsousalima** [comment]
Yes @jlewi I can patch it tonight

**Comment by pvsousalima** [comment]
hey @jlewi much of the references have been removed, I do not see any reference at the master branch in regards of tf-hub neither tf-hub-lb, it seems like they have been removed out of the documentation, is that right?

**Comment by abhi-g** [comment]
Looks like you are right. Those references are gone now.

**Comment by jlewi** [comment]
So does that mean we should close this PR?

**Comment by abhi-g** [comment]
yes. And done.

**Pull request closed without merging**
