### PR TITLE
Update Azure Deployment Docs for KF 1.2

### PR DESCRIPTION
**Pull request by berndverst**
Updates the deploy instructions for KF 1.2 on Azure

Also addresses some config file confusion, #2398

### CODE REVIEW

**Comment by berndverst** [comment]
FYI @aronchick

**Comment by berndverst** [comment]
@joeliedtke I'm the main Azure contributor by the way. Just need this merged to address some major problems in the Azure docs at present causing lots of confusion.
Also the v1.2 docs change didn't update some of our partials/shortcodes :(

**Comment by PatrickXYS** [comment]
I can help add lgtm tag in case you can't find response in time

/lgtm

**Comment by berndverst** [comment]
/assign @Bobgy

@Bobgy could you help approve this Azure docs change so I can merge it? Trying to get this out quickly to minimize issues being filed.

**Comment by berndverst** [comment]
FYI One note on the strange `.cache/` instructions -- definitely planning to refactor the manifests to make this unnecessary. Just documenting what people need to do to make it work todyay.

**Comment by Bobgy** [comment]
As a follow up, can you add OWNERS for azure folders, so that you can approve them by yourself later?

/lgtm
/approve

**Pull request merged**
