### PR TITLE
Update IP from `xip` to `nip`

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
cc @DomFleischmann

### CODE REVIEW

**Review by DomFleischmann — CHANGES_REQUESTED** [review]
There is another mention of `xip.io` in line 64

**Comment by RFMVasconcelos** [comment]
Nice catch! Fixed

**Comment by RFMVasconcelos** [comment]
The tests are failing and automation to relaunch seems not to be working.. 

I'll make another PR. 

@Bobgy @joeliedtke do you know if we should fix the test triggers? Or is it working and I am simply not finding the right command? :)

**Pull request closed without merging**
