### PR TITLE
Fix broken link to release page

### PR DESCRIPTION
**Pull request by janeman98**
Currently, in https://www.kubeflow.org/docs/ibm/install-kubeflow/

**Kubeflow installation**
Run the following commands to set up and deploy Kubeflow.
1. Download the kfctl v1.0-rc.4 release from the [Kubeflow releases page](https://github.com/kubeflow/kubeflow/releases/tag/v1.0-rc.4 ).

Follow Kubeflow release page -> 404

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1692)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign

Thanks @janeman98!
/lgtm
/approve

**Comment by janeman98** [comment]
Thanks @sarahmaddox ! I thought you are flying back home today? Anyway, Happy Valentines day!

**Comment by sarahmaddox** [comment]
:) I'm at the airport! Happy Valentines day to you too!

**Pull request merged**
