### PR TITLE
Update the version for IKS

### PR DESCRIPTION
**Pull request by yhwang**
Update the version for IKS to v1.6

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by yhwang** [comment]
the retest command doesn't work. need to figure out how to rerun those checks.

**Comment by Tomcli** [comment]
probably need to push a new commit, netlify tests are not part of the tide.

**Comment by yhwang** [comment]
@Tomcli just updated the description in the commit. those checks are good now

**Pull request merged**
