### PR TITLE
Upgrade hugo version to v0.51

### PR DESCRIPTION
**Pull request by abhi-g**
upgrading hugo to allow for docsy theme to function..

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/308)

### CODE REVIEW

**Comment by abhi-g** [comment]
fixes #304

**Comment by abhi-g** [comment]
This is all I changed so far and it seems to pass the checks. Looking at your PR, the error from netlify deployment was:
11:42:26 AM: Building sites …
11:42:26 AM: ERROR 2018/11/23 19:42:26 error: failed to transform resource: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version
11:42:27 AM: Total in 272 ms

So, either my change of version itself is okay, but mixed with your changes to docsy theme, might still fail?

Based on https://gohugo.io/hosting-and-deployment/hosting-on-netlify/ I assumed this is all I needed to do.

@richardsliu Do you know if upgrading the version of hugo in this config is enough?

**Comment by abhi-g** [comment]
Also from your PR's log @sarahmaddox 
"11:42:25 AM: Installing Hugo 0.51" before it failed.
So I am assuming this deployment will fail as well with the docsy theme. We might need "0.51/extended". Not sure yet how to get it with netlify.

**Comment by sarahmaddox** [comment]
I think the error is due to the fact that we need the *extended* version of Hugo, which supports SCSS.

**Comment by abhi-g** [comment]
haha, was worth a try. Doesn't work by just adding /extended in there.

**Comment by abhi-g** [comment]
sounds good.

**Pull request closed without merging**
