### PR TITLE
Add makefile.

### PR DESCRIPTION
**Pull request by irvifa**
This will make build and test locally easier.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1408)

Maintenance plan:

Update `HUGO_VERSION` in Makefile and build the Dockerimage again if we want to use different version of hugo.

### CODE REVIEW

**Comment by sarahmaddox** [comment]
@irvifa Please would you explain the reason for this PR in more detail. 

If you're proposing a new way of building the website locally (that is, different from what's in the README) please would you include some documentation in the PR. Prerequisites, and how to use the MAKE file.

It will also be good to include a maintenance plan - what needs to change when the website is updated to different versions.

Note that the process needs testing before we can merge this PR.

**Comment by irvifa** [comment]
@sarahmaddox can you explain how the test works for the makefile? Thanks!

**Comment by sarahmaddox** [comment]
@irvifa We'll need to manually test the process after you've documented it.

**Comment by irvifa** [comment]
@sarahmaddox okay i’ll update the readme and how we maintain it. Thanks for the advice..

**Comment by irvifa** [comment]
@sarahmaddox I added the how to's in the `README.md` and plan of its maintenance.

**Comment by abhi-g** [comment]
I don't think we need to complicate the website preview any more than it needs to be. The current prices is fairly straightforward. Either run hugo locally to create a preview, or create a PR and the current repo setup automatically creates a preview for you.

If you'd still like your Docker setup, I suggest you commit to your own GitHub repository.

**Pull request closed without merging**
