### PR TITLE
Upload TFJOB Using GPUs example output & Job Scheduling API verison

### PR DESCRIPTION
**Pull request by yylin1**
I want to Upload `TFJOB using GPU example and outout, and Job Scheduling  API verison.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/458)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @amygdala 

Thanks, this looks great! 
@amygdala I know you're looking at this page already. Please would you verify this PR?

**Comment by yylin1** [comment]
Hi @sarahmaddox  this PR be merged? or need to test ?

**Comment by sarahmaddox** [comment]
Hallo @yylin1 Thanks for this PR. I've assigned @amygdala to review it. She's planning to look at it soon.

**Comment by amygdala** [comment]
The yaml specifies `--batch_size=32` but the status output specifies `--batch_size=4` --seems they should be consistent?

**Comment by yylin1** [comment]
Hi @amsaha , they should consistent. My testing run `--batch_size=4`, so I change `--batch_size=32` match the original example, should user   know setting `batch sizes`.

**Comment by amygdala** [comment]
I see that on line 303: https://github.com/kubeflow/website/pull/458/files#diff-0f7b82550dec419c0244d601d2b1a38cR303 batch of 32 is used, and here: https://github.com/kubeflow/website/pull/458/files#diff-0f7b82550dec419c0244d601d2b1a38cR362 batch of size 4 is used.

**Comment by yylin1** [comment]
Thanks, @amygdala You can verify this PR again.

**Comment by jlewi** [comment]
Looks like @sarahmaddox and @amygdala have it covered
/unassign @jlewi 
/unassign @IronPan

**Pull request merged**
