### PR TITLE
Added relative link to new AWS Pipelines page for 1.4 branch

### PR DESCRIPTION
**Pull request by judyheflin**
Fixed broken AWS Pipelines link for Kubeflow website 1.4 branch

### CODE REVIEW

**Comment by surajkota** [comment]
@Arhell can you take a look, same as #3176

**Comment by surajkota** [comment]
@Arhell @Ark-kun review please

**Comment by surajkota** [comment]
@chensun @neuromage ping tiny PR to fix a broken link. Please take a look

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by surajkota** [comment]
@Arhell please merge this PR

**Comment by Arhell** [comment]
> @Arhell PR is ready to merge

https://github.com/kubeflow/website/pull/3189#issuecomment-1064501999

**Comment by surajkota** [comment]
@shannonbradshaw can you do another lgtm. not sure why it did not work

**Comment by surajkota** [comment]
@Bobgy, @IronPan, @neuromage, @chensun can one of you approve this tiny PR?

**Review by goswamig — APPROVED** [review]

**Comment by hbelmiro** [comment]
Closing due to inactivity.

/close

**Pull request closed without merging**
