### PR TITLE
Pin the version of kustomize, v4 is not supported.

### PR DESCRIPTION
**Pull request by drPytho**
There are issues installing Kubeflow with version v4. 

Note: 
https://github.com/kubeflow/website/issues/2570
https://github.com/kubeflow/kubeflow/issues/5755

### CODE REVIEW

**Comment by thesuperzapper** [comment]
Can a @kubeflow/wg-manifests-leads please review, this is a simple change.

**Comment by thesuperzapper** [comment]
Seems like https://github.com/kubeflow/website/pull/2542 is an alternative to this

**Comment by yanniszark** [comment]
The contract of the manifests wg is to use version `3.2.0`, as in previous versions:
https://github.com/kubeflow/manifests/tree/v1.3.0-rc.0#readme

This is a link to the `3.2.0` version:
https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0

Can we change the PR to reflect that? Since those are the GKE distribution docs, I believe the appropriate owners (cc @Bobgy @zijianjoy) should give the final wording they want to adopt.

**Comment by drPytho** [comment]
Added reference to the manifest repo in case it updates the source of truth is available. 

Also defaulted to install 3.2.0 from https://github.com/kubeflow/website/pull/2542.

**Comment by Bobgy** [comment]
Thank you!
/LGTM
/Approve

Because this is GCP specific

**Pull request merged**
