### PR TITLE
doc: Update the document of Feast feature store.

### PR DESCRIPTION
**Pull request by shuchu**
- Update the obsoleted links
- Remove one line about upgrading Feast from 0.9 to 0.12.  The version numbers are too old. The latest version is 0.37.1.

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

@shuchu I just don't see this change:
> Remove one line about upgrading Feast from 0.9 to 0.12. The version numbers are too old. The latest version is 0.37.1.

**Comment by shuchu** [comment]
> /lgtm
> 
> @shuchu I just don't see this change:
> 
> > Remove one line about upgrading Feast from 0.9 to 0.12. The version numbers are too old. The latest version is 0.37.1.

hi @hbelmiro   I removed the Line 33 :)

**Comment by hbelmiro** [comment]
@shuchu 
> hi @hbelmiro I removed the Line 33 :)

Oh, man. I think I'm getting blind 🥲

**Comment by shuchu** [comment]
its been a while, is it good to merge now?  :)

**Comment by hbelmiro** [comment]
@andreyvelich can we get this merged?

**Review by andreyvelich — COMMENTED** [review]
Thank you for this.
/assign @franciscojavierarceo to review FEAST changes.

**Review by franciscojavierarceo — APPROVED** [review]
Nice thanks for this @shuchu!

**Pull request merged**
