### PR TITLE
Add OWNERs for about section

### PR DESCRIPTION
**Pull request by andreyvelich**
See comment: https://github.com/kubeflow/website/pull/2120#issuecomment-672888785.

@gaocegege @terrytangyuan @johnugeorge @Jeffwan You wouldn't mind to be in the OWNERs file for about section?

/cc @jlewi

### CODE REVIEW

**Comment by Jeffwan** [comment]
This is great. Would love to help. The outdated banner on about page looks uncomfortable.

**Comment by andreyvelich** [comment]
Agree @Jeffwan, I created PR to fix it: https://github.com/kubeflow/website/pull/2128.

**Comment by 8bitmp3** [comment]
Hey @andreyvelich, thanks a million! 

If you want, you can add `8bitmp3` as a reviewer. @RFMVasconcelos do you want to have your GH handle added to the list of reviewers? @andreyvelich - we have recently joined KF.

IMHO, it may be best to have at least two here.

**Comment by RFMVasconcelos** [comment]
Hi @8bitmp3, I'm super happy to be part of this project and want to make the docs simple for newcomers, so I'm happy to become a reviewer 🚀

**Comment by andreyvelich** [comment]
Sure @8bitmp3.
I think it is better to add you and @RFMVasconcelos as approvers under `/about` section since you are already reviewer in the root OWNERS file: https://github.com/kubeflow/website/blob/master/OWNERS#L7.

What do you think @8bitmp3 @RFMVasconcelos @jlewi ?

**Comment by 8bitmp3** [comment]
@andreyvelich as you wish 👍

**Comment by andreyvelich** [comment]
@RFMVasconcelos I think I can't add you in the OWNERS file unless you are not in Kubeflow org members.
You should create PR to join the organisation.

**Comment by jlewi** [comment]
@andreyvelich I would suggest getting this PR merged ASAP in order to "bootstrap" an initial set of approvers who can then approve adding additional folks.  So I would suggest removing @RFMVasconcelos or anyone else who is not in the org.

/lgtm
/approve

**Comment by andreyvelich** [comment]
Sure @jlewi, done.

**Comment by RFMVasconcelos** [comment]
@andreyvelich added myself to the org here -> https://github.com/kubeflow/internal-acls/pull/315

**Comment by andreyvelich** [comment]
> @andreyvelich added myself to the org here -> [kubeflow/internal-acls#315](https://github.com/kubeflow/internal-acls/pull/315)

Thanks @RFMVasconcelos, can we approve it @jlewi ?

**Comment by jlewi** [comment]
/lgtm

@animeshsingh or @rmgogogo could one of you approve this please?

**Comment by RFMVasconcelos** [comment]
@andreyvelich @jlewi following the community meeting:

- Should I create a PR and add also an OWNERs file for the "Getting Started" section?
- If so, who should I add? I'm keen to review docs on that front.

Sorry for the delay on becoming a member. I am happy to take on "Getting Started" since @8bitmp3 is on "About".

**Comment by andreyvelich** [comment]
@RFMVasconcelos Sure, just create an additional PR to add yourself in approvers list.
Thank you very much for helping us!

**Pull request merged**
