### PR TITLE
Fixed indentation that broke numbering on CLI deployment page.

### PR DESCRIPTION
**Pull request by chupman**
Indentation on code block was off by one space. Verified fix by running Hugo server locally.
fixes kubeflow/kubeflow#3266

Signed-off-by: Chris Hupman <chupman@us.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/709)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-709--competent-brattain-de2d6d.netlify.com/docs/gke/deploy/deploy-cli/

**Comment by sarahmaddox** [comment]
Thanks @chupman This looks great! LGTM once the CLA is signed.

Please would you follow the instruction from the googlebot in an earlier comment, to sign the CLA. Then come back here and add a comment. That will prompt the rerun of the CLA test.

**Comment by chupman** [comment]
Thanks. I'm working on getting added to the IBM CCLA now.

**Comment by chupman** [comment]
CLA should be good now

**Pull request merged**
