### PR TITLE
Small fix - Remove non-rendered note

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
cc @evilnick

### CODE REVIEW

**Review by evilnick — COMMENTED** [review]
I think the style in these docs for such notes is to use the site shortcode. For example:

```

{{% alert color="warning" %}}
note content 
{{% /alert %}}
```

**Comment by RFMVasconcelos** [comment]
Thank you for the review and suggestion @evilnick ! Can you please lgtm?

**Comment by evilnick** [comment]
I'm really sorry - now that the warning note is rendering properly, it seems that the style for <code> inside a warning is different. I will file an issue on that because it is barely readable.

Screenshot from 2021-04-29 13-04-19

For now I would just remove the backticks around those terms.

**Comment by evilnick** [comment]
Added issue - https://github.com/kubeflow/website/issues/2677

**Comment by RFMVasconcelos** [comment]
Fixed!

**Comment by evilnick** [comment]
@RFMVasconcelos did we ever figure out why these tests were failing? doesn't look like it is anything to do with the content of this PR

**Comment by RFMVasconcelos** [comment]
@evilnick no idea why the tests are falling and it appears we are not being able to trigger retests. #2698 replaces this PR.

**Pull request closed without merging**
