### PR TITLE
Update Canonical distro listings

### PR DESCRIPTION
**Pull request by grobbie**
* remove microk8s add-on
* correct naming and description of Charmed Kubeflow distro
* correct installation instructions Charmed Kubeflow distro
* revise owners and approvers

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
Thank you for this contribution @grobbie and for the revision of owners - removing myself. 

It has been a pleasure to be part of this project!

/lgtm
/approve

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request merged**
