### PR TITLE
Add request logging doc for TF serving

### PR DESCRIPTION
**Pull request by lluunn**
From https://github.com/kubeflow/kubeflow/blob/master/components/k8s-model-server/request-logging.md

/cc @jlewi

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/125)

### CODE REVIEW

**Comment by jlewi** [comment]
@lluunn Not sure why netilify preview failed; I didn't see an error; can you push a trivial change to see if that triggers a rerun of the preview.

**Comment by lluunn** [comment]
@jlewi test passed now

**Pull request merged**
