### PR TITLE
add links to install tools, getting started

### PR DESCRIPTION
**Pull request by kbhawkey**
- add links to install tools, getting started
- remove kfctl release page from reference
- See issue #881

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/893)

### CODE REVIEW

**Comment by kbhawkey** [comment]
**Note:** Added links to three tools on the main `Getting Started` page. Instead of the links, could add a new page to cover install and setup of the cli tools. The deployment pages repeat the `kfctl` installation instructions.

**Comment by kbhawkey** [comment]
Preview:
https://deploy-preview-893--competent-brattain-de2d6d.netlify.com/docs/started/getting-started/

**Comment by joeliedtke** [comment]
The redirect looks good to me.

**Comment by joeliedtke** [comment]
/hold

Hold for technical review.

**Comment by sarahmaddox** [comment]
/hold cancel

Thanks @joeliedtke and @kbhawkey! The redirect works:
https://deploy-preview-893--competent-brattain-de2d6d.netlify.com/docs/reference/downloads/

/approve

**Pull request merged**
