### PR TITLE
Moved multi-user to KFP v2 docs

### PR DESCRIPTION
**Pull request by hbelmiro**
Resolves: https://github.com/kubeflow/website/issues/3749

cc @chensun

### CODE REVIEW

**Comment by jbottum** [comment]
sure, but I am not sure I understand it.   It looks like just a documentation change.    Have the KFP WG leads commented ?  are they on PTO ?

**Comment by hbelmiro** [comment]
@jbottum this PR changes the `content/en/_redirects`. This file doesn't belong to the pipelines folder. That's why it needs approval from root approvers.

**Comment by hbelmiro** [comment]
/unhold

@terrytangyuan can you also take a look? We need a root approver.

**Comment by hbelmiro** [comment]
@terrytangyuan @jbottum @andreyvelich @james-jwu can one of you guys take a look? We need a root approver.

**Pull request merged**
