### PR TITLE
remove troubleshooting.md

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2766
/assign @RFMVasconcelos

@RFMVasconcelos please check

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you for starting this fix @Arhell! 

TBH I am unsure that a literal link fix helps here, as we'll be pointing people to the generic deployment where they will hardly find what they are looking for if they click. 

@Bobgy do you know if this is still relevant? As it is GCP specific? 

Many thanks!

**Comment by Arhell** [comment]
cc @thesuperzapper

**Comment by Bobgy** [comment]
/lgtm
/approve
Agree to remove, most of the stuff are either outdated or not specific to Kubeflow

**Pull request merged**
