### PR TITLE
update link

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2762

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Can you update all the links at once instead of one PR per link fix?

**Comment by Arhell** [comment]
> Can you update all the links at once instead of one PR per link fix?

I checked all the links on this page, found another one that did not work, corrected it.

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you @Arhell for this fix!! 

/lgtm 
/approve

**Pull request merged**
