### PR TITLE
Added doc URL to 'Create issue' option

### PR DESCRIPTION
**Pull request by sarahmaddox**
Added a site-specific version of the `layouts/partials/page-meta-links.html` file, so that I can add code to inject the page URL into any issue created when the user clicks the **Create issue** option on a doc page. In the file, line 9 is new and file 10 is adjusted to add the `body` of the issue:

```
{{$doc_url := printf "https://www.kubeflow.org%s" .URL }}
{{ $issuesURL := printf "%s/issues/new?title=%s&body=%s" $gh_repo (htmlEscape $.Title) (htmlEscape $doc_url) }}
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/807)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview:
https://deploy-preview-807--competent-brattain-de2d6d.netlify.com/docs/started/getting-started/

Click **Create issue** on the above page (or any page) and check the URL in the body of the new issue.

**Comment by sarahmaddox** [comment]
Fixes https://github.com/kubeflow/website/issues/806

Note that this is a "good enough" fix, in that it hard-codes the domain into the URL. We need a more flexible fix to the Docsy theme, which should cater for different site configurations as mentioned in https://github.com/google/docsy/issues/91

Also as mentioned in the above issue, we need a similar fix for the Feedback widget.

**Comment by abhi-g** [comment]
Good to lear the interesting hugo snippet.

/lgtm
/approve

**Pull request merged**
