### PR TITLE
clean section

### PR DESCRIPTION
**Pull request by Arhell**
update for issue https://github.com/kubeflow/website/issues/2760#issuecomment-881430679

### CODE REVIEW

**Comment by Arhell** [comment]
cc @Bobgy

**Comment by Arhell** [comment]
cc @Bobgy
i deleted a blank page

**Comment by Arhell** [comment]
cc @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
Thank you @Arhell for this PR. 

My apologies on the time to review. LGTM!

/lgtm
/approve

**Pull request merged**
