### PR TITLE
Added a practical description of Kubeflow

### PR DESCRIPTION
**Pull request by sarahmaddox**
At the high level of our docs, we tend to describe our mission rather than giving an overview of how we accomplish that mission.

This PR:
* Updates the "About Kubeflow" page to include a practical description of what Kubeflow is.
* Adds a "Components Overview" page as a handy destination to link to, from the above page and potentially from other pages too.

Fixes issue #183

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/184)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
@aronchick Please would you take a look - have I done Kubeflow justice? This change answers the question, "Yes, but what _is_ Kubeflow?"

**Comment by sarahmaddox** [comment]
For ease of reference, here's the staged doc:
https://deploy-preview-184--competent-brattain-de2d6d.netlify.com/docs/about/kubeflow/

**Comment by aronchick** [comment]
This looks great!

/LGTM

**Pull request merged**
