### PR TITLE
Add link to AutoML WG Slack channel

### PR DESCRIPTION
**Pull request by andreyvelich**
I added link to AutoML WG Slack channel in community page. 
I think it can be useful.

/assign @joeliedtke @8bitmp3

/cc @jlewi @gaocegege @johnugeorge

### CODE REVIEW

**Comment by andreyvelich** [comment]
@jlewi Sure, I will create separate PR to add OWNERs file.

**Comment by 8bitmp3** [comment]
Thank you

/lgtm

**Comment by jlewi** [comment]
Looks like this is blocked on the PR updating the OWNERs file so you can approve changes.

**Comment by andreyvelich** [comment]
@8bitmp3 @Jeffwan @jlewi I rebased for the OWNERS file, can you lgtm again, please?

**Pull request merged**
