### PR TITLE
Update to pipelines OWNERS

### PR DESCRIPTION
**Pull request by hbelmiro**
Adding myself as a reviewer to pipelines OWNERS.

@chensun do you suggest any other updates for the pipelines OWNERS?

/assign @andreyvelich @chensun

### CODE REVIEW

**Review by chensun — APPROVED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@hbelmiro I warn you that this will result in you being assigned as a reviewer to literally all PRs they get created on the website (because the other sections OWNERS don't define `reviewers`)

**Comment by hbelmiro** [comment]
Thank you @thesuperzapper.
I removed myself from root.

@rimolive can you take a second look?

**Pull request merged**
