### PR TITLE
fix footer

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubeflow/website/issues/2592

### CODE REVIEW

**Review by jasonliu747 — COMMENTED** [review]
@Arhell thanks for your contribution, could you fix the CI errors?

**Comment by Arhell** [comment]
@jasonliu747  done

**Comment by jasonliu747** [comment]
> @jasonliu747 done
> but my fixes were not applied, this is due to generation, can you tell me how to do this? I can not find

I think it works now.
/LGTM

**Review by RFMVasconcelos — COMMENTED** [review]
This looks good, thank you @Arhell ! 

Please keep in mind that the changes will only be effective once we point the website to the master branch. 

/lgtm
/approve

**Pull request merged**
