### PR TITLE
redirect azure distribution docs to new website

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR redirects the "Kubeflow on Azure" docs to their new external website as part of https://github.com/kubeflow/website/issues/3074

The link to the new website was already added to the "installing kubeflow" guide in PR https://github.com/kubeflow/website/pull/3458

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I have removed the OWNERS file, because none of those people are involved in the project anymore.

I tried adding @mosabami (the Azure employee who seems to be in charge of the new distro), but turns out he was not a member of the Kubeflow org, so I cant. 

But we don't really need an OWNERS file for this single page anyway.

**Comment by thesuperzapper** [comment]
@jbottum @zijianjoy @james-jwu I think this is important to redirect these old docs to the new website.

I am trying to close out https://github.com/kubeflow/website/issues/3074 to make the website actually clear about how to get Kubeflow installed (especially with all the new eyes about to look after the CNCF adoption).

**Comment by thesuperzapper** [comment]
@mosabami can you please take a quick look and LGTM this PR, as it will reduce confusion from users about Kubeflow's support for Azure.

It removes the very outdated Azure docs and redirects them to your new ones at https://azure.github.io/kubeflow-aks/main/.

**Comment by mosabami** [comment]
@thesuperzapper how do I get added to the Kubeflow org?

**Comment by thesuperzapper** [comment]
@mosabami For the purposes of this PR it's not really necessary, given that we are going to be deleting the entire `/docs/distributions/` section of the website, but as you should probably be added to the org, I have raised a PR to do that: https://github.com/kubeflow/internal-acls/pull/611

**Comment by mosabami** [comment]
LGTM

**Comment by mosabami** [comment]
my apologies for the late response here @thesuperzapper  feel free to have it merged. #sign-off

**Comment by thesuperzapper** [comment]
@zijianjoy can you do the approval on this one since @mosabami has LGTM'd it?

**Pull request merged**
