### PR TITLE
Hide upgrade instructions for AI Platform Pipelines managed storage instructions

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @rmgogogo 

before we figure out a more detailed instructions that can make sure there's no user data loss

### CODE REVIEW

**Comment by rmgogogo** [comment]
Maybe you can make the sentence be more user friendly as current it can work. You can point it out that current in-cluster PVC is not deleted but no garentee in the future and we suggest managed.

**Comment by Bobgy** [comment]
> Maybe you can make the sentence be more user friendly as current it can work. You can point it out that current in-cluster PVC is not deleted but no garentee in the future and we suggest managed.

I want to at least confirm with marketplace team we can rely on this for a while first.

**Pull request merged**
