### PR TITLE
Update invitation link to Kubeflow Slack channel

### PR DESCRIPTION
**Pull request by ckadner**
The old invitation link had expired. Thanks to @jlewi who provided this new link.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1802)

### CODE REVIEW

**Comment by ckadner** [comment]
@jlewi

**Comment by sarahmaddox** [comment]
Thanks!
/ok-to-test
/lgtm
/approve

**Comment by ckadner** [comment]
thanks @sarahmaddox

**Comment by ckadner** [comment]
FYI: PR to change the Slack invite link in `kubeflow/examples` docs: https://github.com/kubeflow/examples/pull/769

**Pull request merged**
