### PR TITLE
doc(kfp): update multi-user isolation doc title and supported platforms

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @joeliedtke @8bitmp3

### CODE REVIEW

**Review by 8bitmp3 — CHANGES_REQUESTED** [review]
@Bobgy Hi, what do you think about this proposal: 

`For the latest status... refer to...`

- Adding a definite article "the" (I'm not 100% sure here but I think it's right)
- Replacing "read" with "refer to" for a11y


(Additionally, I'd keep each line at 80 characters max)

WDYT?

Thank you!

**Comment by Bobgy** [comment]
@8bitmp3 Thank you for the suggestions! It does sound better.

> (Additionally, I'd keep each line at 80 characters max)

I don't really want to enforce this, because editing existing paragraphs will incur non-trivial edits to keep the rule.
Do you find it difficult to read in some situations? So far, I've been using VS Code with wrapping enable to edit markdown files and not manually wrapping lines make the whole editing a lot easier.

**Comment by 8bitmp3** [comment]
> (Additionally, I'd keep each line at 80 characters max)
I don't really want to enforce this, because editing existing paragraphs will incur non-trivial edits to keep the rule.
Do you find it difficult to read in some situations? So far, I've been using VS Code with wrapping enabled to edit markdown files. Not manually wrapping lines make the whole editing a lot easier.

@Bobgy Ok! Whatever makes it easier to review for you.

I think some open-source projects, including at Google, have a linter in docs tests that sort of checks for the 80 chart limit, many don't have it so it's not enforced.

Certain IDEs may not have the default setting set to auto-wrap (do the less modern ones with less GUI have them?). So if a user forks the repo and starts working via the CLI, their view may not be the same as ours. the GitHub web UI, VSCode, IDEA and Xcode have done an excellent job at this.

Check this out - https://about.gitlab.com/blog/2016/10/11/wrapping-text/ - to wrap or not to wrap dos and don'ts 🙂

image

**Pull request merged**
