### PR TITLE
Add OWNERS for Getting Started Section

### PR DESCRIPTION
**Pull request by PatrickXYS**
Help solve `Getting Started` section OWNER responsibilities

https://github.com/kubeflow/website/issues/2177

/cc @RFMVasconcelos @8bitmp3

### CODE REVIEW

**Comment by 8bitmp3** [comment]
Cool, thanks @PatrickXYS I'd recommend to have 2 approvers per cloud provider (AWS, GCP, IBM, Azure), so it doesn't get stuck. You may not want someone from another company OKing the docs related to your cloud services 🤷‍♀️ 🤷‍♂️ cc @RFMVasconcelos 

My siggestion is to add the following members, based on the OWNERS files:
- `docs/azure`: maybe @eedorenko and/or @berndverst could join in. @sudivate could join in if no backup is available.
- `docs/aws`: have you spoken to @Jeffwan ? I think think having a backup here would be good.
- `docs/gke`: @8bitmp3 and @joeliedtke should be added for GCP
- `docs/ibm`: @animeshsingh @shawnzhu @Tomcli (at least 2)

Feel free to add me - @8bitmp3 - as a reviewer to check Markdown files (syntax, formatting, etc). 

WDYT? Cheers

**Comment by PatrickXYS** [comment]
I understand your point @8bitmp3 

The reason I haven't make the OWNERs file complicated is: this folder is only for redirection, again, if someone from IBM/GCP would like to help approve any useful PR under this folder related to AWS, I'm happy with that, that proves we work as a community.

In other perspective, I'd like neutral folks to be listed as OWNER in this folder rather than a set of cloud provider's folks, including @8bitmp3  @RFMVasconcelos

**Comment by 8bitmp3** [comment]
@PatrickXYS Understood 👍 I and @RFMVasconcelos probably spend more time on-prem—our heads aren't in the ☁️ as much as yours 😆

**Pull request merged**
