### PR TITLE
Create OWNERS for multi tenancy doc

### PR DESCRIPTION
**Pull request by Bobgy**
/assign @8bitmp3 @yanniszark

### CODE REVIEW

**Comment by Bobgy** [comment]
/approve
Also, are there volunteers as reviewers?

**Comment by yanniszark** [comment]
@Bobgy can you please add me to approvers? I have good experience and am very familiar with multi-twnancy in Kubeflow.

**Comment by Bobgy** [comment]
@yanniszark Thank you for offering help. You can help review and update multi-tenancy docs without being an approver.

With enough commitments, we can consider granting approver.

**Comment by yanniszark** [comment]
No problem!
I thought I would be more useful to people wanting to contribute to these docs if I were an approver.
About previous commitments, I have contributed the kubeflow auth guidelines (https://github.com/kubeflow/community/blob/master/guidelines/auth.md), design around multi-tenancy in KFP as well as the Istio/Dex/AuthService integration.

**Comment by 8bitmp3** [comment]
@Bobgy @yanniszark thank you

You can also add me as a reviewer. 

@RFMVasconcelos - do you want to volunteer?

**Comment by Bobgy** [comment]
@yanniszark I really appreciate your previous contributions to multi-user design.
You can help a lot with reviews/your own PRs already. If you show enough commitments on other type of contributions, I'll be more than happy to grant more permissions.

Thanks @8bitmp3 for offering review too.
I think we can start with this collection and add @RFMVasconcelos when he replies.

/approve

**Comment by RFMVasconcelos** [comment]
@Bobgy @yanniszark thank you for stepping forward! 

@8bitmp3 If you think you need my help I'm happy to be part of it, but I think it looks good in your hands :) Don't want to overcommit and underdeliver :)

**Comment by cvenets** [comment]
@Bobgy 

Can you please elaborate on the following?
"If you show enough commitments on other type of contributions,"

@yanniszark from our team (Arrikto) has already done significant contributions in Kubeflow wrt multi-tenancy, he was the one that initiated the effort for multi-tenancy on KFP, and then Google picked up, and has done multiple contributions on the docs side. He mentioned a few on his previous comment. So, why isn't this enough yet?

I understand that Google tries to retain full control, but long-standing, and committed contributors should be acknowledged at some point. And this doesn't seem to be the case here. We understand that Google tries to get help from non-Google people for reviews/contributions, but these people need to somehow be acknowledged. Asking to be an approver on the docs, doesn't seem to be that disrupting, especially with @yanniszark's past in the Kubeflow community, and multi-tenancy specifically.

@jlewi can probably confirm the above as well for the non-KFP part.

Thank you

**Comment by Bobgy** [comment]
Hi @cvenets,

My point was very simple, there are different types of contributions:
* When you contribute some design, you get ownership for that design.
* When you contribute some code, you get ownership for that code (probably only for independent code area that makes sense).
* When you contribute some documentation, you get ownership for that doc.

As I said, I really appreciate @yanniszark's great efforts on the design, but that doesn't automatically grant extra ownership on code and documentation.
I'm not aware of @yanniszark's past doc contributions to multi-tenancy. Can you list some if I was just missing some context? I was looking at https://github.com/kubeflow/website/pulls?q=is%3Apr+author%3Ayanniszark+is%3Aclosed.
I'd be happy to grant extra permissions if that seems reasonable.

These are my personal understandings.
@jlewi for confirmation, is there any existing guidance for granting OWNERS?

**Comment by cvenets** [comment]
Hello @Bobgy,

Thank you for the clarification about design + code + docs.

@yanniszark has previously designed, contributed, and documented Kubeflow's Istio/Dex/AuthService/OIDC integration, where multi-tenancy is core (docs here: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/). @jlewi can confirm this, since it was quite some time ago.

From the experience with this work, he then proposed the first design for KFP multi-tenancy, and actually showed the first demo of multi-tenant KFP in the relevant Community Meeting, where we were trying to understand if multi-tenancy for KFP is something that users want. Seeing the great demand from the community, Google decided to put effort in this from the KFP side.

He has also authored blog posts and given presentations to KubeCon about multi-tenancy in Kubeflow.

This is why it sounds quite reasonable to me to be an approver on the docs side.

Thank you,
Constantinos

**Comment by jlewi** [comment]
> I understand that Google tries to retain full control, but long-standing, and committed contributors should be acknowledged at some point.

Completely agree about acknowleding contributors. And it sounds like @Bobgy is acknowledging @yanniszark 's contributions and as you mention it looks @yanniszark has been recognized in blogs and presentations.

The primary role of OWNERs files though isn't to aknowledge contributions; its to ensure code quality and timely reviews by ensuring people reviewing and approving code have the most context.

Looking at the commit history. It looks like the most recent commits and reviews were made by @Bobgy and reviewed by @8bitmp3 .

So @Bobgy's request to start with reviewer as opposed to approver permissions seems reasonable. 

Adding @yanniszark as an approver would also be reasonabe .

Given @Bobgy has been the one actively maintaining these docs, I'm inclined to defer to him.

Is there a downside to starting with reviewer and bumping to approver once @Bobgy and @yanniszark have had a chance to collaborate on a couple PRs?

**Comment by cvenets** [comment]
@jlewi thank you for providing feedback.

The core reason I looped you in was to have at least one other person from the Google side, confirming all previous contributions of design, code, and docs wrt multi-tenancy that @yanniszark has done. So, that @Bobgy is also in sync, since a lot of them were not committed on KFP repos directly, but rather on other Kubeflow repos, so @Bobgy may not be familiar with them.

I agree completely on your comment wrt code quality, I didn't argue about an addition just for acknowledgement purposes, we wouldn't want that.

It is just a bit strange to me why we would be so reluctant to make someone that has repeatedly contributed quality code in this specific subject, an approver. That's all.

As you suggested, I will also let @Bobgy decide, since he is the current maintainer of these docs.

Thank you,
Constantinos

**Comment by Bobgy** [comment]
Thanks @jlewi @cvenets for clarification!

One thing I am still not sure is -- has Yannis contributed to this folder of multi tenancy documentations before?
My understanding is no, please correct me if I am wrong.

> Is there a downside to starting with reviewer and bumping to approver once @Bobgy and @yanniszark have had a chance to collaborate on a couple PRs?

I will suggest to go this route. I fully recognize Yannis' contributions in related areas, it's just a matter of collaborating on these docs for a trial.

One thing to note is that, we typically ask either @8bitmp3 or @joeliedtke for technical writing review and ensuring a consistent tone.

I'd only skip their review if the PR is truly trivial. We would expect other approvers to do the same on multi tenancy docs.

**Comment by jlewi** [comment]
Thanks
/lgtm

**Pull request merged**
