### PR TITLE
Added outdated banner to non-index docs unchanged in last 30d

### PR DESCRIPTION
**Pull request by jlewi**
This was originally PR #2066. @RFMVasconcelos is out this week and
the PR is blocked by a merge conflict so I rebased it in order
to get it merged.

Related to: #1984

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @animeshsingh 
/assign @Jeffwan 
/assign @jbottum 
/assign @8bitmp3 

Could one of you please LGTM this? If you look at the original PR #2031 you can see this has been a drawn out process. Getting the banner added to all the pages will be a good incentive to get people to take a look and update their docs and help us finalize the docs for 1.1.

**Comment by Jeffwan** [comment]
Thanks @jlewi driving this.

**Comment by jlewi** [comment]
@RFMVasconcelos did all the work. @RFMVasconcelos we should get your script checked in so we can rerun this in the future.

/approve

**Comment by RFMVasconcelos** [comment]
@jlewi @Jeffwan thank you for this! I'm back now 🚀

**Pull request merged**
