### PR TITLE
Add API doc for Kubeflow Pipelines

### PR DESCRIPTION
**Pull request by IronPan**
This doc is generated from 
https://github.com/kubeflow/pipelines/tree/master/backend/api/swagger
using swagger hub
https://app.swaggerhub.com/home

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/720)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-720--competent-brattain-de2d6d.netlify.com/docs/pipelines/kubeflow-pipeline-api-spec/

**Comment by sarahmaddox** [comment]
Thanks for this API doc! To fit it into the website structure, I recommend the following:

* Create a file at `/docs/pipelines/reference/api/_index.md`
similar to this one: https://github.com/kubeflow/website/blob/master/content/docs/reference/pytorchjob/_index.md

* Rename the api doc file from `.html` to `.md` and move it
from
`/docs/pipelines/kubeflow-pipeline-api-spec.html`
to
`/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.md`

* Add the following metadata  at the top of the `kubeflow-pipeline-api-spec.md` file:

```
+++
title = "Kubeflow Pipelines API"
description = "Reference documentation for the Kubeflow Pipelines API"
weight = 100
+++
```

Similar to this file:https://raw.githubusercontent.com/kubeflow/website/master/content/docs/reference/pytorchjob/v1beta1/pytorch.md

Try the above steps, to see if they cause Hugo to wrap the Kubeflow site navigation around the page and apply our styling. The above steps should also create a place for this page in the navigation tree on the left of the site. (I haven't tested the steps - you may need to do some tweaking. Basically, you need to copy the pattern used in the other reference docs listed above.)

**Comment by IronPan** [comment]
It doesn't seem to be rendering well. 
https://deploy-preview-720--competent-brattain-de2d6d.netlify.com/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/

**Comment by IronPan** [comment]
fix https://github.com/kubeflow/website/issues/577

**Comment by sarahmaddox** [comment]
Hallo @IronPan, following on from our chat, let's try this to unblock the API reference for now:

* Move the file at `/docs/pipelines/reference/api/_index.md` to `/docs/pipelines/reference/api.md`.
* Change the contents of the above file to this:

```
+++
title = " Pipelines API Reference"
description = "Reference documentation for the Kubeflow Pipelines API."
weight = 10
+++

See the [generated reference for Kubeflow Pipelines API v0.1.20](/docs/pipelines/reference/api/kubeflow-pipeline-api-spec/].
```

* Change the generated file name from 
`/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.md` to `/docs/pipelines/reference/api/kubeflow-pipeline-api-spec.html`.

The above guidelines are my best bet. Please adapt if necessary.

Later we can investigate creating a script that strips the Swagger-generated HTML, jQuery, and CSS from the generated reference, so that it fits into the styling and structure of the Hugo theme.

**Comment by sarahmaddox** [comment]
@IronPan Can we close this PR for now, since we're not intending to do any more work on it at the moment? We can re-open it if we decide to continue with it.

**Pull request closed without merging**
