### PR TITLE
Added @rimolive as approver for Pipelines

### PR DESCRIPTION
**Pull request by hbelmiro**
cc @chensun @rimolive

### CODE REVIEW

**Comment by rimolive** [comment]
cc @kubeflow/kubeflow-steering-committee This PR is critical given that Pipelines WG leads are out until July 22nd (the final release date for Kubeflow 1.9).

We need to add another approver for the Pipelines documentation PRs asap.

**Comment by jbottum** [comment]
I am supportive of this.   I would like others to provide their input.

**Review by terrytangyuan — APPROVED** [review]
+1

**Pull request merged**
