### PR TITLE
Add page for Spark operator/Yunikorn integration

### PR DESCRIPTION
**Pull request by jacobsalway**
Add a user guide page to the Spark operator on Yunikorn gang scheduling support that is upcoming in the 2.0.0 release.

https://github.com/kubeflow/spark-operator/issues/2098

### CODE REVIEW

**Comment by jacobsalway** [comment]
/hold

Holding til 2.0.0 release actually comes out.

**Review by yuchaoran2011 — APPROVED** [review]

**Review by yuchaoran2011 — COMMENTED** [review]
/lgtm

**Pull request merged**
