### PR TITLE
model registry: update MLOps diagrams

### PR DESCRIPTION
**Pull request by tarilabs**
Based on previous feedback from:
- https://github.com/kubeflow/website/pull/3698#issuecomment-2069810560
- https://github.com/kubeflow/website/pull/3698#discussion_r1597274742

Reorganize diagrams as follows:
1. make MLOps inner Vs outer cycle smaller just to introduce the concept
2. re-use overall architecture diagram for Kubeflow introduced with https://github.com/kubeflow/website/pull/3728
2.a. use similar style from https://www.kubeflow.org/docs/components/training/overview/#why-training-operator- and adapt to highlight the Model Registry box

Quick demo:
Screenshot 2024-07-26 at 10 44 24

This actualize the agreement from:
- https://github.com/kubeflow/website/pull/3698#discussion_r1607299980

@StefanoFioravanzo @andreyvelich wdyt ?

### CODE REVIEW

**Comment by ederign** [comment]
I liked the diagram @tarilabs ! /lgtm

**Review by ederign — APPROVED** [review]

**Comment by StefanoFioravanzo** [comment]
@tarilabs Nice diagram! All the components that "push" metadata to the model registry can also "pull" from it. How can we better represent this symmetry? Directional rows may give a wrong representation

**Comment by tarilabs** [comment]
> @tarilabs Nice diagram! All the components that "push" metadata to the model registry can also "pull" from it. How can we better represent this symmetry? Directional rows may give a wrong representation

thanks! I'm starting to followup on received feedback which I didn't have bandwidth to act upon before.

It is a valid comment, even tho I'd say for the most past some components _mainly push_ and _occasionally pull_ (or viceversa) but I concur a bidirectional symmetric arrow might just be good enough, will do 👍

**Comment by tarilabs** [comment]
@StefanoFioravanzo with 8b3b40e revised as follows:
- "Model Development" bidirectional: I can totally see the interactivity in both directions, especially during "inner loops" iterations
- "Model Serving" the direction was mean to flow from Model Registry, to KServe

I've left the other arrows unchanged, since in those automated components I would expect the components to index/catalog the result into the Model Registry

**Review by rareddy — APPROVED** [review]
/lgtm
/approve

**Review by andreyvelich — COMMENTED** [review]
Thank you for adding this @tarilabs, looks great!
/lgtm
/approve

**Comment by tarilabs** [comment]
All comments in this PR looks addressed to me,
and socialized this PR with all the folks who had original comments (links in [first message](https://github.com/kubeflow/website/pull/3828#issue-2431753797)) that this PR is meant to follow-up on--as agreed.

/remove-hold

**Pull request merged**
