### PR TITLE
Use a more compatible URL concat way

### LINKED ISSUE #3703: A more compatible way for concat a url in Kubeflow Pipeline/v2/Installation/Quickstart
While I'm trying to lauch a KFP following the [doc](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/#kfp-sdk), I found that current URL concat way is not compatible when user set endpoint with a `/` in the end.

## Current Doc Content
image

## A Possible Mistake

```python
from kfp import dsl
from kfp import client

@dsl.component
def addition_component(num1: int, num2: int) -> int:
    return num1 + num2

@dsl.pipeline(name='addition-pipeline')
def my_pipeline(a: int, b: int, c: int = 10):
    add_task_1 = addition_component(num1=a, num2=b)
    add_task_2 = addition_component(num1=add_task_1.output, num2=c)

endpoint = 'http://localhost:8080/'    # <= endpoint with a / in the end
kfp_client = client.Client(host=endpoint)
run = kfp_client.create_run_from_pipeline_func(
    my_pipeline,
    arguments={
        'a': 1,
        'b': 2
    }
)

url = f'{endpoint}/#/runs/details/{run.run_id}'
print(url)
```

### Output
There will be a redundant '/' following `8080`.
`http://localhost:8080//#/runs/details/your_run_id_here`

### What We Can Do
I think we can use `urllib` other than just a simple string concat to avoiding this possible problem.

### PR DESCRIPTION
**Pull request by realnumber666**
Fixes #3703 , I try to use `urljoin` in `urllib` package to provide a more compatible URL concat way in [KFP quickstart doc](https://www.kubeflow.org/docs/components/pipelines/v2/installation/quickstart/#kfp-sdk).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by hbelmiro** [comment]
Thank you for this contribution @realnumber666.
/lgtm

**Comment by hbelmiro** [comment]
Fixes https://github.com/kubeflow/website/issues/3703

**Comment by realnumber666** [comment]
> @realnumber666 can you please edit the PR description to use `Fixes https://github.com/kubeflow/website/issues/3703` instead of `Based on my issue https://github.com/kubeflow/website/issues/3703`. That way GitHub will automatically link this PR to your issue and will automatically close the issue when this PR is closed.
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> Thank you in advance.

**Comment by realnumber666** [comment]
@hbelmiro Done. Thanks for your advice!

**Comment by varodrig** [comment]
@hbelmiro  it seems we should close this PR given that the pages doesn't exist in the new version. please confirm .
cc @realnumber666

**Pull request closed without merging**
