### PR TITLE
Update aws-e2e.md to resolve 404s on model yaml files and update kfserving version to resolve x509 error

### PR DESCRIPTION
**Pull request by pythagoras1357**
Updated kfserving to the latest stable version to avoid the following error: failed calling webhook "inferenceservice.kfserving-webhook-server.defaulter": x509: certificate signed by unknown authority.

Updated paths to model yaml files to avoid 404s

### CODE REVIEW

**Comment by pythagoras1357** [comment]
@googlebot I signed it!

**Comment by pythagoras1357** [comment]
@googlebot I signed it!

**Comment by PatrickXYS** [comment]
@pythagoras1357 Thanks for updating!

/lgtm
/approve

**Pull request merged**
