### PR TITLE
Update istio documentation to branch 1.2 for Kubeflow v1.2

### PR DESCRIPTION
**Pull request by nanduri1998**
Documentation for installation via K8s needs update to v1.2 as all URLs point to 1.1

### CODE REVIEW

**Comment by berndverst** [comment]
FYI I had to do the same to the Azure docs (which use different shortcodes). I only caught that after the docs release for v1.2 also.
See: https://github.com/kubeflow/website/pull/2413/files

**Comment by Bobgy** [comment]
/approve
Thanks!

As a follow up, can you move shortcodes into a sub-folder and add OWNERS there, so kfctl_istio_dex maintainers can approve this by themselves?

**Comment by RFMVasconcelos** [comment]
@Bobgy that makes a lot of sense! I'll make an issue on this so we can get OWNERS for shortcodes ;)

**Pull request merged**
