### PR TITLE
Update the old Feast installation documentation links

### PR DESCRIPTION
**Pull request by tsisodia10**
This PR is initiated to address the issue of broken links in the Kubeflow documentation, targeting the installation instructions for Feast, by updating them with accurate URLs to ensure users have access to the correct resources.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Review by hbelmiro — APPROVED** [review]

**Comment by varodrig** [comment]
/close due to page has changed, the urls are already updated here https://www.kubeflow.org/docs/external-add-ons/feast/introduction/

cc @hbelmiro  @tsisodia10

**Pull request closed without merging**
