### PR TITLE
Apply Docs Restructure to `v1.2-branch` = update `v1.2-branch` to current `master` v2 

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
This acts on #2606.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@thesuperzapper @joeliedtke @Bobgy this PR makes the latest changes in `master` effective for `v1.2-branch` as discussed. 

We need @bobgy or @joeliedtke to approve it, as in v1.2-branch I am not a root OWNER, plus I made the PR :)

**Comment by thesuperzapper** [comment]
@Bobgy or @joeliedtke can you `/approve`?

**Comment by Bobgy** [comment]
Thank you!
/LGTM
@joeliedtke can you take a look?

**Comment by RFMVasconcelos** [comment]
@joeliedtke could you please take a look? :)

**Comment by thesuperzapper** [comment]
@joeliedtke really just need another set of eyes, if it looks good to you, please `/approve`

**Comment by RFMVasconcelos** [comment]
Perhaps @animeshsingh could take a look and approve if @joeliedtke is busy? 

This PR is blocking a lot of work from being effective on the website. Would be great to accelerate this, after a long push to make those contributions by the community.

**Comment by theadactyl** [comment]
pinging joeliedtke and will find a delegate if necessary.

**Comment by RFMVasconcelos** [comment]
Thank you for this @theadactyl and @animeshsingh !

**Pull request merged**
