### PR TITLE
Update kubeflow-summit-2023.md

### PR DESCRIPTION
**Pull request by papagala**
This PR fixes a typo in my name as a speaker for Kubeflow Conference Speaker 2023. It's a tiny error and you can see my correct name here https://www.linkedin.com/in/aioswaldo/

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you for the fix @papagala!
Please can you rebase your PR ?

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by papagala** [comment]
> Thank you for the fix @papagala! Please can you rebase your PR ?

I created another tiny Pull Request since after rebasing this one, it got a bit chaotic 😄  https://github.com/kubeflow/website/pull/3595

**Comment by papagala** [comment]
@Arhell I decided to create another PR https://github.com/kubeflow/website/pull/3595

**Pull request closed without merging**
