### PR TITLE
Evaluating the Docsy theme - ready for review

### PR DESCRIPTION
**Pull request by sarahmaddox**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/303)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Removing reviewers because this PR will be noisy until I've finished adding commits.

/uncc @jlewi 
/uncc @kunmingg

**Comment by sarahmaddox** [comment]
Fixes issue #291

**Comment by sarahmaddox** [comment]
Note for posterity: The magic fix for the Netlify problem was that I needed to install PostCSS (`npm install -D --save autoprefixer` then `npm install -D --save postcss-cli`) before building the site and checking in the `resources` folder.

**Comment by sarahmaddox** [comment]
/assign @abhi-g 
/cc @jlewi 
/cc @pdmack 

Preview:
* [Landing page](https://deploy-preview-303--competent-brattain-de2d6d.netlify.com/)
* [Example of docs page](https://deploy-preview-303--competent-brattain-de2d6d.netlify.com/docs/started/getting-started/)

I'm sure there's some tidying up we can do, such as refining the CSS and styling in general, but I'm hoping this version is good enough to submit and then refine if needed. Also, when we have the theme in place, we can work on adding extras like search and Google Analytics - the hooks are in the theme, we just need to add the specifics.

Comments welcome.

**Comment by jlewi** [comment]
This looks great.

I really like the links to edit this page and file an issue.

/lgtm
/approve
/hold

I put the hold on just in case you want others to review before submitting. If not just remove it.

**Comment by sarahmaddox** [comment]
Thanks @jlewi! I'll give it a couple of days, in case anyone else wants to take a look.

**Comment by gaocegege** [comment]
The new website preview looks awesome! :tada:

**Comment by nareshganesan** [comment]
Both the content and the UX of the new documenation looks great :+1:

**Pull request merged**
