### PR TITLE
Moving /notebooks to under /components + fix redirects

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
See #2468

cc @kubeflow/wg-notebooks-leads

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@Bobgy @joeliedtke could you please review? :)

**Review by 8bitmp3 — COMMENTED** [review]
thanks for this @RFMVasconcelos

**Comment by kimwnasptd** [comment]
Thank you for helping with this @RFMVasconcelos!

**Comment by 8bitmp3** [comment]
Since it's mostly
> ... moving the /notebooks folder under /components/ ..

Maybe this will speed things up:

/lgtm

**Comment by Bobgy** [comment]
Thank you @RFMVasconcelos !

/lgtm
/approve

**Comment by Bobgy** [comment]
It seems we need to add a redirection rule from /notebooks to /components/notebooks similar to https://github.com/kubeflow/website/pull/2505#issuecomment-781845799.
thoughts?

**Comment by RFMVasconcelos** [comment]
I've captured this need in #2511, I will review all changes and update redirects

**Pull request merged**
