### PR TITLE
Katib: Add Hyperparameter Tuning Architecture

### PR DESCRIPTION
**Pull request by andreyvelich**
Related: https://github.com/kubeflow/katib/issues/2255.
I added architecture of HP tuning task in Katib.
Also, I made changes for docs flow, please let me know what do you think about it.

/assign @tenzen-y @johnugeorge @gaocegege @kubeflow/release-team @diegolovison @hbelmiro @droctothorpe 

/hold for review

### CODE REVIEW

**Review by diegolovison — APPROVED** [review]

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Comment by droctothorpe** [comment]
Looks great! One small nit that is a testament to what an incorrigible pedant I am and therefore be ignored: the diagram uses CRD for experiments and trials when what's actually being created is a CR, not a CRD. The SDK and experiment controller don't create CRDs. Unfortunately, https://github.com/kubernetes/community/tree/master/icons doesn't provide a CR icon.

**Comment by droctothorpe** [comment]
Looks you can use an unlabeled CRD icon to reduce confusion:
https://github.com/kubernetes/community/tree/master/icons

**Comment by andreyvelich** [comment]
> Looks great! One small nit that is a testament to what an incorrigible pedant I am and therefore should probably just be ignored: the diagram uses CRD for experiments and trials and other custom resources when what's actually being created is a CR, not a CRD. Unfortunately, https://github.com/kubernetes/community/tree/master/icons doesn't provide a CR icon.

It's a good suggestion, thanks for review @droctothorpe!
Let me know if you think we can improve it further.

/hold cancel
/assign @tenzen-y @johnugeorge @droctothorpe @hbelmiro

**Review by droctothorpe — APPROVED** [review]
/lgtm

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Pull request merged**
