### PR TITLE
Update website versioning for v1.2

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
See #2322

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
cc @8bitmp3 @jlewi @Jeffwan

**Review by Jeffwan — COMMENTED** [review]
Seems we just need to make these changes. Rest should be taken care by cloud providers

**Comment by Jeffwan** [comment]
`fatal error: concurrent map read and map write` @RFMVasconcelos Are you able to start Hugo server locally? This is the first time I see this issue

**Comment by RFMVasconcelos** [comment]
Hm.. first time doing this as well, there seems to be an issue with Hugo - https://github.com/gohugoio/hugo/issues/7293

**Comment by Jeffwan** [comment]
@RFMVasconcelos website tests are not managed by Prow,  `/retest` won't work. Could you make tiny change in your change like adding empty line at the end in `layouts/shortcodes/kf-latest-version.html . Let's see if that's a reproducible or intermittent issue

**Comment by Bobgy** [comment]
I forced a redeploy, let's see how it goes

**Comment by RFMVasconcelos** [comment]
Thank you @Bobgy! Looks like it fixed the issue 🚀

**Comment by RFMVasconcelos** [comment]
Hi @Bobgy or @joeliedtke, could you please verify and approve?

**Pull request merged**
