### PR TITLE
Add containerized dev workflow.

### LINKED ISSUE #327: Add Containerized Dev Environment
Current [dev instructions](https://github.com/kubeflow/website/blob/master/README.md) for this repo require locally installing following dependencies:
* git
* hugo
* npm
* gulp-cli
* gulp

I suggest creating an optional, simpler dev workflow using a Docker image for portable dependency management. This can simplify development instructions, allow dev environments to be quickly spun up and avoid dependency conflicts between this and other projects.

I created a Dockerfile and a few convenience scripts to make changes for my last PR. 

A PR will follow with the dev tooling I've used to make changes to this project.

### PR DESCRIPTION
**Pull request by IMBurbank**
Fixes #327 

Adds `develop` directory with a Dockerfile and convenience scripts for a containerized development workflow. 

Right now, the use instructions are only in the directory-specific readme. I imagine it would be best to let the dev tools get a bit of use and refinement before adding instructions to the root readme. 

`docker_build.sh` and `docker_run.sh` have help docs.

I'll be happy to handle maintenance as necessary for the dev tools.

***Use Instructions from `develop/README.md`:***

Requirements:

* [Git][git-install-docs] to clone project repository
* [Docker][docker-install-docs] to build and run Docker image

## How to use

1. [Fork][github-fork-docs] the [kubeflow/website repo][kubeflow-website-repo]

1. Clone your fork locally. This example uses SSH cloning:
    ```bash
    mkdir kubeflow
    cd kubeflow/
    git clone git@github.com:<your-github-username>/website.git
    cd website/
    ```

1. Build the development Docker image

    ```bash
    ./develop/docker_build.sh
    ```

1. Running the Docker image will start the [hugo server][hugo-server-docs] by default

    ```bash
    ./develop/docker_run.sh
    ```

* The website will be served at [http://localhost:1313/][localhost-1313].

### Updating theme style

* You will have to install the `themes/kf/sass/package.json` npm dependencies to make changes to the website style (this only has to be done one time).

    ```bash
    ./develop/docker_npm_install.sh
    ```

* Run `gulp` after making style changes

    ```bash
    ./develop/docker_gulp.sh
    ```

[docker-install-docs]: https://docs.docker.com/install
[git-install-docs]: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
[github-fork-docs]: https://help.github.com/articles/fork-a-repo
[hugo-server-docs]: https://gohugo.io/commands/hugo_server/
[localhost-1313]: http://localhost:1313
[kubeflow-website-repo]: https://github.com/kubeflow/website

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/328)

### CODE REVIEW

**Comment by IMBurbank** [comment]
Thanks for the reply, @sarahmaddox.

Those changes look pretty doable. It looks like the image would have to switch to `hugo_extended`, add `autoprefixer` and swap `gulp-cli` for `postcss-cli`.

What is the intended timeline for the change to Docsy? I could set up a workflow that allowed both themes, set up and transition workflow to support the `kf` theme for a set amount of time, or completely change over a workflow that uses the Docsy theme in default commands.

I could also make these changes now, or que them up to go through with the Docsy PR.

**Comment by sarahmaddox** [comment]
Thanks @IMBurbank! The timeline for the Docsy PR is basically as soon as I can get everything working. :) I'm actively working on the PR, but have to bow to other priorities. So I think it's best if you go ahead with just the kf theme. Then tackle the Docsy change later.

/assign @kunmingg

**Comment by sarahmaddox** [comment]
@kunmingg @IMBurbank  As Isaac mentioned in an earlier comment, it'll be good for these tools to get some use and maybe refinement before we add them to the main README. Suggestion: Once this PR is approved and merged, Isaac could invite people to try out the tools. Ways to let people know: messages on Slack; an introduction in the Community meeting; comments on this issue...

**Comment by sarahmaddox** [comment]
Hallo @IMBurbank the new theme was applied in January. What do you think - would you like to revise this PR to take the new theme into account, and do you think the resulting process will be easier than the existing one? I'm a little concerned that we'll need to keep changing the process too.

**Comment by sarahmaddox** [comment]
I'm going to close this due to inactivity. Please do re-open it and address the comments if you still want this PR merged.

**Pull request closed without merging**
