### PR TITLE
add column for version to distro table

### PR DESCRIPTION
**Pull request by shannonbradshaw**
@RFMVasconcelos @Bobgy as agreed in our meeting.

### CODE REVIEW

**Comment by nakfour** [comment]
@yanniszark @shannonbradshaw we updated the KF 1.3 documentation on OCP in this branch https://github.com/kubeflow/website/pull/2647
Getting someone to review this.

**Comment by shannonbradshaw** [comment]
@nakfour @yanniszark I pushed an update to this PR labeling OpenShift docs as updated for 1.3.

**Comment by shannonbradshaw** [comment]
Per @RFMVasconcelos Charmed Operators distro updated for 1.3.

**Comment by Bobgy** [comment]
@RFMVasconcelos @shannonbradshaw I believe we should merge this ASAP, distributions can add 1.3 mark as soon as they are ready.

**Comment by Bobgy** [comment]
Also @yanniszark

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos can we merge this?

**Comment by RFMVasconcelos** [comment]
@shannonbradshaw I think we are good to merge. Hopefully, we will have MicroK8s v1.3 by EOD today, but let's merge this and we'll make a separate PR once it's tested. 

/lgtm

**Pull request merged**
