### PR TITLE
Update python-based-visualizations.md

### PR DESCRIPTION
**Pull request by hirokinko**
Fix broken links.

### CODE REVIEW

**Comment by janeman98** [comment]
Thanks @hirokinko for submitting this PR.
/assign @joeliedtke

**Comment by joeliedtke** [comment]
Preview: https://deploy-preview-1967--competent-brattain-de2d6d.netlify.app/docs/pipelines/sdk/python-based-visualizations/

**Comment by joeliedtke** [comment]
/lgtm
/approve

Thanks for fixing these links, @hirokinko!

**Comment by hirokinko** [comment]
Thanks!

**Pull request merged**
