### PR TITLE
Update upgrade doc for upgrading from v0.6.2

### PR DESCRIPTION
**Pull request by janeman98**
Currently, kfctl of v0.6.2 does not support -f flag, following exiting documentation in https://www.kubeflow.org/docs/upgrading/upgrade/ 

Step 2 : 
...
kfctl delete -V -f ${CONFIG_FILE}

will throw an error. 
The documentation should be modified to download the kfctl of v0.7.0 first.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1420)

### CODE REVIEW

**Comment by jinchihe** [comment]
Hey @janeman98 why not just remove `-f` option in the step 2? if user uses old kfctl client, should also can remove the kubeflow cluster. Thanks.

**Comment by janeman98** [comment]
@jinchihe Thanks for the review!

From upgrading from v0.6.2: remove -f option in the step 2 should work
However, for upgrading from v0.7.0 to future version (say v1.0) : remove -f option in the step 2 will NOT work (since -f is required -- see below)

(v.0.7.0 kfctl)
kfctl delete -V
Error: Must pass in -f configFile
Usage:
  kfctl delete [flags]

Flags:
      --delete_storage   Set if you want to delete app's storage cluster used for mlpipeline.
  -f, --file string      The local config file of KfDef.
  -h, --help             help for delete
  -V, --verbose          verbose output default is false

Must pass in -f configFile

**Comment by janeman98** [comment]
@jinchihe 
Since v1.0 release is not there yet, can we remove -f option in the step 2 for now? When we have v1.0, we can document how to upgrade from v0.6.2 to v1.0 and v0.7.0 to v1.0.

What do you think?

**Comment by jinchihe** [comment]
> @jinchihe
> Since v1.0 release is not there yet, I believe we can remove -f option in the step 2 for now. When we have v1.0, we can document how to upgrade from v0.6.2 to v1.0 and v0.7.0 to v1.0.
> 
> What do you think?

I think the upgrading feature will be enhanced and the docs will be rewritten if 0.7 -> 1.0. Since this is hard to say this is upgrading... personally, we just need to consider old -> 0.7 case. Agree?

**Comment by janeman98** [comment]
> > @jinchihe
> > Since v1.0 release is not there yet, I believe we can remove -f option in the step 2 for now. When we have v1.0, we can document how to upgrade from v0.6.2 to v1.0 and v0.7.0 to v1.0.
> > What do you think?
> 
> I think the upgrading feature will be enhanced and the docs will be rewritten if 0.7 -> 1.0. Since this is hard to say this is upgrading... personally, we just need to consider old -> 0.7 case. Agree?

Agree. I will remove -f option for now.

**Comment by janeman98** [comment]
@jinchihe
I have updated the file as per your review feedback (+ move description on CONFIG_FILE to step#5). Please review/approve and let me know if further modification is needed.

**Comment by jinchihe** [comment]
/lgtm
/approve

Thanks @janeman98

**Pull request merged**
