### PR TITLE
Update Kubeflow Pipelines Standalone Deployment documentation to refrense to the latest version

### PR DESCRIPTION
**Pull request by JohanWork**
issue #1862

- updating the documentation to point to the latest version 0.3.0

### CODE REVIEW

**Comment by joeliedtke** [comment]
This change can be previewed at: https://deploy-preview-1866--competent-brattain-de2d6d.netlify.com/docs/pipelines/installation/standalone-deployment/

**Comment by Bobgy** [comment]
Thanks for the catch!
/approve
/lgtm

**Pull request merged**
