### PR TITLE
add deployKF to list of distributions

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR adds deployKF, to the list of distributions:

- https://www.deploykf.org/
- https://github.com/deployKF/deployKF

I have positioned it alphabetically in this list (after the top section of major cloud providers).

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@zijianjoy @james-jwu @jbottum I would appreciate a review and approve.

**Comment by jbottum** [comment]
@thesuperzapper I am inclined to provide support for this PR, although I would appreciate some clarity on support for deployKF.  For example, the rest of distributions have companies behind them.    deployKF lists deployKF as its maintainer rather than Aranui Solutions, a US-based MLOps Consulting Company.    If we are going to add deployKF (with deployKF as the maintainer), then the approvers should review deployKF's maintainers and/or Aranui's contributor team.   I am not trying create unequal hurtles for deployKF but I do want to set some expectations for users and the community who will depend on / invest in deployKF.   Is there a public statement on deployKF (and/or Aranui's commitment) to support deployKF for some period of time or for some number of KF releases ?

**Comment by thesuperzapper** [comment]
@jbottum While it might be somewhat true to list [Aranui Solutions](https://www.aranui.solutions/) as the maintainer (because that's my company, and I am currently the maintainer), I think it might send the wrong message to users about who is "in charge" of deployKF.

I am intending to build the deployKF community so that it is a self-sufficient project with its users/contributors leading its direction.

But I am not against listing "Aranui Solutions" for now, until the project builds itself a base of contributors.

**Comment by thesuperzapper** [comment]
@jbottum I have updated it to say "Aranui Solutions" as the maintainer.

**Comment by thesuperzapper** [comment]
@zijianjoy @james-jwu we will need one of you to approve (as a root owner)

**Pull request merged**
