### PR TITLE
Slack channels alphabetization + add on-prem SIG

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Adding this as per request from SIG on-prem

### CODE REVIEW

**Review by PatrickXYS — APPROVED** [review]
/lgtm

Thanks @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
@andreyvelich @8bitmp3 can you please approve this one? :)

**Review by andreyvelich — APPROVED** [review]
Thanks @RFMVasconcelos!
/lgtm
/approve

**Pull request merged**
