### PR TITLE
Fix broken link (MPI doc)

### PR DESCRIPTION
**Pull request by gcheron**
Fix broken link in MPI doc.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Please sign CLA

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
CLA

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by thesuperzapper** [comment]
Closing as https://github.com/kubeflow/website/pull/3095 has resolved this issue.

/close

**Pull request closed without merging**
