### PR TITLE
Fix a typo in pipelines-compatibility page

### PR DESCRIPTION
**Pull request by suminb**
Add a missing space.

### CODE REVIEW

**Comment by Jeffwan** [comment]
@suminb You need to sign CLA to make the contribution.

**Comment by suminb** [comment]
image

Done!

**Comment by joeliedtke** [comment]
Preview:
https://deploy-preview-2058--competent-brattain-de2d6d.netlify.app/docs/pipelines/pipelines-quickstart/

**Comment by joeliedtke** [comment]
/lgtm
/approve

Thanks for fixing this, @suminb!

**Pull request merged**
