### PR TITLE
Upgraded to the latest version of the Docsy theme

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/1137

Steps taken:

+   Create new branch.
+   Go to the `/themes` dir.
+   Delete all files under `themes/docsy` including the `docsy` dir.
+   Fetch all files from Docsy: `git clone --recurse-submodules --depth 1 https://github.com/google/docsy.git`
+   Remove the Docsy user guide as we don't need it in the Kubeflow repo:

    +   `cd themes/docsy
`    +   `rm -rf userguide/`

+   Go back to the `/website` dir.
+   `git add` and `git commit` the updates, push to origin, and create a WIP PR (to make checking the diff easier - see next step).
+   Check the diff between old Docsy files and updated Docsy files.
+   Check the diff between Kubeflow customised files (see above) and updated Docsy files.

    +   Where relevant, adjust our custom files to incorporate new Docsy changes into the Kubeflow custom layouts.
    +   Where relevant, remove custom files if Docsy now includes the update (see notes above).

+   Rebuild Hugo.
+   Test locally.
+   Commit all changes. (Force add the updated `/resources` files if necessary.)
+   Push to Netlify and test again.

Checked diffs for all Kubeflow's custom layout files. See full details in issue comments https://github.com/kubeflow/website/issues/1137. Made the following changes:
* Removed custom layout file from Kubeflow: `layouts/partials/hooks/body-end.html`, because Docsy itself now includes heading links based on our initial customization. See issue https://github.com/google/docsy/issues/118. Tested heading links in preview, such as on [this page](https://deploy-preview-1197--competent-brattain-de2d6d.netlify.com/docs/started/getting-started/#troubleshooting).
* File: `/layouts/partials/footer.html` - we still need the customization. Updated it to incorporate new Docsy changes.
* File: `/layouts/partials/head.html` - we still need the customization. Updated it to incorporate new Docsy changes.
* File: `/layouts/partials/page-meta-links.htm` - we still need the customization. Updated it to incorporate new Docsy changes.
* Removed custom file `layouts/partials/navbar-version-selector.html` - Docsy now has this file, based on our customization.
* File: `/layouts/partials/navbar.html` - we still need the customization. Retained our custom layout in full, due to issues with Docsy's updated layout. See https://github.com/google/docsy/issues/138

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1197)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1197--competent-brattain-de2d6d.netlify.com/

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1197--competent-brattain-de2d6d.netlify.com/

This PR is now ready for review. Applying a hold to give it time to soak.
/hold

**Comment by sarahmaddox** [comment]
@abhi-g and @joeliedtke Please would you click around the preview and see if anything strange jumps out at you. I've done some fairly comprehensive checking, but the more eyes the better. Unfortunately I haven't figured out a way to make GitHub suppress the diff on the `generated` and `vendor` directories - the many many updates in those directories blow out the diff.

/assign @abhi-g 
/assign @joeliedtke

**Comment by abhi-g** [comment]
@sarahmaddox I clicked through a few pages and nothing obviously broken jumps out to me. Looking good to me.

**Comment by sarahmaddox** [comment]
Thanks @abhi-g! I'm going to remove the hold now, so that this PR can merge. @joeliedtke If you see anything strange on the website after the merge, let me know. :)

/hold cancel

**Comment by joeliedtke** [comment]
Adding notes about things that look odd. After the note is added I'll research if this is a Netlify staging issue or a possible Docsy issue.

- Feedback does not appear to work. Google analytics scripts not present in staging and I do not see an error in the console. Seems likely that this is not intended to work in staging.
- "Edit this page" link does not work. Expected URL:  https://github.com/kubeflow/website/edit/master/content/docs/about/kubeflow.md, Actual: https://github.com/kubeflow/website/edit/master/content/en/docs/about/kubeflow.md
- Wishlist, restyle the links on the home page tiles. Currently the links are low contrast which would be a usability and accessibility issue. (Will write this up as a bug.)

**Comment by joeliedtke** [comment]
Adding notes on things that I have spot checked:

- Home page tile links
- Page content styling
- Navigation styling (top, left, right, and bottom)
- Shortcodes
- Index pages
- Links that appear to be part of the page template
- Feedback form
- Site search (Note, prod site has ads on site search. Staging does not.)

**Comment by joeliedtke** [comment]
After chatting with @sarahmaddox, it sounds like the "Edit this page" issue in staging may be related to the new Docsy template. Otherwise, this looks good to me.

**Comment by sarahmaddox** [comment]
Thanks so much for reporting the issue with the broken link for "Edit this page" @joeliedtke Well spotted!

I found the code that's causing the problem in the Docsy layouts. After some trial and error, I've decided to revert to our custom layout and report the issue to the Docsy team for fixing. They've changed that file a bit recently, and will have more background about the variables in play. Here's the issue:
https://github.com/google/docsy/issues/138

PTAL - I think the reversion of the layout has fixed the problem.

**Comment by joeliedtke** [comment]
/lgtm

LGTM with one nit, the label for "Create issue" (below Edit this page) changed to "Create documentation issue".

**Comment by sarahmaddox** [comment]
> LGTM with one nit, the label for "Create issue" (below Edit this page) changed to "Create documentation issue".

Yeah, it's a little ugly. It's a feature of the Docsy theme, to differentiate doc issues from dev-project issues. We haven't enabled the option to create dev-project issues. The string is in [Docsy's `en.toml` file](https://github.com/google/docsy/blob/master/i18n/en.toml#L39), and I don't think we should override that file.

**Pull request merged**
