### PR TITLE
Notebooks section deduplication

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
There are currently 2 sections under [components](https://www.kubeflow.org/docs/components/) of Jupyter notebooks, being one an outdated redirect.

This PR cleans that.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by RFMVasconcelos** [comment]
@joeliedtke this needs a root owner to approve as components does not have OWNERS file

**Comment by RFMVasconcelos** [comment]
@Bobgy would you be able to approve?

**Comment by RFMVasconcelos** [comment]
cc @kubeflow/wg-notebooks-leads

**Comment by 8bitmp3** [comment]
gently ping @Bobgy @joeliedtke 

(@RFMVasconcelos )
> ... this needs a root owner to approve as components does not have OWNERS file

**Comment by thesuperzapper** [comment]
FYI the leads of Notebook WG are all good with this, so can one of @Bobgy or @joeliedtke please `/approve`

**Comment by Bobgy** [comment]
Sure!
/approve

**Comment by RFMVasconcelos** [comment]
We just need one more /lgtm :)

**Comment by kimwnasptd** [comment]
/lgtm

[worth a shot]

**Pull request merged**
