### PR TITLE
update bentoml guide in external serving section

### PR DESCRIPTION
**Pull request by yubozhao**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by jbottum** [comment]
@yubozhao this look good.   I might suggest a few potential edits.   I don't say these are must haves but might help.  1) The doc might list the dependences i.e. K8s versions 1.2x. 2) The doc might include an explicit link to BentoML support.   I see a community link...you might want to make it very easy for folks to find BentoML support.    You might want that in a couple of places.

**Comment by jbottum** [comment]
@Arhell @8bitmp3 @berndverst hi guys, woul you please review this PR?  thanks!

**Comment by yubozhao** [comment]
Hello @liuqi @Arhell @berndverst Happy holidays

Let me know if you guys have a chance to review this PR, and I am happy to make changes to get it merged in

**Pull request merged**
