### PR TITLE
add description for reusable components operations

### PR DESCRIPTION
**Pull request by Windrill**

### CODE REVIEW

**Comment by Windrill** [comment]
@googlebot I signed it!

**Comment by RFMVasconcelos** [comment]
@Windrill thank you for this PR! 

One of the pipelines OWNERS should now review and approve. 

@8bitmp3 @joeliedtke @numerology maybe could help here :)

**Comment by Bobgy** [comment]
/cc @chensun @neuromage 
we missed this nice PR

**Comment by Bobgy** [comment]
and @joeliedtke

**Review by RFMVasconcelos — COMMENTED** [review]
@Bobgy @joeliedtke should we merge this? 

Looks like a good addition.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Pull request closed without merging**
