### PR TITLE
[WIP] testing table border and background color

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing border and background colors for tables.
Testing colors for code elements.
See issue #680.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/776)

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello. Will the netlify preview be updated after the `needs-ok-to-test` label is removed?

**Comment by sarahmaddox** [comment]
Hallo @kbhawkey I've added the `ok-to-test` label, but the Netlify preview should have been updated anyway. Are you making CSS changes? (The procedure is a little tricky in that case, as Netlify doesn't fully support extended versions of Hugo.)

**Comment by kbhawkey** [comment]
> 
> 
> Hallo @kbhawkey I've added the `ok-to-test` label, but the Netlify preview should have been updated anyway. Are you making CSS changes? (The procedure is a little tricky in that case, as Netlify doesn't fully support extended versions of Hugo.)
> 
> These guidelines should help: https://testydocsy.netlify.com/docs/getting-started/#deployment-with-netlify

hello @sarahmaddox. OK. I have a local clone of this repo, but did not clone using `git clone --recurse-submodules --depth 1 https://github.com/my/example.git`. Also, I did not specifically clone the docsy repo. I do have a sass processor, an installation of hugo extended,as well as postcss-cli. The am able to view a local preview with `hugo server`.
If I made updates to `_variables_project.scss`, and generated a file in resources, `main.scss_*`, what needs to happen in order to build/run these changes on this netlify site? I have probably misunderstood the use of the theme. Thanks.

**Comment by sarahmaddox** [comment]
I think it should be fine not to recursively clone the theme, provided your diff shows the only update is to the relevant SCSS file and resulting resources.

The problem is that Netlify doesn't yet support the extended Hugo theme. Try this as a workaround:

* Force add your changes in the resources folder: `git add -f resources/`
* Commit the resulting changes and push them back up to your branch.

You should then see the styling changes in the Netlify preview.

**Comment by kbhawkey** [comment]
> 
> 
> I think it should be fine not to recursively clone the theme, provided your diff shows the only update is to the relevant SCSS file and resulting resources.
> 
> The problem is that Netlify doesn't yet support the extended Hugo theme. Try this as a workaround:
> 
>     * Force add your changes in the resources folder: `git add -f resources/`

Something's still amiss. Adding the directory only commits one resource file, not the entire directory. Only one resource file is generated.

**Comment by sarahmaddox** [comment]
> Something's still amiss. Adding the directory only commits one resource file, not the entire directory. Only one resource file is generated.

That could still be OK. Often CSS changes only result in one resource file being regenerated. Do your changes show up in the preview?

**Comment by sarahmaddox** [comment]
Another thing I've found sometimes helps: When building your site locally, try stopping your Hugo server, then running just `hugo -D` to build the site without running the server, then restarting the server with `hugo server -D`.

**Pull request closed without merging**
