### PR TITLE
Feature/issue3536 update arch diagram

### PR DESCRIPTION
**Pull request by vikas-saxena02**
Pull request for changes made as part of https://github.com/kubeflow/website/issues/3536

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by vikas-saxena02** [comment]
@Arhell what is the next course of action on this?

**Comment by Arhell** [comment]
> @Arhell what is the next course of action on this?

Hi, wait for lgtm and approve

**Comment by juliusvonkohout** [comment]
@johnugeorge @jbottum @andreyvelich @thesuperzapper how can we move forward? I think we have a first time contributor here

**Pull request closed without merging**
