### PR TITLE
Fix 3rd-level indentation for videos and slides (#169)

### PR DESCRIPTION
**Pull request by aVideogamer**
This is my first pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/170)

### CODE REVIEW

**Comment by aVideogamer** [comment]
I signed it!

**Comment by pdmack** [comment]
@aVideogamer need the CLA completed please.

**Comment by aVideogamer** [comment]
@pdmack I changed my commit's mail to match that on the CLA. Should all be good now.

**Comment by texasmichelle** [comment]
Thanks for submitting!

/lgtm
/approve

**Pull request merged**
