### PR TITLE
Netlify: Add support

### PR DESCRIPTION
**Pull request by gaocegege**
- Added `netlify.toml` to auto-config netlify app
- Ignore public (If we decided to use netlify for prod)

Preview in Netlify is: https://kubeflow-website-dev.netlify.com/

### CODE REVIEW

**Comment by gaocegege** [comment]
/hold

We need to come to an agreement in #5 before the PR.

**Comment by jlewi** [comment]
Is the test failure just because we don't have any tests? Would adding an empty prow_config.yaml fix that?

**Comment by gaocegege** [comment]
ref https://github.com/kubeflow/website/issues/7

I think we do not need to presubmit and postsublime. WDYT?

Of course, Adding a empty prow.yaml also works for me.

**Comment by jlewi** [comment]
For consistency with other repositories I'd prefer to have an empty prow file rather than removing the prow jobs all together.

**Comment by gaocegege** [comment]
SGTM. I will take a look.

**Comment by jlewi** [comment]
@gaocegege Can you sync? We added a prow_config.yaml file so I think the tests should pass.

**Comment by gaocegege** [comment]
Yeah, I will rebase the master ASAP.

**Comment by gaocegege** [comment]
@jlewi 

Please see the deploy preview https://deploy-preview-9--competent-brattain-de2d6d.netlify.com/

**Comment by jlewi** [comment]
/hold cancel
I think we've agreed to go with Netify.

**Pull request merged**
