### PR TITLE
prow_config.yaml: Add

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

### CODE REVIEW

**Comment by gaocegege** [comment]
/assign @jlewi 

I think ksonnet is really a big overhead for maintenance. :worried:

**Comment by jlewi** [comment]
Is the workflow actually testing anything relevant for this repository? What if in prow_config.yaml we just make workflows an empty array? Then I think we won't run any Argo workflows but the test should be reported as a success; so we don't need to check in a ksonnet app.

**Comment by gaocegege** [comment]
Do you mean

```
workflows:
```

I tried to leave the file empty but the test failed.

**Comment by jlewi** [comment]
@gaocegege correct. Make the array workflows in prow_config.yaml an empty array. We loop over that array [here](https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py#L95) so if workflows is empty it should be a nullop.

So if there are no workflows the test should just be reported as successful.

**Comment by gaocegege** [comment]
I will update it, thanks!

**Comment by gaocegege** [comment]
@jlewi It seems that it does not work for us.

Could I unassign myself and assign you to setup the prow for the repo?  You are familiar with our test infra :smile:

**Comment by jlewi** [comment]
Sure

**Comment by jlewi** [comment]
Fixed by #11 PTAL.

**Pull request closed without merging**
