### PR TITLE
Added next steps to the on prem getting-started guide

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/631

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/778)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-778--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-k8s/#next-steps

**Comment by thedriftofwords** [comment]
/lgtm

The only possible improvement I can think of: give readers some hint of what's awaiting them at the Kubeflow web UIs link. For example: "Follow the instructions to connect to the Kubeflow web UIs, where you can manage various aspects of your Kubeflow deployment."

It's also legitimate to ignore this, in favor of keeping the bullet point more concise.

**Comment by sarahmaddox** [comment]
> The only possible improvement I can think of: give readers some hint of what's awaiting them at the Kubeflow web UIs link. For example: "Follow the instructions to connect to the Kubeflow web UIs, where you can manage various aspects of your Kubeflow deployment."

Thanks, good idea. Done.

**Pull request merged**
