### PR TITLE
Adding VMware Tanzu Kubernetes Grid option for deploying Kubeflow

### PR DESCRIPTION
**Pull request by cwei44**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ytsophie** [comment]
@dsdinter @8bitmp3 ,do you have any comments?

**Comment by ytsophie** [comment]
@RFMVasconcelos ,could you ask @dsdinter @8bitmp3 to review the PR?

**Comment by zijianjoy** [comment]
cc @shannonbradshaw

**Comment by cwei44** [comment]
@Bobgy and @8bitmp3 could you help to review this pull request?

**Comment by cwei44** [comment]
@dsdinter @8bitmp3 could you help to review this request?

**Comment by liuqi** [comment]
Hi folks, @cwei44 and I are from VMware. And we both agree to follow the rule described in https://github.com/kubeflow/website/issues/3074 We will add Kubeflow on vSphere docs as external website. We have sent a new PR https://github.com/kubeflow/website/pull/3396 for that purpose. Thanks.

**Comment by liuqi** [comment]
@cwei44 Please help to close this PR per above update. Thanks.

**Pull request closed without merging**
