### PR TITLE
add treebeardtech to list of distributions

### PR DESCRIPTION
**Pull request by alex-treebeard**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

Please sign CLA, thanks

**Review by hbelmiro — COMMENTED** [review]
@alex-treebeard can you please [sign-off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)?

**Comment by varodrig** [comment]
@hbelmiro  is this PR still needed? do we need @alex-treebeard  to sign off the commits?

**Comment by hbelmiro** [comment]
I think we can close and @alex-treebeard can re-open if needed.

/close

**Pull request closed without merging**
