### PR TITLE
Refactoring the left-hand navigation panel.

### PR DESCRIPTION
**Pull request by sarahmaddox**
Proposing some changes to the left-hand navigation panel. Discussion doc coming soon.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/406)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Fixes [394](https://github.com/kubeflow/website/issues/394).
Fixes [383](https://github.com/kubeflow/website/issues/383).

Discussion doc: https://docs.google.com/document/d/1WVUoHAbymNcpRe3y3hF_6iESFzqdaPu3bK7YpFpN28I/edit#heading=h.ulsk1eh6x057

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-406--competent-brattain-de2d6d.netlify.com/docs/

Preview of redirect: https://deploy-preview-406--competent-brattain-de2d6d.netlify.com/docs/guides/pipelines/

Another redirect: https://deploy-preview-406--competent-brattain-de2d6d.netlify.com/docs/guides/components/components

**Comment by abhi-g** [comment]
/lgtm

You might have to resolve one conflicting file though.

**Pull request merged**
