### PR TITLE
Revert #3782 "Added Pipelines v2 installation pages"

### PR DESCRIPTION
**Pull request by thesuperzapper**
Reverts kubeflow/website#3782

Please see https://github.com/kubeflow/website/pull/3782#issuecomment-2211508170.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@hbelmiro as I was saying in https://github.com/kubeflow/website/pull/3782#issuecomment-2211508170, the PR https://github.com/kubeflow/website/pull/3782 was unacceptable for a few reasons and needs to be reverted ASAP:

1. It made no actual content changes while moving pages from the V1 to the V2 section
2. It added pages to the V2 section which have no relationship to the Kubeflow Pipelines V2 (like "Choose an executor").
3. It removed the docs for installing KFP v1.
4. It did not add any redirects making all old links into 404s.

**Comment by thesuperzapper** [comment]
@andreyvelich @rimolive either of you could also approve this PR, because it's very important that we revert soon.

**Comment by thesuperzapper** [comment]
Also @kubeflow/pipelines might be interested to see that we are reverting a strange PR in the KFP docs.

**Comment by rimolive** [comment]
@thesuperzapper Why reverting the change instead of fixing the missing links? I just checked the docs and I could not find any missing/broken link so please point me to these ones so we can fix asap.

**Comment by thesuperzapper** [comment]
You are not reading my comment https://github.com/kubeflow/website/pull/3791#issuecomment-2211509653, the primary issue is that it's not acceptable to move V1 docs into the V2 section without regard for the content.

Also, here is a list of links that are now 404:

- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/choose-executor/
- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/compatibility-matrix/
- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/localcluster-deployment/
- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/overview/
- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/standalone-deployment/
- https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/upgrade/

But even if you had created the appropriate redirects, I would still be suggesting a revert, because it's just not helpful to move docs so that they are actually incorrect.

**Comment by thesuperzapper** [comment]
@rimolive please don't try and defend the PR, just accept the reverse and make a new one, everyone makes mistakes.

It was never acceptable to randomly move V1 docs into the V2 section.

**Comment by hbelmiro** [comment]
@rimolive @thesuperzapper I'm approving this revert and will create a new installation page for v2 with minimal information to install v2. We can iterate later.

/lgtm
/approve

**Comment by hbelmiro** [comment]
@thesuperzapper can you please rebase?

**Comment by thesuperzapper** [comment]
@hbelmiro I have rebased the PR.

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Pull request merged**
