### PR TITLE
Update install-kubeflow.md

### PR DESCRIPTION
**Pull request by aronchick**

### CODE REVIEW

**Comment by 8bitmp3** [comment]
@aronchick I can `/lgtm` if this is urgent. Otherwise, I can only suggest three formatting + stylistic changes.

**Comment by joeliedtke** [comment]
/assign

@aronchick is this an open issue? If so, is there a bug for it? I would recommend adding a link to the bug to the note.

**Comment by RFMVasconcelos** [comment]
This is losing relevance with Kubeflow v1.3 release and has a conflict. 

Should we close it? Or fix the conflict and merge?

**Review by RFMVasconcelos — COMMENTED** [review]
As the community has deprecated `kfctl` and given that this change is no longer true, I think we can close this PR.

/close

**Pull request closed without merging**
