### PR TITLE
Update latest-version.html of KFP

### PR DESCRIPTION
**Pull request by numerology**
Part of KFP weekly release. Thanks!

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1415)

### CODE REVIEW

**Comment by Bobgy** [comment]
Hi @numerology, can you follow instruction in the release playbook to update this file without adding a newline at the end of file. You cannot use github UI to make the change, it will always append an newline at the end

**Comment by sarahmaddox** [comment]
Heh you're right @Bobgy - I just tried removing the empty line and it didn't work.

**Comment by numerology** [comment]
Oh I missed that. Thanks @Bobgy @sarahmaddox for reminding!

**Pull request merged**
