### PR TITLE
Update spark-operator getting-started

### PR DESCRIPTION
**Pull request by ha2hi**
Fixed Service Account (RBAC) path.
Ref: https://github.com/kubeflow/spark-operator/pull/2191

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ha2hi** [comment]
Hi, @ChenYi015 
I know you're busy, but could you approve?

**Review by ChenYi015 — APPROVED** [review]

**Comment by ChenYi015** [comment]
@ha2hi Sorry for the late reply. Thanks for updating the docs. 
/lgtm

**Pull request merged**
