### PR TITLE
Added complete documentation on installing Kubeflow 1.4 on Azure Cloud

### PR DESCRIPTION
**Pull request by ajinkya933**
Updated current document to install Kubeflow 1.4 on Azure Cloud

### CODE REVIEW

**Comment by ajinkya933** [comment]
I have added a readme file for installing Kubeflow 1.4 on Azure Cloud.

**Comment by ajinkya933** [comment]
I have added Missing CLA certificate

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ajinkya933** [comment]
cla certificate is signed for one contributor but not for other contributor, ( this happened because I used 2 different machines while pushing the commit) let me know how to fix this cla issue, if it is causing any delay in approval of pull requests

**Comment by ajinkya933** [comment]
​  @zijianjoy please take a look

**Comment by ajinkya933** [comment]
@shannonbradshaw

**Pull request closed without merging**
