### PR TITLE
Remove outdated API Reference for Katib

### PR DESCRIPTION
**Pull request by tenzen-y**
Remove outdated API Reference for Katib and Direct the user to the latest documentation on GitHub as discussed in [this](https://github.com/kubeflow/katib/pull/1709#issuecomment-965913071).

Ref: https://github.com/kubeflow/katib/pull/1709

/assign @andreyvelich @gaocegege @johnugeorge

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you for the update @tenzen-y!
/lgtm
/assign @gaocegege @johnugeorge

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by gaocegege — COMMENTED** [review]
/lgtm

Thanks for your contribution! :tada: :+1:

**Pull request merged**
