### PR TITLE
Update slack invite link

### PR DESCRIPTION
**Pull request by Linchin**

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@Linchin is something wrong with the existing link?

**Review by Arhell — COMMENTED** [review]
Fix https://github.com/kubeflow/website/pull/3210

**Comment by thesuperzapper** [comment]
closing as https://github.com/kubeflow/website/pull/3210 was merged and also fixed this
/close

**Comment by GerardoGR** [comment]
Not sure if we should create a new issue or just comment on this one so I will do both. Consider closing #3226 once the invite link is updated.

**Pull request closed without merging**
