### PR TITLE
Improve organization of Kubeflow components

### LINKED ISSUE #572: Refactor the "Components" section of the Kubeflow docs for better UX
Restructure the “Components” section of the Kubeflow docs - categorize the components by phase in ML workflow: training, serving, parameter tuning, etc.

https://www.kubeflow.org/docs/components/

### LINKED ISSUE #868: "Components of Kubeflow" can be better organized
Consider refactoring the page, by organizing them along functional lines:
- Training (TFJob, PytorchJob, MPI, MXNet, Chainer)
- Serving (TF serving, Seldon, Batch Predict)
- Pipelines
- Hyperparameter Tuning
- Data

### PR DESCRIPTION
**Pull request by Tabrizian**
Closes #572. 

'Data'  group didn't have any sub components. Also, I added a miscellaneous section to include all of the components that didn't fit into the predefined categories.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/920)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/ok-to-test
/assign

Preview: https://deploy-preview-920--competent-brattain-de2d6d.netlify.com/docs/components/

**Comment by Tabrizian** [comment]
Done!

**Comment by sarahmaddox** [comment]
Thanks! Those updates are perfect.

Alas, the PR that removed the ksonnet component has been merged before yours, which means that your PR now has merge conflicts. GitHub has given you a handy guide in a comment on the PR - click the **command line instructions** link next to "Rebase and merge".

The change you'll need to make areL

* Remove the **ksonnet** file from your PR.
* Replace it with the new [kustomize.md](https://github.com/kubeflow/website/blob/master/content/docs/components/kustomize.md) file - kustomize fits under "Miscellaneous" just as ksonnet did.
* Remove the "ksonnet" entry from the redirects file. (Let any incoming ksonnet links give a 404 error rather than redirecting to kustomize. I think a redirect would be misleading, as ksonnet and kustomize are different things entirely, even though Kubeflow is now using kustomize to achieve a similar goal.)

**Comment by sarahmaddox** [comment]
Ah, and we have another PR (https://github.com/kubeflow/website/pull/909) just merged, which added a new [metadata component](https://www.kubeflow.org/docs/components/metadata/). This will add to the merge conflicts on your PR. So, while you're at it ;)  please would you include the new [metadata.md](https://github.com/kubeflow/website/blob/master/content/docs/components/metadata.md) file in the "Miscellaneous" section.

(I'm now realising that we'll eventually need a section for components that cover the full ML workflow - pipelines, notebooks, metadata. But that change is likely to lead to some fairly lengthy discussion about the naming of the section. I think it'd be great to get your change merged as soon as we can. Then we can iteratively tackle further rearrangement(s).)

**Comment by Tabrizian** [comment]
@sarahmaddox, I can't see the "command line instructions". I think maybe it is only available to the maintainers of the repository.

**Comment by Tabrizian** [comment]
All of the requested changes were fixed!

**Comment by sarahmaddox** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
