### PR TITLE
Mark MPI-operator as beta

### PR DESCRIPTION
**Pull request by alculquicondor**
The APIs are beta.

Not sure if this was an oversight.

### CODE REVIEW

**Comment by alculquicondor** [comment]
@kubeflow/wg-training-leads

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by alculquicondor** [comment]
Tests are failing due to #3404

**Comment by alculquicondor** [comment]
I don't think that command works for me. Can anybody retrigger the tests?

**Comment by alculquicondor** [comment]
Passing :)

**Pull request merged**
