### PR TITLE
Fix KF_DIR env. var. description

### PR DESCRIPTION
**Pull request by mnmami**
Replace 'management' with 'kubeflow' to describe KF_DIR env. variable, as correctly described just above there.

### CODE REVIEW

**Comment by susan-shu-c** [comment]
Haha what, did we seriously submit the same fix in like 1 minute within each other #2440

Nice coincidence :)

**Comment by mnmami** [comment]
Haha, this happens only once each 5 million years :)

**Comment by 8bitmp3** [comment]
/assign @Bobgy 

I assume this is good

/lgtm

**Comment by Bobgy** [comment]
Thanks for the fix!
/approve

**Pull request merged**
