### PR TITLE
Fix link for v1alpha3 Katib SDK

### PR DESCRIPTION
**Pull request by andreyvelich**
After this PR: https://github.com/kubeflow/katib/pull/1252 we moved SDK for v1alpha3 under `sdk/python/v1alpha3` folder.
I fixed the link on the website to point for correct version.

Also, I added @sperlingxx to the OWNERS for Katib docs since he is helping us with developing.

/assign @sperlingxx @gaocegege @johnugeorge 

/cc @jlewi

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Review by andreyvelich — COMMENTED** [review]
/approve

**Pull request merged**
