### PR TITLE
Update the "MiniKF on laptop/desktop" guide

### PR DESCRIPTION
**Pull request by cspavlou**
Update the "MiniKF on laptop/desktop" guide to:

1.  Remove the out-of-date banner.
2. Rename the filename from `getting-started-minikf.md` to `minikf-vagrant.md`.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@cspavlou thank you for this! 

Is this documentation for MiniKF up to date for Kubeflow v1.3?

**Comment by cspavlou** [comment]
> @cspavlou thank you for this!
> 
> Is this documentation for MiniKF up to date for Kubeflow v1.3?

Yes, the instructions are up to date. We will release a new MiniKF with KF 1.3 once 1.3 is out officially.

**Comment by cspavlou** [comment]
@RFMVasconcelos are we good with this PR? Can you merge? This needs to go in before we cut the release. Thanks!

**Comment by RFMVasconcelos** [comment]
Great! LGTM! 
/lgtm
/approve

**Pull request merged**
