### PR TITLE
Update deployKF version to 1.8

### PR DESCRIPTION
**Pull request by thesuperzapper**
Now that https://github.com/kubeflow/website/pull/3724 is merged, I can finally update the deployKF link (which was no longer correct) without causing merge conflicts.

Also, deployKF [0.1.5](https://github.com/deployKF/deployKF/releases/tag/v0.1.5) now supports Kubeflow 1.8, so I have updated the table to reflect that.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@ederign sorry, made a typo, please LGTM again!

**Comment by thesuperzapper** [comment]
@andreyvelich can you please approve this update, it only affects deployKF.

**Review by andreyvelich — COMMENTED** [review]
Sure, thank you for the update @thesuperzapper!
/approve

**Pull request merged**
