### PR TITLE
Add ekf distro

### LINKED ISSUE #2639: Add Arrikto EKF distribution
Would like to add Arrikto's Enterprise Kubeflow distribution under "docs/Distributions" and in the table of distros on the getting-started/installation page.

### PR DESCRIPTION
**Pull request by shannonbradshaw**
Fixes #2639 

cc: @RFMVasconcelos here's the PR for the Arrikto EKF description as discussed on #2611

### CODE REVIEW

**Comment by cvenets** [comment]
@RFMVasconcelos can you please merge the above PR today?

This is fully supported by Arrikto, tested and validated for 1.3, so it needs to be in the distributions table for people to be able to find it, before 1.3 gets announced.

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos we have a precedent for adding distros that members of the community are actively maintaining. Argoflow is just one example. It is arbitrary to exclude Arrikto EKF at this point. I'd asked to have this included in #2611 and you and @thesuperzapper asked me to file a separate PR. Here it is. I would appreciate getting this merged in time for the release announcement. I have not heard any specific objections to including this so there does not seem to be a reason to hold off.

**Comment by RFMVasconcelos** [comment]
@shannonbradshaw to be honest, I feel uncomfortable making this decision on my own without a community agreement.

**Comment by shannonbradshaw** [comment]
@RFMVasconcelos what would it take to get community agreement? Also, I'm not sure I understand the hesitation. We seem to have made the decision about Argoflow without community agreement.

**Comment by thesuperzapper** [comment]
I don't see any significant issues with including this distribution in the docs. Clearly, once we have resolve Kubeflow's governance issues, and then setup a distribution validation system, this list will surely change anyway.

@RFMVasconcelos @Bobgy from a logistical perspective one of you will have to /approve this.

But @shannonbradshaw please only make one change per PR, (don't bring the GCP thing in, as it's unrelated, and just makes it less likely to get merged)

Once @shannonbradshaw removes that other commit, I believe it's fine to merge.

**Comment by shannonbradshaw** [comment]
@thesuperzapper @RFMVasconcelos @Bobgy ok I reverted the last commit per @thesuperzapper's request.

**Comment by thesuperzapper** [comment]
Do you really need to add the AWS acronym  @shannonbradshaw ?

**Comment by thesuperzapper** [comment]
/ok-to-test
/hold 

Holding for the AWS acronym

**Comment by shannonbradshaw** [comment]
@thesuperzapper if we use the acronym it should be defined. That is a docs best practice.

**Comment by andreyvelich** [comment]
From my point of view, we should include all distribution in the official Kubeflow docs that vendors support.
Until we don't have a clear vision on how to explain users how to use Kubeflow on various platforms, www.kubeflow.org/docs/distributions/ should be source of truth.

There are couple of advantages by doing this for Kubeflow 1.3:
1. Users will have more variety to deploy Kubeflow.
2. Kubeflow will be more popular and stable if we test it in the different environments.
3. Community will get support from the Cloud/Platform vendors.

I don't see any problems with merging this PR.

/lgtm
cc @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
Thank you for your comment @andreyvelich! Given your support + @thesuperzapper and @Bobgy's ack, I think I can pull the trigger to add this distribution without upsetting anyone in the community. 

Apologies for the delay on this @cvenets @shannonbradshaw @castrojo @jbottum, having more people chime in was important for me to be making this call.

/lgtm  
/approve

**Pull request merged**
