### PR TITLE
Add Kubeflow on VMware vSphere documentation

### PR DESCRIPTION
**Pull request by liuqi**
* Add a table entry in Installing Kubeflow

### CODE REVIEW

**Comment by annajung** [comment]
deploy preview: https://deploy-preview-3396--competent-brattain-de2d6d.netlify.app/docs/started/installing-kubeflow/#install-a-packaged-kubeflow-distribution

Thanks, @liuqi, this PR follows the plan to remove distribution https://github.com/kubeflow/website/issues/3074 by listing the name and link to the external doc.

/lgtm

cc @zijianjoy @thesuperzapper for review

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by liuqi** [comment]
> Holding until #3381 has been merged. Note, @liuqi you will also need to do a slight update to this PR so the table structure is in line with the new changes.
> 
> /hold

Sure. I will keep eye on #3381, and make changes accordingly.

**Comment by thesuperzapper** [comment]
@zijianjoy I think its best if we wait on the approval as this PR will inevitably need a rebase after https://github.com/kubeflow/website/pull/3381 is merged.

I will remove it for now so it does not accidentally get merged.

/remove-approve

**Comment by jbottum** [comment]
All - I am supportive of merging this PR in its currently approved state.  IMO, this PR  should not be dependent on #3381.    My reasoning is that 3381 has extensive changes that will require a ~ "looks good to me" from every distribution.   This PR, #3396, is specific to the work and contribution of a single distribution (Vmware) and their work should be acknowledged per their adherence to our process.

**Comment by liuqi** [comment]
> All - I am supportive of merging this PR in its currently approved state. IMO, this PR should not be dependent on #3381. My reasoning is that 3381 has extensive changes that will require a ~ "looks good to me" from every distribution. This PR, #3396, is specific to the work and contribution of a single distribution (Vmware) and their work should be acknowledged per their adherence to our process.

Yes. If this PR is merged before #3381, I will also watch that PR closely. So we could process these different distributions in batch with that one. It seems that would be much more clear and the VMware efforts could be noticed by users earlier. @thesuperzapper It would be highly appreciated if you could reconsider this PR. Thanks.

**Comment by annajung** [comment]
Hey folks, based on the [recent community meeting](https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit#heading=h.lknb7lltaq86), it was agreed that new distributions shouldn't be blocked by https://github.com/kubeflow/website/pull/3381. 

It would be great if someone else can remove the hold. If not, I'm planning on removing it on wed Dec 7th. 
cc @thesuperzapper @jbottum @zijianjoy

**Comment by zijianjoy** [comment]
/unhold

Based on community meeting's feedback, unholding this PR because the PR itself looks good and has been approved.

**Pull request merged**
