### PR TITLE
Split kubeflow-core into individual prototypes

### PR DESCRIPTION
**Pull request by ankushagarwal**
Update to kubeflow/kubeflow :  https://github.com/kubeflow/kubeflow/pull/1207

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/91)

### CODE REVIEW

**Comment by jlewi** [comment]
We should keep the website in sync with the current release.

Presumably kubeflow/kubeflow#1207 won't go out until 0.3.0 or possibly 0.2.3.

So we shouldn't commit this until then.

Alternatively there is an open issue #88 to version our website.

Ideally we would cut branches for every release and then kubeflow.org would point to the branch corresponding to the current release. This way we could continue to update docs at head.

**Comment by jlewi** [comment]
@ankushagarwal The docs are now versioned so this can be submitted.

**Comment by ankushagarwal** [comment]
@jlewi : Ready for review

**Comment by ankushagarwal** [comment]
Self LGTM-ed because @k8s-ci-robot removed LGTM label after a rebase.

**Pull request merged**
