### PR TITLE
hugo update

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/kubeflow/website/issues/2881
Checked everything locally

### CODE REVIEW

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you @Arhell ! 

/lgtm

**Comment by RFMVasconcelos** [comment]
This is still in draft mode. Happy to approve once you feel it's ready @Arhell

**Comment by Arhell** [comment]
cc @RFMVasconcelos

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you @Arhell ! 

/approve

**Pull request merged**
