### PR TITLE
Fix: fix broken images by using consistent path. Fixes #3250

### LINKED ISSUE #3250: Kserve pics are broken
Several pics/images are broken (not rendering) 
https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/

Here are the sections with broken pics
- https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/#listing
- https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/#creating
- https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/#inspecting
- https://www.kubeflow.org/docs/external-add-ons/kserve/webapp/#metrics

### PR DESCRIPTION
**Pull request by hsinhoyeh**
Fix broken image link on webpage due to a relative path used.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by zijianjoy** [comment]
Thank you @hsinhoyeh ! The change looks good by itself. However, looks like the external adds-on are not hosting the images in a central location https://github.com/kubeflow/website/tree/master/content/en/docs/images, but include them in the add-on's doc foler.

@shannonbradshaw What is your thought about it? Should external add-ons' pictures stay with their documents in the same folder?

**Comment by zijianjoy** [comment]
/lgtm
/approve

I am going to approve it so it can fix the current broken link issue. Thank you for your contribution!

**Comment by shannonbradshaw** [comment]
@james-jwu sorry, I was away for the holiday weekend. Yes. I think it makes more sense to host the images for a given external add on in the same directory as the docs for that add on.

**Comment by zijianjoy** [comment]
@shannonbradshaw Thank you for confirming! 

For Kubeflow components: Should we follow the same pattern of keeping doc and images closer to each other? What is the reason behind the differences between current structure https://github.com/kubeflow/website/tree/master/content/en/docs/images and add-ons?

**Pull request merged**
