### PR TITLE
Updated ICP setup guide for kfctl v0.7

### PR DESCRIPTION
**Pull request by sarahmaddox**
This PR updates the IBM Cloud Private setup guide to use the new kfctl semantics in v0.7.

The PR addresses some of the updates for https://github.com/kubeflow/website/issues/1226. Further PRs will update other docs.

Note: I've set the config URL to an interim path in `/kubeflow/manifests/master/`. When we know the path for the v0.7 RC1 release, we must update the path.

I've also fixed the list formatting throughout the page.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1241)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1241--competent-brattain-de2d6d.netlify.com/docs/started/cloud/getting-started-icp/

**Comment by sarahmaddox** [comment]
/assign @jinchihe 
/hold

@jinchihe Please would you take a look at these changes? I'll publish them along with the other kfctl updates, when we have RC1 for Kubeflow v0.7.0.

**Comment by jinchihe** [comment]
Wow! Some changes make the documentation more professional. Great thanks!  @sarahmaddox 

/lgtm

**Comment by sarahmaddox** [comment]
Thanks @jinchihe I've made some further changes, to use the latest config URL, and to set the version number to always correspond to the latest released version of Kubeflow. Please would you take a look and let me know if this works for IBM Cloud Private? The preview is in the same place: https://deploy-preview-1241--competent-brattain-de2d6d.netlify.com/docs/started/cloud/getting-started-icp/

**Comment by jinchihe** [comment]
> Thanks @jinchihe I've made some further changes, to use the latest config URL, and to set the version number to always correspond to the latest released version of Kubeflow. Please would you take a look and let me know if this works for IBM Cloud Private? The preview is in the same place: https://deploy-preview-1241--competent-brattain-de2d6d.netlify.com/docs/started/cloud/getting-started-icp/

Thanks @sarahmaddox That's OK for ICP. Great thanks for changes! 
/lgtm

**Comment by sarahmaddox** [comment]
@jinchihe We're thinking we should merge the v0.7 deployment guides now, with the RC releases, so that people have the opportunity to try them out. This PR is ready to go, but I'll hold it until the on-prem PR https://github.com/kubeflow/website/pull/1251 is merged, to avoid problems with the shared `kfctl_k8s_istio.0.7.0.yaml` config. If you're happy to LGTM again, then I'll remove the hold when applicable.

**Comment by jinchihe** [comment]
@sarahmaddox Make sense, Thanks!
/lgtm

**Comment by sarahmaddox** [comment]
The PR that updates the config file is now merged, so we can merge this PR too.

/hold cancel
/approve

**Pull request merged**
