### PR TITLE
Move `Azure` platform under /distributions

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Following the latest discussions on `platforms` and `distributions` starting a PR to move `Kubeflow on Azure`.

cc @joeliedtke @Bobgy @animeshsingh @8bitmp3

### CODE REVIEW

**Comment by 8bitmp3** [comment]
cc @aronchick @berndverst @eedorenko @sudivate

**Comment by RFMVasconcelos** [comment]
@Bobgy could you please review this? I have made a similar request to all the platforms so we get them moved to distributions.

This is merging to master and we can make sure we only point the main website to master once all the platforms have moved, so there is no weird scenario where one of the clouds would be outside and others inside the distributions folder.

/assign @Bobgy 

cc @animeshsingh @joeliedtke

**Review by berndverst — APPROVED** [review]

**Comment by RFMVasconcelos** [comment]
Thank you for reviewing and approving @berndverst ! 

There was a small conflict, that I just fixed. I think it's ready to merge and only needs your /lgtm :)

**Comment by RFMVasconcelos** [comment]
@8bitmp3 or @Bobgy, could I get a lgtm here please?

**Comment by RFMVasconcelos** [comment]
Oh, it seems I need to fix conflicts again

**Comment by RFMVasconcelos** [comment]
Good to go! :)

**Comment by 8bitmp3** [comment]
/lgtm

👍

**Comment by RFMVasconcelos** [comment]
Thank you @8bitmp3

**Pull request merged**
