### PR TITLE
Remove myself from approvers

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Comment by jbottum** [comment]
@rimolive can you please provide a description / reason for this change ?

**Comment by terrytangyuan** [comment]
> @rimolive can you please provide a description / reason for this change ?

See https://github.com/kubeflow/website/pull/3793#issuecomment-2224104762

@jbottum Please check messages in KSC channel in CNCF Slack.

**Comment by gregsheremeta** [comment]
/hold

Ricardo, your contributions are extremely valuable to this community. Please reconsider.

**Comment by hbelmiro** [comment]
IMHO, we should encourage people to review PRs and provide constructive feedback. What I've seen is exactly the opposite. We have very few people reviewing PRs and we're harassing them, which discourages them from continuing.

**Comment by StefanoFioravanzo** [comment]
By no means this PR should be approved. Ricardo is one of the our best contributors, and what happened in https://github.com/kubeflow/website/pull/3793#issuecomment-2224104762 should not result in loosing a great approver.

**Comment by StefanoFioravanzo** [comment]
@rimolive I hope you will reconsider. I am sure that our @kubeflow/kubeflow-steering-committee will take due action against people who do not respect our code of conduct and do not promote collaborative and open-source principles.

**Pull request closed without merging**
