### PR TITLE
Update owners file for Azure 

### PR DESCRIPTION
**Pull request by sudivate**
Update owners file for Azure

### CODE REVIEW

**Comment by sudivate** [comment]
Hi @8bitmp3, @sudivate, and @eedorenko are in the transitioning phase and would like to onboard new owners to the Azure area. Please guide on how can we proceed? 
cc-@aronchick

**Comment by 8bitmp3** [comment]
/lgtm

Thanks @sudivate !

cc @RFMVasconcelos (another 👍 OWNERS update)

/assign @animeshsingh @Bobgy @joeliedtke @rmgogogo

PTAL and approve if you can, thank you!

**Comment by Bobgy** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md) of the kubeflow org. You can then trigger verification by writing `/verify-owners` in a comment.
> - yilun-msft
>   - User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
>   - layouts/shortcodes/azure/OWNERS
> - shbijlan
>   - User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
>   - layouts/shortcodes/azure/OWNERS
> - nilspohlmann
>   - User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
>   - layouts/shortcodes/azure/OWNERS
> - vsetty-msft
>   - User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
>   - layouts/shortcodes/azure/OWNERS

Can you please add them to kubeflow org first?

**Comment by sudivate** [comment]
@Bobgy - Created PR https://github.com/kubeflow/internal-acls/pull/381 to add above users to the Kubeflow org

**Comment by Bobgy** [comment]
The github sync was successful, we need to wait for @yilun-msft @shbijlan @nilspohlmann @vsetty-msft to accept kubeflow invitation.

**Comment by 8bitmp3** [comment]
Hello @vsetty-msft Have you been added as a Kubeflow member in a separate PR? If so, can you please accept this invitation.  Thanks!! cc @sudivate @yilun-msft @shbijlan @NilsPohlmann @Bobgy

**Comment by 8bitmp3** [comment]
/verify-owners

cc @sudivate

**Comment by PatrickXYS** [comment]
The way to move forward is to remove @vsetty-msft from OWNERs file if there's no response

**Comment by PatrickXYS** [comment]
Please rebase master to pass conflicts

**Comment by joeliedtke** [comment]
@sudivate, Please update the PR to resolve the merge conflict.

**Comment by PatrickXYS** [comment]
Let's close PR if no updates recently, it has been 4 months.

**Pull request closed without merging**
