### PR TITLE
Add Myself into AWS OWNERS

### PR DESCRIPTION
**Pull request by PatrickXYS**
Add PatrickXYS@ as AWS Content Approvers

### CODE REVIEW

**Comment by 8bitmp3** [comment]
Good idea @PatrickXYS 

@Jeffwan Can you please `/lgtm` and `/approve` if all is good, since you're the sole approver at the moment?

**Comment by PatrickXYS** [comment]
@Bobgy Can you help lgtm + approve this PR since @Jeffwan is not available for now?

**Comment by Bobgy** [comment]
/lgtm
/approve
Sure

**Pull request merged**
