### PR TITLE
remove "Getting Started"/"Workstation Installation"

### LINKED ISSUE #2565: Move "Workstation Installation"  under "Distributions"
Currently, there is a confusing "Workstation Installation" page under "Getting Started" containing docs for the `MiniKF` and `MicroK8S Add-on` distributions.

Clearly they cannot be treated as special, and should be moved to "Distributions".
 
### Proposed structure (to split them up):

```
Distributions:
- MiniKF
   - Overview [renamed from  "Workstation Installation / MiniKF"
   - Deploy Kubeflow using MiniKF on AWS
   - Deploy Kubeflow using MiniKF on Google Cloud

- MicroK8S Add-on:
   - Overview [renamed from "Workstation Installation / Kubeflow on MicroK8s"
   - Kubeflow on Linux
   - Kubeflow on macOS
   - Kubeflow on Windows

- ...
```

### PR DESCRIPTION
**Pull request by thesuperzapper**
Closes #2565

As discussed in https://github.com/kubeflow/website/issues/2565, we are going to drop the "Workstation Installation" docs in favour of a refactored "Installing Kubeflow" page, see issue: https://github.com/kubeflow/website/issues/2590

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
Thank you for this PR @thesuperzapper ! 

/lgtm 

Do you think we should wait for #2590? They are a bit orthogonal, given the well structured `distributions` list.

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I agree that both this and #2590 should be merged at the same time, if only so that there aren't dangling links in the "Installing Kubeflow" page.

**Comment by RFMVasconcelos** [comment]
Sounds like a good plan :)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos as we are about to merge https://github.com/kubeflow/website/pull/2611, I think we can go ahead an merge this.

**Review by RFMVasconcelos — COMMENTED** [review]
@thesuperzapper as we now merged #2611, as agreed these `workstation` docs become redundant. 

/lgtm
/approve

**Pull request merged**
