### PR TITLE
web/Download component has moved - update tutorial

### PR DESCRIPTION
**Pull request by nicolaiskogheim**
Hi!

I'm going through the tutorials these days and needed to change a URL because the Download component has moved into a new directory.
I have tested that the new URL works with the example in the tutorial.

### CODE REVIEW

**Comment by nicolaiskogheim** [comment]
Ok it seems the bot took care of reviewers, so I'll unassign chensun. I'm new here as you might have guessed :)

/unassign  @chensun

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by nicolaiskogheim** [comment]
My PR is a duplicate of #3127 so I'll go ahead and close this one, but it would be nice to get the other one merged.

**Comment by nicolaiskogheim** [comment]
No I'm sorry, that other PR was for the v1 SDK, while mine is for the v2 SDK. Reopening.

**Pull request closed without merging**
