### PR TITLE
redirect ibm distribution docs to new website

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR redirects the "Kubeflow on IKS" docs to their new external website as part of https://github.com/kubeflow/website/issues/3074

The link to the new website was already added to the "installing kubeflow" guide in PR https://github.com/kubeflow/website/pull/3469.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@jbottum @zijianjoy @james-jwu I think this is important to redirect these old docs to the new website.

I am trying to close out https://github.com/kubeflow/website/issues/3074 to make the website actually clear about how to get Kubeflow installed (especially with all the new eyes about to look after the CNCF adoption).

**Comment by yhwang** [comment]
/lgtm

Tommy and I will update the index page in a separate PR.

**Comment by thesuperzapper** [comment]
@zijianjoy @james-jwu one of you will need to approve because I have updated redirects.

**Comment by thesuperzapper** [comment]
@zijianjoy since we have approval from @yhwang can you please approve this (as only you can do it).

**Comment by zijianjoy** [comment]
/lgtm
/approve 

The `content/en/_redirects` change can probably be improved for mapping the current subpage to the ibm corresponding page. But will let @yhwang to fix that in future PR.

**Pull request merged**
