### PR TITLE
Move all Azure specific shortcodes to Azure folder  

### PR DESCRIPTION
**Pull request by sudivate**
- Move all Azure specific shortcodes to the Azure folder  

- Fix broken link

### CODE REVIEW

**Comment by 8bitmp3** [comment]
PTAL and `/approve` if 👍 

/assign @animeshsingh @Bobgy @joeliedtke @rmgogogo

**Review by 8bitmp3 — APPROVED** [review]
thanks @sudivate

**Comment by Bobgy** [comment]
/approve
Thanks!

**Pull request merged**
