### PR TITLE
update content OWNERS to reflect current maintainers

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR updates the OWNERS of the primary content sections to reflect who is currently maintaining these sections:

- `docs/about/`
- `docs/components/`
- `docs/distributions/`
    - _NOTE: this section will be removed soon as part of https://github.com/kubeflow/website/issues/3074_
- `docs/external-add-ons/`
- `docs/started/`

Initially, I have added the following people as approvers/reviewers, as they are all active community leads, but we can expand this list as needed:
- @thesuperzapper (me)
- @jbottum
- @zijianjoy 

__NOTE 1:__ I have used the SAME reviewers/approvers because we want to automatically assign people who can actually approve the changes that people propose.

__NOTE 2:__ I have NOT changed the root OWNERS, I have a separate PR for that, so it can be discussed separately: https://github.com/kubeflow/website/pull/3559

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@zijianjoy @chensun @james-jwu  as you are currently the only active root owners, one of you will need to approve this.

**Comment by varodrig** [comment]
@thesuperzapper  following up on this PR. what's the current status? is it still on Hold?
cc @chensun

**Comment by thesuperzapper** [comment]
@varodrig we should probably still remove the two owners files:

- https://github.com/kubeflow/website/blob/master/content/en/docs/started/OWNERS
- https://github.com/kubeflow/website/blob/master/content/en/docs/about/OWNERS

As they mostly contain people who are no longer involved, so we dont want PRs for those sections getting assigned to them.

However, we should do that in another PR as this one is very out of date.

**Pull request closed without merging**
