### PR TITLE
Add a community panel to the Kubeflow front page (#1595)

### PR DESCRIPTION
**Pull request by simmscg**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1637)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1637--competent-brattain-de2d6d.netlify.com/

Fixes https://github.com/kubeflow/website/issues/1595

/ok-to-test

@simmscg This is looking good! Let us know when you're ready for review. I'd suggest @theadactyl and @abhi-g as reviewers.

**Comment by simmscg** [comment]
Added them in, thanks Sarah :)

**Comment by sarahmaddox** [comment]
/assign

/lgtm
/approve
/hold

This looks great to me. @abhi-g and @theadactyl do you have any comments?

**Pull request merged**
