### PR TITLE
Removed alpha notice from upgrade guide

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/1130

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1590)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1590--competent-brattain-de2d6d.netlify.com/docs/upgrading/upgrade/

/assign @richardsliu

**Comment by jlewi** [comment]
@richardsliu I think we might want to leave in the Alpha notice for now. I would consider upgrades still Alpha and not 1.0.

**Comment by richardsliu** [comment]
Right, I think we need to keep the feature Alpha.

**Comment by sarahmaddox** [comment]
OK thanks. I'll close this PR and mark the issue as resolved.

/close

**Pull request closed without merging**
