### PR TITLE
Restructured the website repo to allow for future i18n and content translation

### PR DESCRIPTION
**Pull request by sarahmaddox**
Preview: https://deploy-preview-1909--competent-brattain-de2d6d.netlify.app/

Fixes https://github.com/kubeflow/website/issues/1127

Notes:
* For a full description of what needs to be done for translation of the docs, see the product requirements doc:  http://bit.ly/kubeflow-i18n
* I thought about moving the images into the `/static/` directory so that we could share them across languages - but that would break the structure of the `OWNERS` files.
* After testing the redirects, I've discovered that the `_redirects` file needs to be in the language subdirectory. That is, for the English docs, the  `_redirects` file must be in `/en/`.
* I've removed the Kubeflow customization of the logic to create the **Edit this page** URL, in the Docsy partial template at https://github.com/kubeflow/website/blob/master/layouts/partials/page-meta-links.html#L9. Now that Kubeflow has the `/en/` directory, the Docsy logic should work. Note that it won't work until we've merged this PR. Click **Edit this page** on any page to see the URL constructed by the logic. Remove the `/en` part of the path to make the link work in the current directory structure (before this PR is merged).

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/assign @joeliedtke 
/assign @abhi-g 
/assign @janeman98 

This PR is now ready for review. Applying a hold to give us time for a careful review.
/hold

@janeman98 @joeliedtke @abhi-g Please would you take a look? See the PR description for preview link and more context.

**Comment by janeman98** [comment]
Thanks @sarahmaddox 
_Click **Edit this page** on any page to see the URL constructed by the logic. Remove the /en part of the path to make the link work in the current directory structure (before this PR is merged)._

I am looking at the preview. May I know where to find **Edit this page** in the preview?

**Comment by sarahmaddox** [comment]
Hallo @janeman98, the link is at the top right of every page, in the same panel that shows the list of headings on the page. If you're using a small screen, the panel may not appear. Try reducing the zoom factor in your browser.

**Comment by janeman98** [comment]
> Hallo @janeman98, the link is at the top right of every page, in the same panel that shows the list of headings on the page. If you're using a small screen, the panel may not appear. Try reducing the zoom factor in your browser.

Thanks @sarahmaddox ! I need to **maximize** my screen to see it. I am good now.

**Comment by janeman98** [comment]
I have randomly tested >40 pages in the preview. All worked as what mentioned above.

/lgtm

**Comment by sarahmaddox** [comment]
/hold cancel

Thanks @abhi-g and @janeman98 - could you re-LGTM now that I've merged with master?

**Pull request merged**
