### PR TITLE
Move `Google` platform under /distributions

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
Following the latest discussions on `platforms` and `distributions` starting a PR to move `Kubeflow on GCP`. 

cc @joeliedtke @Bobgy @animeshsingh

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@joeliedtke could you please review this? I have made a similar request to all the platforms so we get them moved to `distributions`. 

This is merging to master and we can make sure we only point the main website to master once all the platforms have moved, so there is no weird scenario where one of the clouds would be outside and others inside the `distributions` folder.

/assign @joeliedtke 

cc @Bobgy

**Comment by Bobgy** [comment]
/lgtm
/approve
Thank you @RFMVasconcelos for helping with this!
I checked redirects quickly, seems all good. Because we are moving into master, I think we can get them in faster

Can you please resolve the conflicts?

**Comment by RFMVasconcelos** [comment]
Thank you @Bobgy ! I will fix the conflicts and merge then :)

**Comment by RFMVasconcelos** [comment]
@Bobgy I have fixed conflicts, can you please LGTM ?

**Comment by Bobgy** [comment]
/lgtm
Thank you!

**Pull request merged**
