### PR TITLE
set delete-policy=abandon in deployment manager cleanup

### PR DESCRIPTION
**Pull request by MatthiasHertel**
referenced to: https://github.com/kubeflow/kubeflow/issues/1092

its not documented

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/357)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Friendly ping @MatthiasHertel do you have any response to my review comments?

**Comment by MatthiasHertel** [comment]
@sarahmaddox 

first of all sorry for my absence , I am currently writing my bachelor thesis (topic: mlaas - machine learning as a service -state of the art ... and a big part is kubeflow)  so that I have just little time 

 ... you are right just delete the reference not tthe resource is not a good fix for that and can be dangerous.

so that i would suggest to give a hint in the right place  to use the `delete-policy` argument is a good fix for the occurance of this issue. it will helps and explain what the problem is.

many greetings
matthias

**Comment by sarahmaddox** [comment]
Thanks @MatthiasHertel. Will you update this PR, or would you like me to create a separate PR and send it to you for review?

Good luck with your bachelor thesis. :)

**Comment by sarahmaddox** [comment]
/close

I'm going to close this PR, as it's obsolete given the comments on the PR and the related issue. If you want to re-open the PR and add the qualifications mentioned in the review comments, that's fine too. :)

Many thanks for the PR!

**Pull request closed without merging**
