### PR TITLE
Slack Channel name fixed

### PR DESCRIPTION
**Pull request by jnavarro86**
Just a small fix on the slack channel name

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1835)

### CODE REVIEW

**Comment by jnavarro86** [comment]
@googlebot I signed it!

**Comment by sarahmaddox** [comment]
/assign
/lgtm

Thanks for the fix, @jnavarro86! 

Please would you re-check the CLA - it needs to be signed with the same email address that you used for this commit (jnavarro86 at gmail.com).

**Comment by jnavarro86** [comment]
@googlebot I signed it!

**Comment by jnavarro86** [comment]
@sarahmaddox Thanks for the review! Signed with correct email.

**Comment by sarahmaddox** [comment]
Thanks @jnavarro86!
/ok-to-test
/approve

**Pull request merged**
