### PR TITLE
update docsy & hugo

### PR DESCRIPTION
**Pull request by Arhell**
update https://github.com/kubeflow/website/issues/2702

1. Updated hugo and docsy to the latest versions
2. Updated README
4. netlify.toml
5. Styles, rewrite to custom use **_styles_project**
6. https://github.com/kubeflow/website/pull/1870

### CODE REVIEW

**Comment by Arhell** [comment]
cc @joeliedtke

**Comment by thesuperzapper** [comment]
@Arhell this is pretty large PR, is it ready for review?

After it is, me and @RFMVasconcelos  could take a crack at reviewing it.

**Comment by Arhell** [comment]
> @Arhell this is pretty large PR, is it ready for review?
> 
> After it is, me and @RFMVasconcelos could take a crack at reviewing it.

Yes, ready, basically, as I wrote above, only docsy and hugo update, in general, this is a copy-paste of the main docsy repository

**Review by RFMVasconcelos — COMMENTED** [review]
Thank you for this effort @Arhell !

It would be great to also have a LGTM from @Bobgy or @joeliedtke who followed the process of implementation of Hugo, Netlify and Docsy from the start, so we are confident to merge such a large change.

Looking at your deployment, one thing that came to my attention was lack of indentation:
image

**Comment by thesuperzapper** [comment]
@Arhell it seems like you have increased the indentation beyond what is currently on kubeflow.org, making the more nested pages quite squished, for example: https://www.kubeflow.org/docs/components/pipelines/tutorials/
Old |  New
--- | ---
Screen Shot 2021-05-16 at 10 35 08 am | Screen Shot 2021-05-16 at 10 33 38 am




Also, I am not sure what is going on with the styling on the default `/docs` page at the top (under the kubeflow logo)
Screen Shot 2021-05-16 at 10 32 24 am

**Comment by Arhell** [comment]
> @Arhell it seems like you have increased the indentation beyond what is currently on kubeflow.org, making the more nested pages quite squished, for example: https://www.kubeflow.org/docs/components/pipelines/tutorials/
> 
> Old	New
> Screen Shot 2021-05-16 at 10 35 08 am	Screen Shot 2021-05-16 at 10 33 38 am
> Also, I am not sure what is going on with the styling on the default `/docs` page at the top (under the kubeflow logo)
> Screen Shot 2021-05-16 at 10 32 24 am

@thesuperzapper done

**Comment by thesuperzapper** [comment]
@Arhell I know its not strongly related, but can you also look at https://github.com/kubeflow/website/issues/2568, which still seems to happen with this PR?

**Comment by thesuperzapper** [comment]
@Bobgy this PR looks (visually) good to me, but I am not super familiar with docsy/hugo, so would appreciate a quick check from your end to check this looks sane.

**Comment by Arhell** [comment]
> @Arhell I know its not strongly related, but can you also look at #2568, which still seems to happen with this PR?
@thesuperzapper
I would like to correct this in the next PR, because this one is already very large

**Comment by thesuperzapper** [comment]
@Arhell sounds good, then all we need to get this merged is a review from @Bobgy

**Comment by Bobgy** [comment]
/cc @joeliedtke 
do you want to take a look?

/lgtm
just checking the updated website, it seems we don't have a lot of changes visually.

**Comment by Bobgy** [comment]
Hi @Arhell, thank you for this contribution!
Just curious, were there specific fixes/features you wanted for this upgrade?

**Comment by Arhell** [comment]
@Bobgy 
Hi, I want everything to be the latest version, there were some changes in the docsy and hugo itself (which would probably work faster)
+ the latest update is good anyway.

**Comment by Bobgy** [comment]
/lgtm
/approve

Fair enough, thank you for this contribution!

**Pull request merged**
