### PR TITLE
Cleanup the root owners file.

### PR DESCRIPTION
**Pull request by jlewi**
* Remove jlewi@ as an approver; I will no longer be actively reviewing
  miscellaneous doc changes
* Add @Bobgy  as another co-approver
* Add 8bitmp3 and RFMVasconcelos they are reviewing a lot of docs and
  working up to becoming approvers

* Prune the reviewers list so that PRs can be better autoassigned. We should
  arguably have OWNERs files in all subdirectories and rarely hit root owners
  file.
* Alphabetize the reviewers list

### CODE REVIEW

**Comment by Bobgy** [comment]
/lgtm

Sad to see you moving on, but good luck!

**Comment by 8bitmp3** [comment]
/lgtm

@jlewi Thanks for being awesome and always helping the community 🙏

**Comment by jlewi** [comment]
@8bitmp3 PTAL; I had to fix the OWNERs file; looks like @RFMVasconcelos isn't a member of the org yet.

**Comment by RFMVasconcelos** [comment]
@jlewi sorry for that. I have created this PR some time ago but it seems stuck -> https://github.com/kubeflow/community/pull/354

**Comment by RFMVasconcelos** [comment]
I realize that I needed to add myself here as well ->  https://github.com/kubeflow/internal-acls/pull/315

**Pull request merged**
