### PR TITLE
Fix favicons not showing Kubeflow logo

### PR DESCRIPTION
**Pull request by thesuperzapper**
Currently, some services are picking up the default favicon from Docsy (our theme) when linking to the Kubeflow website.

For example, try linking to Kubeflow website on slack, you will see a strange default icon:

Screenshot 2024-07-21 at 19 07 25

This PR fixes all issues with favicons and explicitly requests that people reindex them by adding a parameter `?v=2` to the URL paths.

You can confirm this PR works by looking at the preview and seeing if the favicon appears in your browser.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
I have confirmed that this PR fixes the issue on slack:

Screenshot 2024-07-21 at 19 19 06

**Comment by thesuperzapper** [comment]
@james-jwu @jbottum @andreyvelich @terrytangyuan can one of you please review or approve this website PR?

It looks bad if our favicon does not work properly, lol.

**Review by terrytangyuan — COMMENTED** [review]
How were the files for different devices generated from the original logo?

**Comment by thesuperzapper** [comment]
@terrytangyuan the new favicons were generated using the industry standard tool from the SVG of the logo:

- https://realfavicongenerator.net/

**Comment by terrytangyuan** [comment]
Thanks

/lgtm
/approve

**Comment by thesuperzapper** [comment]
This issue was also affecting Google, lol:

Screenshot 2024-07-21 at 19 57 30

**Pull request merged**
