### PR TITLE
Update ssh configuration for aws nodegroup

### PR DESCRIPTION
**Pull request by mbaijal**
Based on issue and discussions here: https://github.com/kubeflow/kubeflow/issues/3359

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/857)

### CODE REVIEW

**Comment by sarahmaddox** [comment]
@googlebot re-check

**Comment by sarahmaddox** [comment]
@mbaijal Please would you sign the CLA as requested by the bot. If you've already signed it, please check that the email address you used to sign the CLA is the same as the one used in this commit. If they're different, please sign the CLA with the email addressed used in this PR.

After signing the CLA, please add a comment on this PR - that will cause the bot to run the CLA check again. :)

**Comment by Jeffwan** [comment]
Thanks! LGTM!

**Comment by sarahmaddox** [comment]
@mbaijal Please would you verify the CLA as described in earlier comments.

**Comment by sarahmaddox** [comment]
@Jeffwan is this change important to get the AWS setup working properly? If so, would you like to create another PR to apply the fix?

@mbaijal thanks so much for this update. Because of the lack of response, I think it's best to close this PR and push the change through via another PR. I'll come back and close the PR early next week. Please do comment here if you're able to complete the CLA before then.

**Comment by sarahmaddox** [comment]
I'm closing this PR due to lack of response. Please do re-open it if you'd like to continue working on it.

/close

**Comment by Jeffwan** [comment]
> I'm closing this PR due to lack of response. Please do re-open it if you'd like to continue working on it.
> 
> /close

Thanks. I can make the changes in separate PRs. For user who customize their cluster, this will be helpful.

**Pull request closed without merging**
