### PR TITLE
[AWS] Update AWS Notebook Image to v1.2.0

### PR DESCRIPTION
**Pull request by PatrickXYS**
Update AWS Notebook Image from tag from `1.1.0` to `1.2.0`

### CODE REVIEW

**Comment by 8bitmp3** [comment]
👋 @Jeffwan (the 2nd approver in OWNERS) please `/lgtm` @PatrickXYS 's PR if it looks good 👍

**Comment by PatrickXYS** [comment]
/cc @jngo2

Can you take a look as well? Btw, @jngo2 will be part of kubeflow on AWS project in the future.

**Comment by PatrickXYS** [comment]
@8bitmp3 Hi since @Jeffwan is not working in AWS currently, can we move forward given I'm the only OWNER of AWS content?

**Comment by 8bitmp3** [comment]
@PatrickXYS Let me try

/lgtm

@Jeffwan can also LGTM, I think

**Comment by 8bitmp3** [comment]
Maybe we should update the OWNERS file @PatrickXYS and add 1-2 more approvers/reviewers cc @RFMVasconcelos

**Comment by PatrickXYS** [comment]
@8bitmp3  Yeah it sounds good, though I'm not sure how will be added as approvers/reviewers

In short term, AWS will have me as the only engineer on the whole Kubeflow project, other folks are working on Sagemaker part.

**Pull request merged**
