### PR TITLE
add safari favicon

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubeflow/website/issues/3124

### CODE REVIEW

**Comment by zijianjoy** [comment]
How is this icon being used?

**Comment by Arhell** [comment]
> How is this icon being used?

before
https://realfavicongenerator.net/favicon_checker?protocol=https&site=www.kubeflow.org%2F#.YfQzQurP1PZ

after add
https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-3126--competent-brattain-de2d6d.netlify.app%2F#.YfQzWurP1PY

this is for safari

**Comment by Arhell** [comment]
cc @zijianjoy

**Review by Arhell — COMMENTED** [review]
/assign @kimwnasptd

**Review by Arhell — COMMENTED** [review]
/unassign @kimwnasptd

**Comment by Arhell** [comment]
cc @kimwnasptd

**Pull request closed without merging**
