### PR TITLE
update IKS version

### PR DESCRIPTION
**Pull request by yhwang**
update the IKS version on the installing kubeflow page to v1.7.0

### CODE REVIEW

**Review by Tomcli — APPROVED** [review]
/lgtm
/approve

**Review by Arhell — COMMENTED** [review]
lgtm

**Review by Tomcli — APPROVED** [review]
/lgtm
/approve

**Comment by yhwang** [comment]
tag owners again
/cc @RFMVasconcelos @8bitmp3

**Comment by jbottum** [comment]
@yhwang thanks for this update.   do the links to the IKS website, etc work ?   I got a 404 on one of them.

**Comment by yhwang** [comment]
@jbottum 
there are two links and both work for me: 
- https://ibm.github.io/manifests/
- https://github.com/IBM/manifests/releases/tag/v1.7.0

**Pull request merged**
