### PR TITLE
Add MPIJob v1alpha2 API reference

### PR DESCRIPTION
**Pull request by terrytangyuan**
Part of https://github.com/kubeflow/mpi-operator/issues/217. 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Trying to following instruction [here](https://github.com/kubeflow/website/tree/affc79c5e7f6860214f6b2bdcb163294d99bdc41/gen-api-reference) but seeing the error below. Does anyone know how to fix it? What version of `gen-crd-api-reference-docs` have we used to generate the existing docs?

```
I0415 12:57:05.106541   52177 main.go:123] parsing go packages in directory github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha2
I0415 12:57:05.618382   52177 main.go:225] using package=github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha2
F0415 12:57:05.646690   52177 main.go:444] type invalid type has kind=Unsupported which is unhandled
```

**Comment by terrytangyuan** [comment]
cc'ing a few folks that modified the docs recently @richardsliu @kbhawkey @rlenferink

**Comment by kbhawkey** [comment]
Hello @terrytangyuan . A couple of questions:
- What type is the script failing on, https://github.com/ahmetb/gen-crd-api-reference-docs/blob/master/main.go#L457
- I suggest that you try the `gen-crd-api-reference-docs` program from the command line before running in the script.

**Comment by terrytangyuan** [comment]
Looks like these issues might be related:  
* https://github.com/ahmetb/gen-crd-api-reference-docs/issues/10 
* https://github.com/ahmetb/gen-crd-api-reference-docs/issues/12
Are there other alternatives for API doc generation?

**Comment by kbhawkey** [comment]
Ping @sarahmaddox

**Comment by sarahmaddox** [comment]
/assign @richardsliu 

@richardsliu Do you have any guidance to give here?

**Comment by richardsliu** [comment]
@zhenghuiwang How did you work around this issue?

**Comment by zhenghuiwang** [comment]
@terrytangyuan FYI this is [a workaround](https://github.com/kubeflow/kubeflow/issues/3723#issuecomment-585394918)  I tried last time for generating notebook controller API references.

**Comment by terrytangyuan** [comment]
Yea I read that and tried something similar - still no luck. Would it be permitted to add the docs manually? There seems to be more work working around the issues than manually writing up the docs.

**Comment by sarahmaddox** [comment]
FYI, please note that you'll need to move the files in this PR, due to PR https://github.com/kubeflow/website/pull/1909, which inserted the `/en/` element into the directory path for all content files. In other words, that PR moved all content files from `content/docs/...` to `content/en/docs/...`.

**Comment by terrytangyuan** [comment]
@sarahmaddox Thanks for the note. 

The problem right now is that the `gen-crd-api-reference-docs` tool is either not working or requires specific hack/fix for different controllers/projects. It would be good if someone from your team or from community can put together an alternative solution. Otherwise the API docs are not maintainable. In order to move forward with operator graduation, we may just add docs manually.

**Comment by sarahmaddox** [comment]
@terrytangyuan Thanks for the info. +1 to adding the MPIJob API reference manually for now. Looking at the reports on the various issues, it looks as if others are resorting to the same strategy until the `gen-crd-api-reference-docs` tool is fixed.

At this point, I think it's worth waiting a while to see if the `gen-crd-api-reference-docs` bugs get fixed, rather than creating an alternative solution for Kubeflow. But if someone in the community has the bandwidth and knowledge to create an alternative, that would be great too. @terrytangyuan can you create an issue in kubeflow/website, summarizing the problem, giving the current status, asking if anyone would like to develop an alternative tool, and linking to the relevant info:

* This PR (https://github.com/kubeflow/website/pull/1899)
* https://github.com/kubeflow/kubeflow/issues/3723#issuecomment-585394918
* https://github.com/ahmetb/gen-crd-api-reference-docs/issues/10
* https://github.com/ahmetb/gen-crd-api-reference-docs/issues/12

With that issue, we'll have one convenient place to point people too, and it will also provide the opportunity for someone to create the fix if they want to contribute in that way.

**Comment by terrytangyuan** [comment]
@sarahmaddox Thanks! I created an issue in https://github.com/kubeflow/website/issues/1924. I'll update this PR later with manually generated API docs for MPIJob.

**Comment by terrytangyuan** [comment]
@sarahmaddox I have added the API reference docs manually. Please take a look when you get a chance.

**Comment by sarahmaddox** [comment]
Preview:
* https://deploy-preview-1899--competent-brattain-de2d6d.netlify.app/docs/reference/overview/
* https://deploy-preview-1899--competent-brattain-de2d6d.netlify.app/docs/reference/mpijob/
* https://deploy-preview-1899--competent-brattain-de2d6d.netlify.app/docs/reference/mpijob/v1alpha2/
* https://deploy-preview-1899--competent-brattain-de2d6d.netlify.app/docs/reference/mpijob/v1alpha2/mpi/

**Comment by sarahmaddox** [comment]
Thanks @terrytangyuan!
/lgtm
/approve

**Pull request merged**
