### PR TITLE
Updated website kfctl and config versions to 1.0.2

### PR DESCRIPTION
**Pull request by sarahmaddox**
Fixes https://github.com/kubeflow/website/issues/1906

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview - examples of pages that use the version shortcodes:
* https://deploy-preview-1908--competent-brattain-de2d6d.netlify.app/docs/started/getting-started/#configuration-quick-reference
* https://deploy-preview-1908--competent-brattain-de2d6d.netlify.app/docs/gke/deploy/deploy-cli/

**Comment by sarahmaddox** [comment]
/assign @Jeffwan 

@Jeffwan Please would you review this PR?

**Comment by Jeffwan** [comment]
/lgtm

Thanks Sarah. It looks good to me

**Comment by sarahmaddox** [comment]
Thanks!
/approve

**Pull request merged**
