### PR TITLE
Fix other js features broken by heading anchor link.

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/kubeflow/website/issues/1036

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1039)

### CODE REVIEW

**Comment by Bobgy** [comment]
I wasn't familiar enough about hugo layouts. Putting a script.html actually overrides existing script.html. It left a hook in hooks/body-end.html. That was a better place for this.

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1039--competent-brattain-de2d6d.netlify.com/

**Comment by sarahmaddox** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
