### PR TITLE
Update the v0.6.2 gcp instructions.

### PR DESCRIPTION
**Pull request by jlewi**
With 0.6.2 we want to start using the --config flag.

We decided to pin to specific commits of the KFDef files. This
might be overkill because on the tip of the branch the config files
are named based on the version.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/1106)

### CODE REVIEW

**Comment by jlewi** [comment]
@gabrielwen lets not block on these changes.

**Comment by kunmingg** [comment]
/hold
Can you point to config after https://github.com/kubeflow/kubeflow/pull/4031 merge?

**Comment by jlewi** [comment]
/hold cancel
Pull in changes for kubeflow/kubeflow#4031

**Pull request merged**
