### PR TITLE
Upgraded Hugo and Docsy

### PR DESCRIPTION
**Pull request by sarahmaddox**
This PR upgrades the website to the latest version of the Docsy theme and to Hugo 0.68.3. 

Preview: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/

For special attention:

* From Hugo 0.60 onwards, the default Markdown renderer is Goldmark rather than the current default BlackFriday. I've created issue https://github.com/kubeflow/website/issues/1891 to track any breakages we find due to the new renderer. Then we can decide whether to upgrade and subsequently fix the oddities, or to force the use of the BlackFriday renderer.
* I've enabled the **Create project issue** link, which appears now below **Create documentation issue**. This will help steer people towards adding an issue in kubeflow/kubeflow rather than kubeflow/website when the issue isn't a doc issue. (The link was added to the Docsy templates a while ago but we haven't made use of it up to now.)

Other notes:

* I had a lot of trouble to get the Netlify deployment working. I was getting the following build error: `Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): resource "scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0" not found in file cache`. The eventual fix was: Remove all generated `resources/` files then regenerate them (using the `hugo` build command as usual) and force-commit the new `resources/` files.
* I've updated all the custom layouts and resources files that we still need, and removed those that we no longer need. (The reason for no longer needing them is that Docsy has now merged our suggested updates into the theme.)
* I had to add a few more custom files, because previous PRs had made changes to the Docsy theme files in the kubeflow/website repo, and those changes were therefore overwritten when I copied over the new Docsy theme files.

Fixes https://github.com/kubeflow/website/issues/1546
Fixes https://github.com/kubeflow/website/issues/1588

### CODE REVIEW

**Comment by sarahmaddox** [comment]
Preview: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com

**Comment by sarahmaddox** [comment]
Got the Netlify deployment working at last!! Note for posterity: 
* Remove all generated resources/ files from the repo, 
* then regenerate them (using the `hugo` build command as usual) and force-commit the new resources files.

**Comment by sarahmaddox** [comment]
This PF is now ready for review. Applying a hold to give us time for a thorough check.
/hold

/assign @joeliedtke 
/assign @janeman98 
/assign @abhi-g 

Hallo all, please would you take a look at this PR and at the preview of the entire site, and check for any oddities? Please see the PR description above for more context.

**Comment by janeman98** [comment]
Thanks @sarahmaddox
Should I report the following minor issue here or in [issue 1891](https://github.com/kubeflow/website/issues/1891)?

I noticed the [upgraded version](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/started/workstation/minikube-linux/#step-3-create-a-docker-id) is more restricted as they don't allow any space between [..] and (url) :
image

In the [previous version](https://www.kubeflow.org/docs/started/workstation/minikube-linux/#step-3-create-a-docker-id):
image

I can create a PR to fix this, or should we fix this in PR for issue 1891?

**Comment by abhi-g** [comment]
Thanks for the herculean effort @sarahmaddox. So far looks good. I'll spend some more time browsing through the previews..

**Comment by abhi-g** [comment]
The "Edit this page" link on most pages seems broken, but that could be due to the internationalization setup possibly in this PR or otherwise.

**Comment by sarahmaddox** [comment]
> I noticed the [upgraded version](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/started/workstation/minikube-linux/#step-3-create-a-docker-id) is more restricted as they don't allow any space between [..] and (url) :
> image

> I can create a PR to fix this, or should we fix this in PR for issue 1891?

Thanks @janeman98 Please would you create a PR to remove the space now? I think that having the space is not valid Markdown, and the previous parser was too lenient in this case.

**Comment by sarahmaddox** [comment]
> The "Edit this page" link on most pages seems broken, but that could be due to the internationalization setup possibly in this PR or otherwise.

Oh well spotted! I need to delve into the Docsy templates to diagnose the problem. At this point, the Kubeflow doc structure is set up for only one language, and we therefore don't have an `/en` section in our path. Docsy should be able to handle this, and has done so up to now, but it looks like something has changed. Stay tuned.

**Comment by janeman98** [comment]
> > I noticed the [upgraded version](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/started/workstation/minikube-linux/#step-3-create-a-docker-id) is more restricted as they don't allow any space between [..] and (url) :
> > image
> 
> > I can create a PR to fix this, or should we fix this in PR for issue 1891?
> 
> Thanks @janeman98 Please would you create a PR to remove the space now? I think that having the space is not valid Markdown, and the previous parser was too lenient in this case.

Thanks @sarahmaddox. Will create a PR to fix it. I have put the other issues I found in tracking issue 1891.

**Comment by sarahmaddox** [comment]
@abhi-g I've fixed the **Edit this page** link. Thanks for spotting that! To fix it, I've hacked our custom version of the `page-meta-links.html` template. This problem will (should) go away when we enable multiple languages on the Kubeflow site, so I'm happy with a hack for now.

In the same commit, I've updated the config file to enable the **Create project issue** link, which appears now below **Create documentation issue** on every page. This will help steer people towards adding an issue in kubeflow/kubeflow rather than kubeflow/website when the issue isn't a doc issue. (The link was added to the Docsy templates a while ago but we haven't made use of it up to now.)

**Comment by janeman98** [comment]
Thanks @sarahmaddox for your huge effort to make this work!
I have finished my review and reported all oddities in the tracking issue 1891.

/lgtm

**Comment by abhi-g** [comment]
Thank you @janeman98 for the thorough combing!

/lgtm
/approve

@sarahmaddox please feel free to merge when ready. Tracking all outstanding issues as separate issues to be fixed individually makes sense.

**Comment by sarahmaddox** [comment]
Thanks @abhi-g and @janeman98!
/hold cancel

**Pull request merged**
