### PR TITLE
Update vSphere distro version and website link

### PR DESCRIPTION
**Pull request by harperjuanl**
Update vSphere Kubeflow distribution version and the website link

### CODE REVIEW

**Comment by thesuperzapper** [comment]
/lgtm

@zijianjoy only you or @james-jwu can approve

**Comment by thesuperzapper** [comment]
@harperjuanl Also, are you sure you don't also want to update the name from "Kubeflow on vSphere" to "vSphere Machine Learning Extension" which is what you list on your website: https://vmware.github.io/vSphere-machine-learning-extension/index.html

**Comment by harperjuanl** [comment]
> @harperjuanl Also, are you sure you don't also want to update the name from "Kubeflow on vSphere" to "vSphere Machine Learning Extension" which is what you list on your website: https://vmware.github.io/vSphere-machine-learning-extension/index.html

@thesuperzapper Thanks a lot, we don't need to update the name.

**Comment by thesuperzapper** [comment]
@zijianjoy can you please approve this small fix of the link?

**Pull request merged**
