### PR TITLE
corrected doc text to match what's in pipelines

### PR DESCRIPTION
**Pull request by kmarquardsen**
Reference: https://github.com/kubeflow/pipelines/blob/603597d65b1092d28d77111051e1175c40d77fea/frontend/src/lib/Buttons.ts#L134

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/website/536)

### CODE REVIEW

**Comment by kmarquardsen** [comment]
@sarahmaddox good call. let me clean it up and see if there's others

**Comment by sarahmaddox** [comment]
@kmarquardsen I've just realized: It may be that this fix gets wrapped up in the larger effort when we update the docs for the new UI (https://github.com/kubeflow/website/issues/505).

**Comment by kmarquardsen** [comment]
Sounds good @sarahmaddox let me close this and look through open issues 😄

**Pull request closed without merging**
