### PR TITLE
fix: Updated description for pipeline_version_id in Runs and Recurring Runs API docs

### PR DESCRIPTION
**Pull request by amadhusu**
This doc is generated via the tool (https://github.com/kubeflow/pipelines/tree/master/backend/api#updating-of-api-reference-documentation) after the changes [#10581](https://github.com/kubeflow/pipelines/pull/10581) and [#10591](https://github.com/kubeflow/pipelines/pull/10591) were merged.
 
This will resolve [#10451](https://github.com/kubeflow/pipelines/issues/10451)

**Description**
The updated API docs from the tool should reflect the Deprecated status of pipeline_version_id in Runs and Recurring Runs.

### CODE REVIEW

**Review by hbelmiro — COMMENTED** [review]
/lgtm

**Review by diegolovison — APPROVED** [review]

**Comment by rimolive** [comment]
@Tomcli @chensun As the Pipelines WG approvers, can you confirm if manual changes to these pages look good? Or there is a tool that generates this content?

**Comment by amadhusu** [comment]
@Tomcli @chensun reiterating @rimolive's question.

**Review by Tomcli — APPROVED** [review]
/lgtm
The version id is under `pipeline_version_reference` for v2
https://github.com/kubeflow/pipelines/blob/master/backend/api/v2beta1/run.proto#L211-L217

**Comment by chensun** [comment]
This file is generated via a tool. Can you follow this instruction to check if it indeed needs update?
https://github.com/kubeflow/pipelines/tree/master/backend/api#updating-of-api-reference-documentation

**Comment by amadhusu** [comment]
> This file is generated via a tool. Can you follow this instruction to check if it indeed needs update? https://github.com/kubeflow/pipelines/tree/master/backend/api#updating-of-api-reference-documentation

@chensun So the tool insisted this API doc doesn't need an update. After digging into why, I believe it is due to this -> https://github.com/kubeflow/pipelines/blob/master/backend/api/v2beta1/run.proto#L165 and https://github.com/kubeflow/pipelines/blob/master/backend/api/v2beta1/recurring_run.proto#L89 . 

Screenshot from 2024-03-14 16-14-50


Any reason to keep this deprecated field when we refer the same thing underneath `pipeline_version_reference` or can we do away with the deprecated field?

**Comment by amadhusu** [comment]
@chensun @Tomcli After updating kubeflow/pipelines w.r.t. [#10581](https://github.com/kubeflow/pipelines/pull/10581) and [#10591](https://github.com/kubeflow/pipelines/pull/10591). This API doc is generated from the tool and now contains the relevant information to resolve this issue (Thanks for pointing to the tool). Can you guys review the same?

**Review by Tomcli — COMMENTED** [review]
/lgtm

**Review by chensun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
