### PR TITLE
Fixed oddities caused by change to Goldmark renderer

### LINKED ISSUE #1891: Tracking issue: Rendering oddities cause by change to Goldmark renderer
We're upgrading to the latest version of the Docsy theme and to Hugo 0.68.3. From Hugo 0.60 onwards, the default Markdown renderer is Goldmark rather than the current default BlackFriday (see [Hugo docs](https://gohugo.io/getting-started/configuration-markup#goldmark)). We can choose to force the use of BlackFriday rather than Goldmark if necessary, but we're told that Goldmark gives a better overall experience (although both Goldmark and BlackFriday have their own set of oddities).

Let's list any breakages we find in the [preview from PR # 1870](https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/) so that we can decide whether to upgrade then fix the oddities, or to force the use of BlackFriday renderer.

* Numbered list is broken when it includes code snippets: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/other-guides/kustomize/#applying-the-configuration-to-your-kubeflow-cluster
* Numbered list is broken when it includes an indented bulleted list: https://deploy-preview-1870--competent-brattain-de2d6d.netlify.com/docs/gke/deploy/project-setup/

### PR DESCRIPTION
**Pull request by janeman98**
Fixes #1891

### CODE REVIEW

**Comment by janeman98** [comment]
Preview : https://deploy-preview-1898--competent-brattain-de2d6d.netlify.com/

**Comment by janeman98** [comment]
/assign @sarahmaddox 

I have fixed most of the formatting issues, except 2 files, in which the numbered lists are broken after **shortcode**. I will fix that in a separate PR.

**Comment by janeman98** [comment]
@sarahmaddox 
This PR is ready to be reviewed.

**Comment by sarahmaddox** [comment]
Well done and thank you for the sterling work @janeman98!
/lgtm
/approve

**Comment by janeman98** [comment]
Thanks @sarahmaddox !

**Pull request merged**
