### PR TITLE
Fixed instruction for installing kustomize

### LINKED ISSUE #1917: Step in Installing kustomize throws an error
Following the link https://www.kubeflow.org/docs/other-guides/kustomize/ to install kustomize.

when I tried to run the mv command mentioned below, throws an error.  It looks like tar ball is not extracting with the name of the file. Instead i noticed that it extracts as the file "kustomize" under the current directory.

Error:
$ mv kustomize_*_${opsys}_amd64 ${HOME}/bin/kustomize
mv: cannot stat ‘kustomize_*_linux_amd64’: No such file or directory

-------
Move the binary:
**mv kustomize_*_${opsys}_amd64 ${HOME}/bin/kustomize**

### PR DESCRIPTION
**Pull request by janeman98**
Fixes #1917 

Fixed instruction for installing kustomize.

### CODE REVIEW

**Comment by sarahmaddox** [comment]
/lgtm
/approve
Thanks @janeman98

**Comment by arshashi** [comment]
Not fixed yet.  there is no command to  untar the tar.gz, and when we run mv command it says No such file or directory.   

Please refer the below commands.

root@servername:~/build/kubernetes# mkdir -p ${HOME}/bin
root@servername:~/build/kubernetes# mv kustomize_*_${opsys}_amd64 ${HOME}/bin/kustomize
mv: cannot stat 'kustomize_*_linux_amd64': No such file or directory
root@servername:~/build/kubernetes# ls
get_helm.sh  kustomize  kustomize_v3.5.4_linux_amd64.tar.gz
root@servername:~/build/kubernetes# tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
root@servername:~/build/kubernetes# ls
get_helm.sh  kustomize  kustomize_v3.5.4_linux_amd64.tar.gz
root@servername:~/build/kubernetes# tar -zxvf kustomize_v3.5.4_linux_amd64.tar.gz
kustomize
root@servername:~/build/kubernetes# cd kustomize
bash: cd: kustomize: Not a directory
root@servername:~/build/kubernetes#

**Comment by arshashi** [comment]
> Fixes #1917
> 
> Fixed instruction for installing kustomize.

Instructions still not accurate.  There is no command to untar the tar.gz, and when we run mv command it says No such file or directory.

Please refer the below commands.



root@servername:~/build/kubernetes# export opsys=linux
root@servername:~/build/kubernetes# curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
> grep browser_download |\
> grep download/kustomize |\
> grep -m 1 $opsys |\
> cut -d '"' -f 4 |\
> xargs curl -O -L
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   648  100   648    0     0    493      0  0:00:01  0:00:01 --:--:--   493
100 10.9M  100 10.9M    0     0   879k      0  0:00:12  0:00:12 --:--:-- 1810k
root@servername:~/build/kubernetes# tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
root@servername:/build/kubernetes# mkdir -p ${HOME}/bin
root@servername:/build/kubernetes# mv kustomize__${opsys}amd64 ${HOME}/bin/kustomize
mv: cannot stat 'kustomizelinux_amd64': No such file or directory
root@servername:/build/kubernetes# ls
get_helm.sh kustomize kustomize_v3.5.4_linux_amd64.tar.gz
root@servername:/build/kubernetes# tar xzf ./kustomize_v*${opsys}_amd64.tar.gz
root@servername:/build/kubernetes# ls
get_helm.sh kustomize kustomize_v3.5.4_linux_amd64.tar.gz
root@servername:/build/kubernetes# tar -zxvf kustomize_v3.5.4_linux_amd64.tar.gz
kustomize
root@servername:/build/kubernetes# cd kustomize
bash: cd: kustomize: Not a directory
root@servername:/build/kubernetes#

**Comment by janeman98** [comment]
@arshashi 
Thanks for testing out the fix. After the fix, in https://www.kubeflow.org/docs/other-guides/kustomize/#installing-kustomize, we have :
image

In short, we are moving `kustomize`, not `kustomize_${opsys}amd64`

**Comment by arshashi** [comment]
@janeman98 this works like a gem. Thanks for fixing the issue.

**Pull request merged**
