### PR TITLE
Fix method name in the sdk example

### PR DESCRIPTION
**Pull request by milosjava**
Quick fix for the method name. Naming the example method “tensorboard_vis” is misleading here because this example is related to webapp visualisation and not tensorboard visualisation (present in the section above).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by hbelmiro — COMMENTED** [review]
/lgtm

@chensun can you PTAL?

**Comment by hbelmiro** [comment]
@milosjava can you please rebase?

**Comment by milosjava** [comment]
this PR was made long ago, I will create a new one with some additional changes

**Pull request closed without merging**
