### PR TITLE
Move KFServing to under Components, out of `Tools for serving`

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
This follows #2535 proposal and aims at making KFServing a first class citizen of components.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
@animeshsingh following #2535 this PR moves KFServing to be a top Kubeflow component as it should be given your great work.

Could you please review/merge this PR?

**Comment by RFMVasconcelos** [comment]
Or, alternatively, @Bobgy ?

**Comment by Bobgy** [comment]
@animeshsingh leads KFServing, so I think it's better to leave it to him to decide.

**Comment by animeshsingh** [comment]
thanks

/lgtm
/approve

**Pull request merged**
