### PR TITLE
Update IKS doc for kubeflow v1.5

### PR DESCRIPTION
**Pull request by yhwang**
Update the instructions to point to the manifests repo
which is used to deploy kubeflow v1.5 on IBM IKS cluster

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by yhwang** [comment]
I will update IKS version in `started/installing-kubeflow` page in a separate PR.

**Review by Arhell — COMMENTED** [review]
/assign @zijianjoy

**Pull request merged**
