### PR TITLE
mv Istio under components + add OWNERS

### PR DESCRIPTION
**Pull request by RFMVasconcelos**
See #2471

### CODE REVIEW

**Comment by yanniszark** [comment]
@RFMVasconcelos my username is all small caps:
`yanniszark`

Otherwise lgtm :)

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by RFMVasconcelos** [comment]
Sorry about that @yanniszark! Fixing ;)

**Comment by RFMVasconcelos** [comment]
@yanniszark fixed!

**Comment by Bobgy** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
