### PR TITLE
add thesuperzapper to OWNERS

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR adds me to `approvers` in the root OWNERs file, this will help me and @RFMVasconcelos continue to improve the website.

### CODE REVIEW

**Comment by RFMVasconcelos** [comment]
Hey @thesuperzapper! Are there any specific PRs you need to approve?

I wonder what motivates this PR. If you are experiencing delays on review and approval of certain PRs feel free to ping me :)

**Comment by thesuperzapper** [comment]
@RFMVasconcelos this request is in no way a comment on your responsiveness, I ​just think having multiple active approvers is a healthy thing! (The [Contributing Guidelines](https://www.kubeflow.org/docs/about/contributing/#maintaining-owners-files) also encourage this!)

_PS: the guidelines also encourage removing inactive people, which we should discuss in another issue_

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by thesuperzapper** [comment]
@animeshsingh @Bobgy @james-jwu  @knkski @zijianjoy (current OWNERS)

Since @RFMVasconcelos  was removed from OWNERS in PR https://github.com/kubeflow/website/pull/2981, it's probably a good time to consider adding me to the OWNERS list again.

I have a very long and consistent history of contributing to the docs over the past 2 years, and was in fact the person who nominated @RFMVasconcelos for owners (see https://github.com/kubeflow/website/pull/2539)!

**Comment by Arhell** [comment]
сс @Bobgy

**Comment by thesuperzapper** [comment]
@Bobgy any chance we can add me to owners, this will help with things like docsy / hugo updates

**Comment by theadactyl** [comment]
Hi @thesuperzapper, can you open a new PR adding yourself to reviewers instead? We are going to be rolling out a new policy on contributor role hierarchy and graduation, which includes requirements around having experience as a reviewer in advance of being promoted to approver, etc.

**Comment by thesuperzapper** [comment]
@theadactyl I think we already have a policy for adding OWNERS, but it's just not being followed.

I have just raised proposal https://github.com/kubeflow/community/issues/546 to start the process of cleaning up all the OWNERS files, I would appreciate your input on that issue.

**Comment by theadactyl** [comment]
I think that we need to refresh our policy and apply it consistently, as
well as do an audit of OWNERs files. I see your proposal and think that's a
great place to start the conversation.

**Pull request closed without merging**
